// Generated by Claude Code
import CoreLocation
import SwiftUI

/// Schritt "Stadt/Region" -- Herzstück dieser Onboarding-Überarbeitung.
/// Zeigt alle fünf Städte aus `city_regions` fest an (München, Berlin,
/// Hamburg, Frankfurt, Wien), unabhängig von `is_active`, sortiert nach
/// `sort_order`. Die vier noch nicht redaktionell scharf geschalteten
/// Städte (`editorial_status != "live"`) bekommen ein "Bald verfügbar"-
/// Badge, bleiben aber auswählbar -- die spätere Umschaltung übernimmt
/// weiterhin `setPreferredRegion`/`profiles.preferred_region_id`, keine
/// Schemaänderung. Automatischer Standortzugriff bleibt als zusätzliche,
/// gleichwertige Option bestehen (per GPS die nächstgelegene Stadt
/// vorschlagen) und fällt bei Ablehnung/Fehler auf dieselbe Liste zurück.
struct CityPickerStepView: View {
    @ObservedObject var auth: AuthStore
    let repository: UserRepository?
    let onFinished: () -> Void

    @State private var cities: [CityRegionOption] = []
    @State private var selectedCityID: UUID?
    @State private var isWorking = false
    @State private var isLoadingCities = true
    @State private var errorMessage: String?

    var body: some View {
        VStack(spacing: 0) {
            ScrollView {
                VStack(spacing: 20) {
                    VStack(spacing: 8) {
                        Image(systemName: "map.circle")
                            .font(.system(size: 52))
                            .foregroundStyle(KlangradarTheme.accent)
                        Text("Wo möchtest du Konzerte entdecken?")
                            .font(.largeTitle.bold())
                            .multilineTextAlignment(.center)
                        Text("Wähle deine Stadt aus. Du kannst das später in deinem Profil jederzeit ändern.")
                            .font(.title3)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.center)
                    }
                    .padding(.top, 8)

                    Button {
                        Task { await requestLocation() }
                    } label: {
                        Label("Meinen Standort verwenden", systemImage: "location.fill")
                            .frame(maxWidth: .infinity)
                    }
                    .authSecondaryButtonStyle()
                    .controlSize(.large)
                    .disabled(isWorking)

                    if isLoadingCities {
                        ProgressView().padding(.top, 16)
                    } else {
                        VStack(spacing: 12) {
                            ForEach(cities) { city in
                                CityOptionRow(city: city, isSelected: selectedCityID == city.id) {
                                    selectedCityID = city.id
                                }
                            }
                        }
                    }

                    if let errorMessage {
                        Text(errorMessage)
                            .font(.footnote)
                            .foregroundStyle(.red)
                            .multilineTextAlignment(.center)
                    }
                }
                .padding(28)
            }
            .scrollDismissesKeyboard(.interactively)

            VStack(spacing: 14) {
                Button("Weiter") { Task { await confirmSelection() } }
                    .authPrimaryButtonStyle()
                    .controlSize(.large)
                    .frame(maxWidth: .infinity)
                    .disabled(selectedCityID == nil || isWorking)

                Button("Überspringen") { onFinished() }
                    .font(.subheadline.weight(.medium))
                    .disabled(isWorking)
            }
            .padding(.horizontal, 28)
            .padding(.bottom, 16)
        }
        .overlay {
            if isWorking { ProgressView().controlSize(.large) }
        }
        .task { await loadCities() }
        .onboardingChrome()
    }

    private func loadCities() async {
        isLoadingCities = true
        defer { isLoadingCities = false }
        cities = (try? await repository?.allCityRegions()) ?? []
        if selectedCityID == nil {
            selectedCityID = cities.first(where: { $0.isLive })?.id
        }
    }

    private func requestLocation() async {
        isWorking = true
        errorMessage = nil
        defer { isWorking = false }
        do {
            let coordinate = try await LocationRequester().requestOnce()
            if let nearest = nearestCity(to: coordinate) {
                selectedCityID = nearest.id
            }
        } catch {
            // Ablehnung/Fehler ist kein Blocker -- die manuelle Liste bleibt
            // als gleichwertiger Weg sichtbar.
        }
    }

    private func nearestCity(to coordinate: CLLocationCoordinate2D) -> CityRegionOption? {
        cities
            .compactMap { city -> (CityRegionOption, Double)? in
                guard let lat = city.latitude, let lng = city.longitude else { return nil }
                let dLat = lat - coordinate.latitude
                let dLng = lng - coordinate.longitude
                return (city, dLat * dLat + dLng * dLng)
            }
            .min { $0.1 < $1.1 }?.0
    }

    private func confirmSelection() async {
        guard let selectedCityID else { onFinished(); return }
        isWorking = true
        errorMessage = nil
        defer { isWorking = false }
        if let repository, let userID = auth.userID, let token = auth.accessToken {
            try? await repository.setPreferredRegion(regionID: selectedCityID, userID: userID, token: token)
        }
        onFinished()
    }
}

private struct CityOptionRow: View {
    let city: CityRegionOption
    let isSelected: Bool
    let onSelect: () -> Void

    var body: some View {
        Button(action: onSelect) {
            HStack(spacing: 12) {
                VStack(alignment: .leading, spacing: 2) {
                    HStack(spacing: 8) {
                        Text(city.nameDE)
                            .font(.headline)
                            .foregroundStyle(.primary)
                        if !city.isLive {
                            Text("Beta")
                                .font(.caption2.weight(.semibold))
                                .padding(.horizontal, 8)
                                .padding(.vertical, 3)
                                .background(.secondary.opacity(0.15), in: Capsule())
                                .foregroundStyle(.secondary)
                        }
                    }
                    if let regionName = city.regionName {
                        Text(regionName)
                            .font(.footnote)
                            .foregroundStyle(.secondary)
                    }
                }
                Spacer()
                Image(systemName: isSelected ? "checkmark.circle.fill" : "circle")
                    .font(.title3)
                    .foregroundStyle(isSelected ? KlangradarTheme.accent : Color.secondary.opacity(0.5))
            }
            .padding(16)
            .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 16, style: .continuous))
            .overlay {
                RoundedRectangle(cornerRadius: 16, style: .continuous)
                    .stroke(isSelected ? KlangradarTheme.accent : .clear, lineWidth: 2)
            }
        }
        .buttonStyle(.plain)
        .accessibilityElement(children: .combine)
        .accessibilityAddTraits(isSelected ? [.isSelected] : [])
    }
}
