// Generated by Claude Code
import SwiftUI

/// Schritt "Personen/Ensembles/Venues folgen" (Punkt 6 der vom Nutzer
/// vorgegebenen Ziel-Struktur) -- zwischen Interessen (Schritt 5) und
/// Benachrichtigungen. Ursprünglich ein einzelner Schritt mit
/// Personen/Ensembles/Venues als Segmenten in einem Picker; auf Nutzer-
/// wunsch (2026-09-02) jetzt EIN eigener Onboarding-Schritt pro Kategorie
/// (siehe OnboardingView.Step .followPersons/.followEnsembles/.followVenues),
/// direkt nach den Genres statt danach — Werke tauchen im Onboarding dadurch
/// gar nicht mehr auf.
///
/// Layout auf Nutzerwunsch (2026-09-03) an Spotifys Onboarding-Grid
/// angelehnt: Personen/Ensembles als 3-spaltiges Grid mit kreisförmigem
/// Bild + Name darunter, Venues als 2-spaltiges Grid mit rechteckigem Bild
/// (Venues sind Orte, kein Kreis-Porträt). Sobald gesucht wird, wechselt die
/// Ansicht auf eine kompakte Liste (kleines Bild + Name in einer Zeile) --
/// beim Grid würde eine gefilterte, oft kurze Trefferliste unnötig viel
/// Leerraum lassen.
///
/// Datenquelle UND Folgen-Mechanismus sind bewusst dieselben, die bereits
/// an anderer Stelle existieren: `UserRepository.interestOptions(_:)` liefert
/// dieselbe alphabetische Personen-/Ensemble-/Venue-Liste, die auch
/// `InterestsView` (Profil → Interessen) verwendet, und "Folgen" ruft
/// dieselbe `setInterest`-RPC/-Tabelle auf, die auch `FollowStore` (Folgen-
/// Button auf Detailseiten) und `InterestsView` nutzen -- ein Follow hier,
/// auf einer Detailseite oder in den Interessen-Einstellungen spiegelt
/// daher konsequent denselben Zustand wider. Es gibt keinen separaten
/// Onboarding-eigenen Folgen-Mechanismus und keine neue Tabelle.
struct FollowCategoryStepView: View {
    @ObservedObject var auth: AuthStore
    let repository: UserRepository?
    let category: InterestCategory
    let header: OnboardingProgressHeader
    let onFinished: () -> Void

    @EnvironmentObject private var follows: FollowStore

    @State private var options: [InterestOption] = []
    // Generated by Claude Code — startet jetzt bereits geladen (statt erst
    // in .task auf true zu wechseln): Der Sprung von leer/ungeladen zu
    // "lädt" zu "Daten da" innerhalb des allerersten Layout-Durchgangs ließ
    // die vom Header reservierte Höhe falsch berechnen. Mit stabil "lädt"
    // als Startzustand baut sich der Inhalt nur noch einmal auf.
    @State private var isLoading = true
    @State private var searchText = ""

    private var subtitle: String {
        switch category {
        case .person: "Verpasse keine neuen Termine deiner Lieblingskünstler:innen. Du kannst das jederzeit im Profil ändern."
        case .ensemble: "Verpasse keine neuen Termine deiner Lieblingsensembles. Du kannst das jederzeit im Profil ändern."
        case .venue: "Verpasse keine neuen Termine an deinen Lieblingsorten. Du kannst das jederzeit im Profil ändern."
        case .genre, .work: ""
        }
    }

    /// Ohne Suchtext auf eine Grid-taugliche Vorschlagszahl begrenzt --
    /// reine "Vorschläge"-Ansicht statt der vollen, potenziell langen
    /// Verzeichnisliste; mit Suchtext wird die komplette geladene Liste
    /// gefiltert und als kompakte Liste statt Grid gezeigt.
    private var visibleOptions: [InterestOption] {
        if searchText.isEmpty {
            return Array(options.prefix(category == .venue ? 12 : 18))
        }
        return options.filter { $0.label.localizedStandardContains(searchText) }
    }

    private var followedCount: Int {
        options.filter { isFollowing($0) }.count
    }

    private var gridColumns: [GridItem] {
        let count = category == .venue ? 2 : 3
        return Array(repeating: GridItem(.flexible(), spacing: 14), count: count)
    }

    var body: some View {
        ScrollView {
            VStack(spacing: 20) {
                VStack(spacing: 6) {
                    Text("Wem möchtest du folgen?")
                        .font(.title2.bold())
                    Text(subtitle)
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                }
                .frame(maxWidth: .infinity)

                OnboardingSearchField(prompt: "\(category.title) durchsuchen", text: $searchText)

                if isLoading {
                    ProgressView().padding(.top, 40)
                } else if visibleOptions.isEmpty {
                    ContentUnavailableView(
                        "Keine Treffer",
                        systemImage: category.systemImage,
                        description: Text("Für \"\(searchText)\" wurde nichts gefunden.")
                    )
                    .padding(.top, 20)
                } else if searchText.isEmpty {
                    LazyVGrid(columns: gridColumns, spacing: 20) {
                        ForEach(visibleOptions) { option in
                            FollowGridCell(
                                option: option,
                                kind: entityKind,
                                isFollowing: isFollowing(option),
                                action: { toggle(option) }
                            )
                        }
                    }
                } else {
                    VStack(spacing: 0) {
                        ForEach(visibleOptions) { option in
                            Button { toggle(option) } label: {
                                HStack(spacing: 12) {
                                    InterestOptionThumbnail(option: option, kind: entityKind)
                                    // Generated by Claude Code — explizit
                                    // linksbündig: ein zweizeiliger Name
                                    // sollte nicht mittig umbrechen.
                                    Text(option.label)
                                        .foregroundStyle(.primary)
                                        .font(.subheadline)
                                        .multilineTextAlignment(.leading)
                                        .lineLimit(2)
                                    Spacer()
                                    if isFollowing(option) {
                                        Image(systemName: "checkmark.circle.fill")
                                            .font(.system(size: 22))
                                            .foregroundStyle(KlangradarTheme.accent)
                                    }
                                }
                            }
                            .padding(.vertical, 10)
                            if option.id != visibleOptions.last?.id {
                                Divider()
                            }
                        }
                    }
                }
            }
            .padding(.horizontal, 20)
            .padding(.top, 12)
            .padding(.bottom, 12)
        }
        .scrollDismissesKeyboard(.interactively)
        .safeAreaInset(edge: .top, spacing: 0) { header }
        .onboardingBackground()
        .safeAreaInset(edge: .bottom) {
            VStack(spacing: 14) {
                Button(action: onFinished) { Text("Weiter").frame(maxWidth: .infinity) }
                    .authPrimaryButtonStyle().controlSize(.large)
            }
            .authBottomActionLayout()
        }
        .navigationTitle("Folgen")
        .onboardingChrome()
        .navigationBarTitleDisplayMode(.inline)
        .task(id: category) { searchText = ""; await load() }
    }

    private func isFollowing(_ option: InterestOption) -> Bool {
        guard let id = UUID(uuidString: option.id) else { return false }
        return follows.isFollowing(kind: entityKind, id: id)
    }

    private var entityKind: EntityKind {
        switch category {
        case .person: .person
        case .ensemble: .ensemble
        case .venue: .venue
        case .genre, .work: .person
        }
    }

    private func toggle(_ option: InterestOption) {
        guard let id = UUID(uuidString: option.id) else { return }
        // Generated by Claude Code — Haptik sitzt jetzt zentral in
        // FollowStore.toggle (Core/Repositories/UserRepository.swift), damit
        // Grid, Suchliste UND alle anderen Folgen-Buttons (Detailseiten,
        // Profil) konsistent dasselbe Feedback geben.
        Task { await follows.toggle(kind: entityKind, id: id) }
    }

    private func load() async {
        isLoading = true
        defer { isLoading = false }
        options = (try? await repository?.interestOptions(category)) ?? []
    }
}

/// Eine Grid-Kachel: Bild (Kreis für Personen/Ensembles, abgerundetes
/// Rechteck für Venues) mit Folgen-Zustand als Häkchen-Badge, Name darunter
/// -- zweizeilig mit kleinerer Schrift bei langen Namen, damit alle Kacheln
/// einer Reihe gleich hoch bleiben.
private struct FollowGridCell: View {
    let option: InterestOption
    let kind: EntityKind
    let isFollowing: Bool
    let action: () -> Void

    private var initials: String {
        let parts = option.label.split(separator: " ")
        let letters = [parts.first?.first, parts.count > 1 ? parts.last?.first : nil].compactMap { $0 }
        return String(letters).uppercased()
    }

    private var isVenue: Bool { kind == .venue }

    var body: some View {
        Button(action: action) {
            VStack(spacing: 8) {
                // Generated by Claude Code — kein Plus-Icon mehr für den
                // unausgewählten Zustand (Nutzervorgabe: "kein Plus unter
                // den Personen/Ensembles"); nur bei aktivem Follow taucht
                // ein Häkchen-Badge oben rechts auf (wie im Spotify-Vorbild),
                // statt permanent unten rechts zu sitzen.
                ZStack(alignment: .topTrailing) {
                    CroppedAsyncImage(url: option.photoURL, crop: nil) {
                        Color.secondary.opacity(0.12).overlay {
                            Text(initials)
                                .font(.callout.weight(.semibold))
                                .foregroundStyle(KlangradarTheme.accent)
                        }
                    }
                    .aspectRatio(isVenue ? 4 / 3 : 1, contentMode: .fill)
                    .frame(maxWidth: .infinity)
                    .clipShape(isVenue ? AnyShape(RoundedRectangle(cornerRadius: 14, style: .continuous)) : AnyShape(Circle()))
                    .overlay {
                        if isVenue {
                            RoundedRectangle(cornerRadius: 14, style: .continuous)
                                .stroke(isFollowing ? KlangradarTheme.accent : .clear, lineWidth: 2.5)
                        } else {
                            Circle().stroke(isFollowing ? KlangradarTheme.accent : .clear, lineWidth: 2.5)
                        }
                    }

                    if isFollowing {
                        Image(systemName: "checkmark.circle.fill")
                            .font(.system(size: 22))
                            .symbolRenderingMode(.palette)
                            .foregroundStyle(.white, KlangradarTheme.accent)
                            .background(Circle().fill(.white))
                            .padding(4)
                    }
                }

                Text(option.label)
                    .font(.caption.weight(.medium))
                    .foregroundStyle(.primary)
                    .multilineTextAlignment(.center)
                    .lineLimit(2)
                    .minimumScaleFactor(0.85)
                    .frame(height: 30, alignment: .top)
            }
        }
        .buttonStyle(.plain)
    }
}
