// Generated by Claude Code
import SwiftUI

/// Schritt "Personen/Ensembles/Venues folgen" (Punkt 6 der vom Nutzer
/// vorgegebenen Ziel-Struktur) -- zwischen Interessen (Schritt 5) und
/// Benachrichtigungen. Ursprünglich ein einzelner Schritt mit
/// Personen/Ensembles/Venues als Segmenten in einem Picker; auf Nutzer-
/// wunsch (2026-09-02) jetzt EIN eigener Onboarding-Schritt pro Kategorie
/// (siehe OnboardingView.Step .followPersons/.followEnsembles/.followVenues),
/// direkt nach den Genres in Schritt 4 statt danach — Werke tauchen im
/// Onboarding dadurch gar nicht mehr auf.
///
/// Datenquelle UND Folgen-Mechanismus sind bewusst dieselben, die bereits
/// an anderer Stelle existieren: `UserRepository.interestOptions(_:)` liefert
/// dieselbe alphabetische Personen-/Ensemble-/Venue-Liste, die auch
/// `InterestsView` (Profil → Interessen) verwendet, und "Folgen" ruft
/// dieselbe `setInterest`-RPC/-Tabelle auf, die auch `FollowStore` (Folgen-
/// Button auf Detailseiten) und `InterestsView` nutzen -- ein Follow hier,
/// auf einer Detailseite oder in den Interessen-Einstellungen spiegelt
/// daher konsequent denselben Zustand wider. Es gibt keinen separaten
/// Onboarding-eigenen Folgen-Mechanismus und keine neue Tabelle.
struct FollowCategoryStepView: View {
    @ObservedObject var auth: AuthStore
    let repository: UserRepository?
    let category: InterestCategory
    let header: OnboardingProgressHeader
    let onFinished: () -> Void

    @EnvironmentObject private var follows: FollowStore

    @State private var options: [InterestOption] = []
    // Generated by Claude Code — startet jetzt bereits geladen (statt erst
    // in .task auf true zu wechseln): Der Sprung von leer/ungeladen zu
    // "lädt" zu "Daten da" innerhalb des allerersten Layout-Durchgangs ließ
    // die von der NavigationStack per safeAreaInset(top) reservierte Höhe
    // für den Fortschritts-Header falsch berechnen — der Titel überlappte
    // sichtbar mit dem Header, bis man einmal manuell scrollte. Mit stabil
    // "lädt" als Startzustand baut sich der Inhalt nur noch einmal auf.
    @State private var isLoading = true
    @State private var searchText = ""

    private var subtitle: String {
        switch category {
        case .person: "Verpasse keine neuen Termine deiner Lieblingskünstler:innen. Du kannst das jederzeit im Profil ändern."
        case .ensemble: "Verpasse keine neuen Termine deiner Lieblingsensembles. Du kannst das jederzeit im Profil ändern."
        case .venue: "Verpasse keine neuen Termine an deinen Lieblingsorten. Du kannst das jederzeit im Profil ändern."
        case .genre, .work: ""
        }
    }

    /// Ohne Suchtext auf die ersten Einträge begrenzt -- reine
    /// "Vorschläge"-Ansicht statt der vollen, potenziell langen
    /// Verzeichnisliste; mit Suchtext wird die komplette geladene Liste
    /// gefiltert.
    private var visibleOptions: [InterestOption] {
        if searchText.isEmpty {
            return Array(options.prefix(12))
        }
        return options.filter { $0.label.localizedStandardContains(searchText) }
    }

    private var followedCount: Int {
        options.filter { isFollowing($0) }.count
    }

     var body: some View {
        // Generated by Claude Code — Titel/Untertitel waren als fixer
        // VStack VOR dem List platziert. Ein reiner VStack-Sibling vor
        // einem List respektiert das per NavigationStack gesetzte
        // safeAreaInset(top) (Fortschritts-Header) nicht zuverlässig und lag
        // sichtbar zum Teil dahinter/darunter. Jetzt Teil derselben Liste
        // wie der Rest des Inhalts (analog SignUpStepView: Titelblock als
        // erste Form-Section) — dasselbe Layout-System, garantiert korrekt
        // unterhalb des Headers.
        List {
            Section {
                VStack(spacing: 6) {
                    Text("Wem möchtest du folgen?")
                        .font(.title2.bold())
                    Text(subtitle)
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                }
                .frame(maxWidth: .infinity)
                .padding(.vertical, 8)
                .listRowBackground(Color.clear)
                OnboardingSearchField(prompt: "\(category.title) durchsuchen", text: $searchText)
                    .listRowInsets(EdgeInsets())
                    .listRowBackground(Color.clear)
                    .padding(.vertical, 4)
            }
            if isLoading {
                HStack { Spacer(); ProgressView(); Spacer() }
            } else if visibleOptions.isEmpty {
                ContentUnavailableView(
                    "Keine Treffer",
                    systemImage: category.systemImage,
                    description: Text("Für \"\(searchText)\" wurde nichts gefunden.")
                )
            } else {
                Section("\(category.title) · \(followedCount) gefolgt") {
                    ForEach(visibleOptions) { option in
                        Button { toggle(option) } label: {
                            HStack(spacing: 12) {
                                InterestOptionThumbnail(option: option, kind: entityKind)
                                Text(option.label).foregroundStyle(.primary)
                                Spacer()
                                Image(systemName: isFollowing(option) ? "checkmark.circle.fill" : "plus.circle")
                                    .font(.system(size: 28, weight: .regular))
                                    .frame(width: 44, height: 44)
                                    .foregroundStyle(isFollowing(option) ? KlangradarTheme.accent : .secondary)
                            }
                        }
                    }
                }
            }
        }
        .listStyle(.insetGrouped)
        .safeAreaInset(edge: .top, spacing: 0) { header }
        .onboardingBackground()
        .safeAreaInset(edge: .bottom) {
            VStack(spacing: 14) {
                Button(action: onFinished) { Text("Weiter").frame(maxWidth: .infinity) }
                    .authPrimaryButtonStyle().controlSize(.large)
            }
            .authBottomActionLayout()
        }
        .navigationTitle("Folgen")
        .onboardingChrome()
        .navigationBarTitleDisplayMode(.inline)
        .task(id: category) { searchText = ""; await load() }
    }

    private func isFollowing(_ option: InterestOption) -> Bool {
        guard let id = UUID(uuidString: option.id) else { return false }
        return follows.isFollowing(kind: entityKind, id: id)
    }

    private var entityKind: EntityKind {
        switch category {
        case .person: .person
        case .ensemble: .ensemble
        case .venue: .venue
        case .genre, .work: .person
        }
    }

    private func toggle(_ option: InterestOption) {
        guard let id = UUID(uuidString: option.id) else { return }
        Task { await follows.toggle(kind: entityKind, id: id) }
    }

    private func load() async {
        isLoading = true
        defer { isLoading = false }
        options = (try? await repository?.interestOptions(category)) ?? []
    }
}
