// Generated by Claude Code
import SwiftUI

/// Schritt "Personen/Ensembles/Venues folgen" (Punkt 6 der vom Nutzer
/// vorgegebenen Ziel-Struktur) -- zwischen Interessen (Schritt 5) und
/// Benachrichtigungen (Schritt 7). Getrennte Segmente für Personen,
/// Ensembles und Venues; eine eigene "Festivals/Veranstalter"-Kategorie
/// gibt es NICHT, weil `EntityKind`/`InterestCategory` dafür keinen eigenen
/// Wert kennen (nur person/ensemble/venue/work/genre) -- CLAUDE.md verbietet
/// erfundene Backend-Felder, Festival-Venues/-Veranstalter sind hier bereits
/// unter "Venues" bzw. "Ensembles" erfasst.
///
/// Datenquelle UND Folgen-Mechanismus sind bewusst dieselben, die bereits
/// an anderer Stelle existieren: `UserRepository.interestOptions(_:)` liefert
/// dieselbe alphabetische Personen-/Ensemble-/Venue-Liste, die auch
/// `InterestsView` (Profil → Interessen) verwendet, und "Folgen" ruft
/// dieselbe `setInterest`-RPC/-Tabelle auf, die auch `FollowStore` (Folgen-
/// Button auf Detailseiten) und `InterestsView` nutzen -- ein Follow hier,
/// auf einer Detailseite oder in den Interessen-Einstellungen spiegelt
/// daher konsequent denselben Zustand wider. Es gibt keinen separaten
/// Onboarding-eigenen Folgen-Mechanismus und keine neue Tabelle.
struct FollowProfilesStepView: View {
    @ObservedObject var auth: AuthStore
    let repository: UserRepository?
    let onFinished: () -> Void

    @EnvironmentObject private var follows: FollowStore

    private enum Segment: String, CaseIterable, Identifiable {
        case person, ensemble, venue
        var id: String { rawValue }
        var category: InterestCategory {
            switch self {
            case .person: .person
            case .ensemble: .ensemble
            case .venue: .venue
            }
        }
        var title: String { category.title }
        var systemImage: String { category.systemImage }
    }

    @State private var segment: Segment = .person
    @State private var options: [InterestOption] = []
    @State private var isLoading = false
    @State private var searchText = ""

    /// Ohne Suchtext auf die ersten Einträge begrenzt -- reine
    /// "Vorschläge"-Ansicht statt der vollen, potenziell langen
    /// Verzeichnisliste; mit Suchtext wird die komplette geladene Liste
    /// gefiltert.
    private var visibleOptions: [InterestOption] {
        if searchText.isEmpty {
            return Array(options.prefix(12))
        }
        return options.filter { $0.label.localizedStandardContains(searchText) }
    }

    private var followedCountInSegment: Int {
        options.filter { isFollowing($0) }.count
    }

    var body: some View {
        VStack(spacing: 0) {
            VStack(spacing: 6) {
                Text("Wem möchtest du folgen?")
                    .font(.title2.bold())
                Text("Verpasse keine neuen Termine deiner Lieblingskünstler:innen, Ensembles und Spielstätten. Du kannst das jederzeit im Profil ändern.")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
                    .multilineTextAlignment(.center)
            }
            .padding(.horizontal, 24)
            .padding(.top, 12)
            .padding(.bottom, 8)

            Picker("Kategorie", selection: $segment) {
                ForEach(Segment.allCases) { item in
                    Label(item.title, systemImage: item.systemImage).tag(item)
                }
            }
            .pickerStyle(.segmented)
            .padding(.horizontal, 24)
            .padding(.bottom, 8)

            List {
                if isLoading {
                    HStack { Spacer(); ProgressView(); Spacer() }
                } else if visibleOptions.isEmpty {
                    ContentUnavailableView(
                        "Keine Treffer",
                        systemImage: segment.systemImage,
                        description: Text("Für \"\(searchText)\" wurde nichts gefunden.")
                    )
                } else {
                    Section("\(segment.title) · \(followedCountInSegment) gefolgt") {
                        ForEach(visibleOptions) { option in
                            Button { toggle(option) } label: {
                                HStack {
                                    Text(option.label).foregroundStyle(.primary)
                                    Spacer()
                                    Image(systemName: isFollowing(option) ? "checkmark.circle.fill" : "plus.circle")
                                        .foregroundStyle(isFollowing(option) ? KlangradarTheme.accent : .secondary)
                                }
                            }
                        }
                    }
                }
            }
            .listStyle(.insetGrouped)
            .searchable(text: $searchText, prompt: "\(segment.title) durchsuchen")
        }
        .navigationTitle("Folgen")
        .onboardingChrome()
        .navigationBarTitleDisplayMode(.inline)
        .safeAreaInset(edge: .bottom) {
            VStack(spacing: 8) {
                Button(action: onFinished) { Text("Weiter").frame(maxWidth: .infinity) }
                    .authPrimaryButtonStyle().controlSize(.large)
                Button("Alle überspringen", action: onFinished)
                    .font(.footnote.weight(.medium))
            }
            .authBottomActionLayout()
        }
        .task(id: segment) { searchText = ""; await load() }
    }

    private func isFollowing(_ option: InterestOption) -> Bool {
        guard let id = UUID(uuidString: option.id) else { return false }
        return follows.isFollowing(kind: entityKind, id: id)
    }

    private var entityKind: EntityKind {
        switch segment {
        case .person: .person
        case .ensemble: .ensemble
        case .venue: .venue
        }
    }

    private func toggle(_ option: InterestOption) {
        guard let id = UUID(uuidString: option.id) else { return }
        Task { await follows.toggle(kind: entityKind, id: id) }
    }

    private func load() async {
        isLoading = true
        defer { isLoading = false }
        options = (try? await repository?.interestOptions(segment.category)) ?? []
    }
}
