import SwiftUI

/// Bettet die bestehende `InterestsView` (Features/Profile/InterestsView.swift)
/// als Onboarding-Schritt ein — deren `.navigationTitle` bleibt hier ohne
/// umgebenden NavigationStack einfach wirkungslos. Jede Auswahl wird von
/// InterestsView selbst sofort gespeichert, "Weiter" schließt nur den Schritt
/// ab, ohne selbst noch etwas zu sichern.
struct InterestsStepView: View {
    @ObservedObject var auth: AuthStore
    let repository: UserRepository?
    let onFinished: () -> Void

    var body: some View {
        // Generated by Claude Code — .safeAreaInset muss direkt an der
        // scrollbaren InterestsView (List) hängen. An einem umschließenden
        // VStack gesetzt, reserviert das darunterliegende List keinen Platz
        // dafür und die letzten Zeilen lagen unter der Weiter-Leiste.
        InterestsView(auth: auth, repository: repository, fixedCategory: .genre)
            .navigationTitle("Was interessiert dich?")
            .onboardingChrome()
            .navigationBarTitleDisplayMode(.inline)
            .safeAreaInset(edge: .bottom) {
                VStack(spacing: 14) {
                    Button(action: onFinished) { Text("Weiter").frame(maxWidth: .infinity) }
                        .authPrimaryButtonStyle().controlSize(.large)
                }
                .authBottomActionLayout()
            }
    }
}
