import SwiftUI
import UserNotifications

/// Schritt "Benachrichtigungen": erst ein Erklär-Screen, dann erst der
/// iOS-Systemdialog (bessere Annahmequote als ein blinder Dialog beim
/// App-Start) — danach die bestehenden granularen Toggles
/// (Features/Profile/NotificationSettingsView.swift), unabhängig vom
/// Systemdialog-Ergebnis erreichbar: die Datenbank-Präferenzen bestimmen nur,
/// WELCHE Kategorien gesendet werden, falls die OS-Berechtigung überhaupt
/// erteilt ist.
struct NotificationsStepView: View {
    @ObservedObject var auth: AuthStore
    let repository: UserRepository?
    let onFinished: () -> Void

    @State private var isWorking = false

    var body: some View {
        // Generated by Claude Code — Titel war als fixer VStack-Sibling vor
        // der Form platziert und respektierte das per NavigationStack
        // gesetzte safeAreaInset(top) nicht zuverlässig (lag teils hinter
        // dem Header, siehe FollowCategoryStepView). Jetzt als erste
        // Form-Section über NotificationSettingsView.introTitle.
        NotificationSettingsView(
            auth: auth,
            repository: repository,
            introTitle: "Verpasse keine interessanten Konzerte",
            introSubtitle: "Wähle zuerst aus, was dich interessiert. Den iOS-Systemdialog öffnen wir erst danach."
        )
        .safeAreaInset(edge: .bottom) {
            VStack(spacing: 14) {
                Button { Task { await requestPermission() } } label: {
                    Text("Benachrichtigungen aktivieren").frame(maxWidth: .infinity)
                }
                .authPrimaryButtonStyle().controlSize(.large).disabled(isWorking)
                Button("Nicht jetzt", action: onFinished).font(.subheadline.weight(.medium)).disabled(isWorking)
            }
            .authBottomActionLayout()
        }
        .navigationTitle("Benachrichtigungen")
        .onboardingChrome()
        .navigationBarTitleDisplayMode(.inline)
        .overlay { if isWorking { ProgressView().controlSize(.large) } }
    }

    private func requestPermission() async {
        isWorking = true
        defer { isWorking = false }
        _ = try? await UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .badge, .sound])
        onFinished()
    }
}
