import SwiftUI
import UIKit

struct KlangradarAppIcon: View {
    var size: CGFloat = 76

    private var image: UIImage? {
        guard
            let icons = Bundle.main.infoDictionary?["CFBundleIcons"] as? [String: Any],
            let primary = icons["CFBundlePrimaryIcon"] as? [String: Any],
            let files = primary["CFBundleIconFiles"] as? [String],
            let name = files.last
        else { return UIImage(named: "AppIcon") }
        return UIImage(named: name)
    }

    var body: some View {
        Group {
            if let image {
                Image(uiImage: image).resizable().scaledToFit()
            } else {
                Image("AppIcon").resizable().scaledToFit()
            }
        }
        .frame(width: size, height: size)
        .clipShape(RoundedRectangle(cornerRadius: size * 0.225, style: .continuous))
        .shadow(color: .black.opacity(0.16), radius: 14, y: 7)
        .accessibilityHidden(true)
    }
}

/// Passwortfeld mit Klar-/Verbergen-Auge in der Zeile selbst statt einem
/// separaten "Passwörter anzeigen"-Schalter darunter — ein Auge pro Feld ist
/// der iOS-übliche Ort für diese Aktion, ein zusätzlicher Toggle wirkt wie
/// eine dauerhafte Einstellung statt einer kurzen Sichtbarkeits-Aktion.
struct RevealablePasswordField: View {
    let title: String
    @Binding var text: String
    @Binding var isRevealed: Bool
    var textContentType: UITextContentType? = .password

    var body: some View {
        HStack(spacing: 8) {
            Group {
                if isRevealed {
                    TextField(title, text: $text)
                } else {
                    SecureField(title, text: $text)
                }
            }
            .textContentType(textContentType)
            Button {
                isRevealed.toggle()
            } label: {
                Image(systemName: isRevealed ? "eye.slash" : "eye")
                    .foregroundStyle(.secondary)
            }
            .buttonStyle(.plain)
            .accessibilityLabel(isRevealed ? "Passwort verbergen" : "Passwort anzeigen")
        }
    }
}

struct GoogleSignInLabel: View {
    var body: some View {
        Label {
            Text("Mit Google anmelden")
        } icon: {
            Image("GoogleG")
                .resizable()
                .scaledToFit()
                .frame(width: 18, height: 18)
        }
    }
}

// Generated by Claude Code — ersetzt den bisherigen durchgehenden
// ProgressView-Balken (überlappte mit dem iOS-26-Glass-Zurück-Button, da
// beide unabhängig voneinander im Nav-Bar-Bereich platziert waren) durch
// einen einzigen Header, der den Zurück-Button UND die Fortschrittsanzeige
// als abgetrennte Segmente (Zielvorgabe: wie in den Referenz-Mockups) in
// einer Zeile führt. Steps blenden dafür die System-Nav-Bar komplett aus
// (siehe .onboardingChrome()) statt einen zweiten, konkurrierenden
// Zurück-Button vom System zu bekommen.
struct OnboardingProgressHeader: View {
    let current: Int
    let total: Int
    var onBack: (() -> Void)? = nil

    var body: some View {
        HStack(spacing: 14) {
            if let onBack {
                Button(action: onBack) {
                    Image(systemName: "chevron.left")
                        .font(.footnote.weight(.semibold))
                        .frame(width: 32, height: 32)
                }
                .buttonStyle(.plain)
                .background(.thinMaterial, in: .circle)
                .accessibilityLabel("Zurück")
            }
            HStack(spacing: 5) {
                ForEach(0..<total, id: \.self) { index in
                    Capsule()
                        .fill(index < current ? KlangradarTheme.accent : Color(.systemGray5))
                        .frame(height: 3)
                }
            }
        }
        .padding(.horizontal, 20)
        .padding(.top, 8)
        .padding(.bottom, 12)
        // Undurchsichtiger Hintergrund ist Pflicht, kein Kosmetik-Detail:
        // Form-Sektionsköpfe (z.B. "Zugangsdaten") pinnen beim Scrollen an
        // die Oberkante und blieben bei .clear sichtbar hinter diesem
        // Header stehen, sobald die System-Nav-Bar per .onboardingChrome()
        // ausgeblendet ist.
        .background(.bar)
        .accessibilityElement(children: .combine)
        .accessibilityLabel("Schritt \(current) von \(total)")
    }
}

/// Blendet die System-Navigationsleiste (Titel + Zurück-Button) für einen
/// Onboarding-Schritt aus — der Zurück-Button lebt stattdessen im
/// `OnboardingProgressHeader`, damit beide nicht mehr um denselben Bereich
/// konkurrieren.
extension View {
    func onboardingChrome() -> some View {
        self
            .navigationBarTitleDisplayMode(.inline)
            .toolbar(.hidden, for: .navigationBar)
    }
}

/// Checkbox statt Switch für einmalige Zustimmungen (AGB, Datenschutz) —
/// ein Toggle-Switch signalisiert eine jederzeit umkehrbare Einstellung,
/// eine Checkbox liest sich als das erwartete "ich habe das gelesen und
/// bestätige es"-Häkchen. Für widerrufbare Präferenzen (z.B. Newsletter,
/// Benachrichtigungs-Kategorien) bleibt der reguläre Switch-Style richtig.
struct CheckboxToggleStyle: ToggleStyle {
    func makeBody(configuration: Configuration) -> some View {
        Button {
            configuration.isOn.toggle()
        } label: {
            HStack(alignment: .top, spacing: 12) {
                Image(systemName: configuration.isOn ? "checkmark.square.fill" : "square")
                    .font(.title3)
                    .foregroundStyle(configuration.isOn ? KlangradarTheme.accent : Color(.tertiaryLabel))
                configuration.label
                    .foregroundStyle(.primary)
            }
        }
        .buttonStyle(.plain)
    }
}

extension ToggleStyle where Self == CheckboxToggleStyle {
    static var checkbox: CheckboxToggleStyle { CheckboxToggleStyle() }
}

extension View {
    @ViewBuilder
    func authPrimaryButtonStyle() -> some View {
        if #available(iOS 26.0, *) {
            self.buttonStyle(.glassProminent)
        } else {
            self.buttonStyle(.borderedProminent)
        }
    }

    @ViewBuilder
    func authSecondaryButtonStyle() -> some View {
        if #available(iOS 26.0, *) {
            self.buttonStyle(.glass)
        } else {
            self.buttonStyle(.bordered)
        }
    }

    @ViewBuilder
    func authBottomActionLayout() -> some View {
        if #available(iOS 26.0, *) {
            self.padding(.horizontal, 20).padding(.vertical, 10)
        } else {
            self.padding().background(.bar)
        }
    }
}

/// Gemeinsames Gerüst für kompakte Onboarding-Schritte (Titel + Inhalt +
/// primärer "Weiter"-Button, optional ein sekundärer Text-Button zum
/// Überspringen). Schritte mit einer eingebetteten Liste/Form (Interessen,
/// Benachrichtigungen) nutzen stattdessen ihr eigenes Layout, siehe
/// InterestsStepView/NotificationsStepView.
struct OnboardingStepScaffold<Content: View>: View {
    let title: String
    var subtitle: String? = nil
    var systemImage: String? = nil
    @ViewBuilder var content: () -> Content
    let primaryTitle: String
    var isPrimaryEnabled: Bool = true
    let onPrimary: () -> Void
    var secondaryTitle: String? = nil
    var onSecondary: (() -> Void)? = nil
    var errorMessage: String? = nil
    var isWorking: Bool = false

    var body: some View {
        VStack(spacing: 24) {
            Spacer(minLength: 8)
            if let systemImage {
                Image(systemName: systemImage)
                    .font(.system(size: 52))
                    .foregroundStyle(KlangradarTheme.accent)
            }
            VStack(spacing: 8) {
                Text(title)
                    .font(.largeTitle.bold())
                    .multilineTextAlignment(.center)
                if let subtitle {
                    Text(subtitle)
                        .font(.title3)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                }
            }

            content()

            if let errorMessage {
                Text(errorMessage)
                    .font(.footnote)
                    .foregroundStyle(.red)
                    .multilineTextAlignment(.center)
            }

            Spacer(minLength: 8)

            VStack(spacing: 10) {
                Button(primaryTitle) { onPrimary() }
                    .authPrimaryButtonStyle()
                    .controlSize(.large)
                    .frame(maxWidth: .infinity)
                    .disabled(!isPrimaryEnabled || isWorking)

                if let secondaryTitle, let onSecondary {
                    Button(secondaryTitle) { onSecondary() }
                        .font(.footnote)
                        .disabled(isWorking)
                }
            }
        }
        .padding(28)
        .overlay {
            if isWorking {
                ProgressView().controlSize(.large)
            }
        }
        .scrollDismissesKeyboard(.interactively)
    }
}
