import SwiftUI

/// Koordiniert den gesamten Onboarding-Ablauf: Einstieg (Anmelden/Account
/// erstellen/Gast) → Account erstellen → E-Mail bestätigen → Persönliche
/// Daten → Interessen (nur Genres) → Stadt → Personen folgen → Ensembles
/// folgen → Venues folgen → Benachrichtigungen → Zusammenfassung. Personen/
/// Ensembles/Venues waren früher ein einzelner Schritt mit Segmenten, sind
/// auf Nutzerwunsch (2026-09-02) jetzt je ein eigener Schritt; Werke tauchen
/// im Onboarding gar nicht mehr auf (siehe InterestsStepView).
/// "Account erstellen" ist verpflichtend, sobald gewählt — nur der
/// Einstiegs-Schritt selbst lässt sich mit "Ohne Account fortfahren"
/// überspringen (anonyme Bootstrap-Session bleibt aktiv). `onFinished` wird
/// von RootTabView übergeben und kümmert sich dort um das lokale
/// "didCompleteOnboarding"-Flag und das Schließen des FullScreenCovers.
struct OnboardingView: View {
    /// Erlaubt Aufrufern (z.B. "Anmelden" im Profil), direkt beim Login-
    /// Formular bzw. beim Sign-up-Schritt einzusteigen statt beim
    /// Willkommens-Bildschirm — der Rest des Flows (inkl. aller Folgeschritte
    /// bei Kontoerstellung) bleibt derselbe wie beim regulären Einstieg.
    enum InitialAction: Equatable {
        case login
        case signUp
    }

    @ObservedObject var auth: AuthStore
    let repository: UserRepository?
    let onFinished: () -> Void

    private enum Step: Hashable {
        case signUp
        case verifyEmail(email: String, marketingEmailOptIn: Bool)
        case personalData
        case interests
        case location
        case followPersons
        case followEnsembles
        case followVenues
        case notifications
        case summary
    }

    @State private var path: [Step]
    @State private var showsLogin: Bool

    // Generated by Claude Code — vorher wurden showsLogin/path erst in
    // .task (also nach dem ersten Render) auf den gewünschten Einstieg
    // gesetzt. Dadurch war für einen Frame kurz der Willkommens-Bildschirm
    // sichtbar, bevor sich das Login-Sheet darüber schob — sah aus wie ein
    // "falsches Popup über dem richtigen Screen". Jetzt schon beim
    // allerersten Render korrekt gesetzt, kein sichtbarer Zwischenschritt
    // mehr.
    init(
        auth: AuthStore,
        repository: UserRepository?,
        initialAction: InitialAction? = nil,
        onFinished: @escaping () -> Void
    ) {
        self.auth = auth
        self.repository = repository
        self.onFinished = onFinished
        _showsLogin = State(initialValue: initialAction == .login)
        _path = State(initialValue: initialAction == .signUp ? [.signUp] : [])
    }

    var body: some View {
        NavigationStack(path: $path) {
            WelcomeStepView(
                auth: auth,
                onCreateAccount: { path.append(.signUp) },
                onLogIn: { showsLogin = true },
                onContinueAsGuest: { onFinished() },
                onAuthenticated: onFinished
            )
            .navigationDestination(for: Step.self) { step in
                // Generated by Claude Code — der Fortschritts-Header saß
                // vorher zentral als .safeAreaInset(top) auf dem
                // NavigationStack. List/Form respektieren ein
                // safeAreaInset, das nicht DIREKT auf ihnen selbst sitzt,
                // nicht zuverlässig (dasselbe Muster, das schon beim
                // unteren Rand Probleme machte, siehe FollowCategoryStepView/
                // NotificationsStepView) — Titel/erste Zeile lagen sichtbar
                // unter einem weißen "Banner" hinter den Segmenten. Jetzt
                // bekommt jeder Schritt seinen fertigen Header übergeben und
                // hängt ihn selbst direkt an sein eigenes List/Form.
                let header = progressHeader(for: step)
                switch step {
                case .signUp:
                    SignUpStepView(auth: auth, header: header) { email, marketingEmailOptIn in
                        path.append(.verifyEmail(email: email, marketingEmailOptIn: marketingEmailOptIn))
                    }
                case let .verifyEmail(email, marketingEmailOptIn):
                    VerifyEmailStepView(
                        auth: auth,
                        repository: repository,
                        email: email,
                        marketingEmailOptIn: marketingEmailOptIn,
                        header: header
                    ) {
                        path.append(.personalData)
                    }
                case .personalData:
                    PersonalDataStepView(auth: auth, repository: repository, header: header) {
                        path.append(.interests)
                    }
                case .interests:
                    InterestsStepView(auth: auth, repository: repository, header: header) {
                        path.append(.location)
                    }
                case .location:
                    CityPickerStepView(auth: auth, repository: repository, header: header) {
                        path.append(.followPersons)
                    }
                case .followPersons:
                    FollowCategoryStepView(auth: auth, repository: repository, category: .person, header: header) {
                        path.append(.followEnsembles)
                    }
                case .followEnsembles:
                    FollowCategoryStepView(auth: auth, repository: repository, category: .ensemble, header: header) {
                        path.append(.followVenues)
                    }
                case .followVenues:
                    FollowCategoryStepView(auth: auth, repository: repository, category: .venue, header: header) {
                        path.append(.notifications)
                    }
                case .notifications:
                    NotificationsStepView(auth: auth, repository: repository, header: header) {
                        path.append(.summary)
                    }
                case .summary:
                    OnboardingSummaryView(
                        auth: auth,
                        repository: repository,
                        header: header,
                        onEditCity: { editStep(matching: { if case .location = $0 { true } else { false } }) },
                        onEditInterests: { editStep(matching: { if case .interests = $0 { true } else { false } }) },
                        onEditFollows: { editStep(matching: { if case .followPersons = $0 { true } else { false } }) },
                        onEditNotifications: { editStep(matching: { if case .notifications = $0 { true } else { false } }) }
                    ) {
                        Task { await finish() }
                    }
                }
            }
        }
        .sheet(isPresented: $showsLogin) {
            PasswordLoginView(
                auth: auth,
                repository: repository,
                onSignedIn: onFinished,
                onRequestSignUp: {
                    showsLogin = false
                    path = [.signUp]
                }
            )
        }
        .interactiveDismissDisabled()
    }

    private func stepNumber(_ step: Step) -> Int {
        switch step {
        case .signUp: 1
        case .verifyEmail: 2
        case .personalData: 3
        case .interests: 4
        case .location: 5
        case .followPersons: 6
        case .followEnsembles: 7
        case .followVenues: 8
        case .notifications, .summary: 9
        }
    }

    private func progressHeader(for step: Step) -> OnboardingProgressHeader {
        OnboardingProgressHeader(
            current: stepNumber(step),
            total: 9,
            onBack: { if !path.isEmpty { path.removeLast() } },
            onSkip: canSkip(step) ? { skipCurrentStep() } : nil
        )
    }

    private func canSkip(_ step: Step) -> Bool {
        switch step {
        case .interests, .location, .followPersons, .followEnsembles, .followVenues, .notifications: true
        default: false
        }
    }

    private func skipCurrentStep() {
        switch path.last {
        case .interests: path.append(.location)
        case .location: path.append(.followPersons)
        case .followPersons: path.append(.followEnsembles)
        case .followEnsembles: path.append(.followVenues)
        case .followVenues: path.append(.notifications)
        case .notifications: path.append(.summary)
        default: break
        }
    }

    /// Springt aus der Zusammenfassung zurück zu einem bereits durchlaufenen
    /// Schritt (z.B. "Bearbeiten" bei Stadt/Folgen/Benachrichtigungen) --
    /// entfernt alles NACH diesem Schritt aus dem Pfad, statt ihn erneut
    /// anzuhängen, damit "Weiter" von dort aus nicht zu doppelten Einträgen
    /// im Stack führt.
    private func editStep(matching predicate: (Step) -> Bool) {
        guard let index = path.firstIndex(where: predicate), index + 1 < path.count else { return }
        path.removeSubrange((index + 1)...)
    }

    private func finish() async {
        if case .authenticated = auth.state, let userID = auth.userID, let token = auth.accessToken {
            try? await repository?.markOnboardingCompleted(userID: userID, token: token)
        }
        Haptics.strong() // Generated by Claude Code — Onboarding abgeschlossen, deutlicher Erfolgs-Impuls
        onFinished()
    }
}
