import SwiftUI

/// Letzter Schritt: Zusammenfassung der gewählten Stadt, Interessen,
/// gefolgten Profile und Benachrichtigungseinstellungen, jede Zeile mit
/// "Bearbeiten"-Sprung zurück zum jeweiligen Schritt, dann Übergang in den
/// personalisierten Home-Feed.
struct OnboardingSummaryView: View {
    @ObservedObject var auth: AuthStore
    let repository: UserRepository?
    let header: OnboardingProgressHeader
    var onEditCity: () -> Void = {}
    var onEditInterests: () -> Void = {}
    var onEditFollows: () -> Void = {}
    var onEditNotifications: () -> Void = {}
    let onFinished: () -> Void

    @State private var cityName: String?
    @State private var interestCounts: [InterestCategory: Int] = [:]
    // Generated by Claude Code — Nutzervorgabe (2026-09-03): statt einer
    // Gesamtsumme mit angehängter, immer gleicher Aufzählung aller drei
    // Kategorien ("8 Personen, Ensembles & Orte" — wirkte, als gäbe es 8
    // von JEDER Kategorie) jetzt eine echte Aufschlüsselung pro Kategorie.
    @State private var followedPersonCount = 0
    @State private var followedEnsembleCount = 0
    @State private var followedVenueCount = 0
    @State private var activeNotificationCount = 0
    @State private var isLoading = true

    private var totalInterestCount: Int { interestCounts.values.reduce(0, +) }

    private var followedTotalCount: Int { followedPersonCount + followedEnsembleCount + followedVenueCount }

    private var followedSummary: String {
        guard followedTotalCount > 0 else { return "Noch keine" }
        var parts: [String] = []
        if followedPersonCount > 0 { parts.append("\(followedPersonCount) Personen") }
        if followedEnsembleCount > 0 { parts.append("\(followedEnsembleCount) Ensembles") }
        if followedVenueCount > 0 { parts.append("\(followedVenueCount) Orte") }
        return parts.joined(separator: ", ")
    }

    var body: some View {
        // Generated by Claude Code — vorher ein `List` mit nur 4 Zeilen:
        // dessen graue Gruppen-Hintergrundfarbe füllte sichtbar die gesamte
        // Resthöhe bis zum Button und wirkte wie ungenutzter Leerraum.
        // Jetzt eigene Karten in einem ScrollView, das sich am Inhalt
        // orientiert statt am Bildschirm. Header hängt direkt am ScrollView
        // (safeAreaInset top) statt am NavigationStack, damit das
        // Checkmark-Icon zuverlässig unterhalb des Fortschritts-Headers
        // bleibt.
        ScrollView {
            VStack(spacing: 28) {
                VStack(spacing: 8) {
                    Image(systemName: "checkmark.circle.fill")
                        .font(.system(size: 52))
                        .foregroundStyle(KlangradarTheme.accent)
                    Text("Dein Profil ist eingerichtet")
                        .font(.largeTitle.bold())
                        .multilineTextAlignment(.center)
                    Text("Du kannst jede Einstellung unten jederzeit im Profil ändern.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                }

                if isLoading {
                    ProgressView().padding(.top, 40)
                } else {
                    VStack(spacing: 12) {
                        summaryRow(
                            systemImage: "map",
                            title: "Stadt",
                            value: cityName ?? "Keine ausgewählt",
                            action: onEditCity
                        )
                        summaryRow(
                            systemImage: "music.quarternote.3",
                            title: "Interessen",
                            value: totalInterestCount > 0 ? "\(totalInterestCount) ausgewählt" : "Noch keine",
                            action: onEditInterests
                        )
                        summaryRow(
                            systemImage: "person.2",
                            title: "Gefolgt",
                            value: followedSummary,
                            action: onEditFollows
                        )
                        summaryRow(
                            systemImage: "bell",
                            title: "Benachrichtigungen",
                            value: activeNotificationCount > 0 ? "\(activeNotificationCount) Kategorien aktiv" : "Alle deaktiviert",
                            action: onEditNotifications
                        )
                    }
                }
            }
            .padding(.horizontal, 20)
            .padding(.top, 20)
            .padding(.bottom, 12)
        }
        .safeAreaInset(edge: .top, spacing: 0) { header }
        .onboardingBackground()
        .safeAreaInset(edge: .bottom) {
            Button(action: onFinished) {
                Text("Konzerte für dich entdecken").frame(maxWidth: .infinity)
            }
            .authPrimaryButtonStyle()
            .controlSize(.large)
            .authBottomActionLayout()
        }
        .task { await loadSummary() }
        .onboardingChrome()
    }

    @ViewBuilder
    private func summaryRow(systemImage: String, title: String, value: String, action: (() -> Void)?) -> some View {
        HStack(spacing: 12) {
            Image(systemName: systemImage)
                .font(.title3)
                .foregroundStyle(KlangradarTheme.accent)
                .frame(width: 26)
            VStack(alignment: .leading, spacing: 2) {
                Text(title).font(.subheadline.weight(.semibold))
                Text(value).font(.footnote).foregroundStyle(.secondary)
            }
            Spacer(minLength: 8)
            if let action {
                Button("Bearbeiten", action: action)
                    .font(.footnote.weight(.semibold))
                    .buttonStyle(.plain)
                    .foregroundStyle(KlangradarTheme.accent)
            }
        }
        .padding(16)
        .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 16, style: .continuous))
    }

    private func loadSummary() async {
        isLoading = true
        defer { isLoading = false }
        guard let repository, let userID = auth.userID, let token = auth.accessToken else { return }

        async let regionsTask = repository.allCityRegions()
        async let preferredIDTask = repository.preferredRegionID(userID: userID, token: token)
        async let preferencesTask = repository.preferences(userID: userID, token: token)

        for category in InterestCategory.allCases {
            let count = ((try? await repository.selectedInterests(category, userID: userID, token: token)) ?? []).count
            interestCounts[category] = count
        }
        followedPersonCount = interestCounts[.person] ?? 0
        followedEnsembleCount = interestCounts[.ensemble] ?? 0
        followedVenueCount = interestCounts[.venue] ?? 0
        interestCounts[.person] = nil
        interestCounts[.ensemble] = nil
        interestCounts[.venue] = nil

        if let preferredID = try? await preferredIDTask, let regions = try? await regionsTask {
            cityName = regions.first(where: { $0.id == preferredID })?.nameDE
        }
        if let preferences = try? await preferencesTask {
            activeNotificationCount = [
                preferences.newMatchingEvents, preferences.priceChanges, preferences.almostSoldOut,
                preferences.reminderDayBefore, preferences.followedEnsembleNewEvent
            ].filter { $0 }.count
        }
    }
}
