import SwiftUI

/// Zentraler Login für Onboarding und Profil. E-Mail-Codes werden hier
/// bewusst nicht angeboten: Codes bestätigen nur neue E-Mail-Adressen,
/// Recovery erfolgt ausschließlich über einen sicheren Link.
struct PasswordLoginView: View {
    @ObservedObject var auth: AuthStore
    var repository: UserRepository?
    var onSignedIn: () -> Void = {}
    /// Wird aufgerufen, wenn "Neuen Account erstellen" gewählt wird. Der
    /// Aufrufer entscheidet, wohin das führt — im vollständigen Onboarding-
    /// Flow (OnboardingView) auf den echten Sign-up-Schritt inkl. aller
    /// Folgeschritte, statt hier ein eigenes, unvollständiges Mini-Sign-up
    /// zu präsentieren (das führte bisher nur bis zur E-Mail-Bestätigung und
    /// übersprang Persönliche Daten/Interessen/Stadt/Folgen/Benachrichtigungen).
    var onRequestSignUp: () -> Void
    @Environment(\.dismiss) private var dismiss

    @State private var email = ""
    @State private var password = ""
    @State private var showsPassword = false
    @State private var isWorking = false
    @State private var errorMessage: String?
    @State private var showsForgotPassword = false
    @State private var showsBiometricOffer = false

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    HStack {
                        Spacer()
                        VStack(spacing: 12) {
                            KlangradarAppIcon(size: 72)
                            Text("Willkommen zurück")
                                .font(.title2.bold())
                            Text("Melde dich an, um deine Favoriten und Empfehlungen auf allen Geräten zu sehen.")
                                .font(.subheadline)
                                .foregroundStyle(.secondary)
                                .multilineTextAlignment(.center)
                        }
                        Spacer()
                    }
                    .listRowBackground(Color.clear)
                }

                Section {
                    TextField("E-Mail-Adresse", text: $email)
                        .textContentType(.emailAddress)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                        .keyboardType(.emailAddress)
                    RevealablePasswordField(title: "Passwort", text: $password, isRevealed: $showsPassword, textContentType: .password)
                        .submitLabel(.go)
                        .onSubmit { if canLogIn { Task { await login() } } }
                }

                Section {
                    Button("Passwort vergessen?") { showsForgotPassword = true }
                        .disabled(isWorking)
                } footer: {
                    Text("Du erhältst einen sicheren Link, mit dem du ein neues Passwort festlegen kannst.")
                }

                if auth.isAppleSignInAvailable || auth.isGoogleSignInAvailable {
                    Section("Andere Anmeldeoptionen") {
                    if auth.isAppleSignInAvailable {
                        Button {
                            Task { await oauth(provider: "Apple") { try await auth.signInWithApple() } }
                        } label: {
                            Label("Mit Apple anmelden", systemImage: "apple.logo")
                        }
                        .disabled(isWorking)
                    }

                    if auth.isGoogleSignInAvailable {
                        Button {
                            Task { await oauth(provider: "Google") { try await auth.signInWithGoogle() } }
                        } label: {
                            GoogleSignInLabel()
                        }
                        .disabled(isWorking)
                    }
                    }
                }

                if let errorMessage {
                    Section { Label(errorMessage, systemImage: "exclamationmark.triangle.fill").foregroundStyle(.red) }
                }
            }
            .navigationTitle("Anmelden")
            .navigationBarTitleDisplayMode(.inline)
            .safeAreaInset(edge: .bottom) {
                // Generated by Claude Code — "Neuen Account erstellen" saß
                // vorher als letzte Form-Section im Scroll-Inhalt und lag
                // dadurch praktisch immer unter dieser fixierten Leiste
                // (nicht antippbar, nur als Geisterschrift sichtbar). Jetzt
                // fester Bestandteil der Leiste, garantiert erreichbar.
                VStack(spacing: 10) {
                    Button { Task { await login() } } label: {
                        Text("Anmelden").frame(maxWidth: .infinity)
                    }
                        .authPrimaryButtonStyle()
                        .controlSize(.large)
                        .disabled(!canLogIn)
                    Button("Neuen Account erstellen", action: onRequestSignUp)
                        .font(.footnote.weight(.medium))
                        .disabled(isWorking)
                }
                .authBottomActionLayout()
            }
            .overlay { if isWorking { ProgressView().controlSize(.large) } }
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Abbrechen") { dismiss() }
                }
            }
            .interactiveDismissDisabled(isWorking)
            .sheet(isPresented: $showsForgotPassword) {
                ForgotPasswordView(auth: auth)
            }
            .onChange(of: auth.isCompletingPasswordRecovery) { _, isRecovering in
                if isRecovering { dismiss() }
            }
            .alert(biometricOfferTitle, isPresented: $showsBiometricOffer) {
                Button("Aktivieren") {
                    UserDefaults.standard.set(true, forKey: BiometricAuth.enabledStorageKey)
                    finishSignIn()
                }
                Button("Später", role: .cancel, action: finishSignIn)
            } message: {
                Text("Schütze deine gespeicherte Anmeldung auf diesem Gerät. Dein Passwort wird weiterhin sicher in der Sitzung verwaltet.")
            }
        }
    }

    private var canLogIn: Bool {
        !isWorking
            && email.trimmingCharacters(in: .whitespacesAndNewlines).contains("@")
            && !password.isEmpty
    }

    private func login() async {
        isWorking = true
        errorMessage = nil
        defer { isWorking = false }
        do {
            try await auth.signInWithPassword(
                email: email.trimmingCharacters(in: .whitespacesAndNewlines).lowercased(),
                password: password
            )
            completeSignIn()
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    private func oauth(provider: String, action: () async throws -> Void) async {
        isWorking = true
        errorMessage = nil
        defer { isWorking = false }
        do {
            try await action()
            completeSignIn()
        } catch {
            errorMessage = "\(provider): \(error.localizedDescription)"
        }
    }

    private var biometricOfferTitle: String {
        BiometricAuth.availableBiometryKind == .touchID ? "Touch ID aktivieren?" : "Face ID aktivieren?"
    }

    private func completeSignIn() {
        if BiometricAuth.availableBiometryKind != .none, !BiometricAuth.isEnabled {
            showsBiometricOffer = true
        } else {
            finishSignIn()
        }
    }

    private func finishSignIn() {
        Haptics.strong() // Generated by Claude Code — Anmeldung abgeschlossen
        onSignedIn()
        dismiss()
    }
}
