import SwiftUI

/// Schritt 2 "Account erstellen": E-Mail + Passwort, Anforderungen live
/// angezeigt (muss zur Supabase-Passwort-Policy passen, siehe
/// backend/supabase/config.toml minimum_password_length/
/// password_requirements), AGB/Datenschutz-Zustimmung. Verschickt bei Erfolg
/// automatisch die Bestätigungs-Mail (Supabase, `enable_confirmations`) —
/// der eigentliche Haken wird erst nach `acceptTerms` im nächsten Schritt
/// gesetzt, sobald eine echte (nicht mehr anonyme) Session existiert.
struct SignUpStepView: View {
    @ObservedObject var auth: AuthStore
    let header: OnboardingProgressHeader
    let onSignedUp: (String, Bool) -> Void

    @State private var email = ""
    @State private var password = ""
    @State private var passwordConfirmation = ""
    @State private var acceptedTerms = false
    @State private var acceptedPrivacy = false
    @State private var marketingEmailOptIn = false
    @State private var showsPassword = false
    @State private var isWorking = false
    @State private var errorMessage: String?
    @State private var showsImpressum = false
    @State private var showsAGB = false
    @State private var showsDatenschutz = false

    private var requirements: [(title: String, isMet: Bool)] { AuthPasswordPolicy.requirements(for: password) }

    private var isValid: Bool {
        email.contains("@")
            && AuthPasswordPolicy.isValid(password)
            && password == passwordConfirmation
            && acceptedTerms
            && acceptedPrivacy
    }

    var body: some View {
        Form {
            Section {
                HStack {
                    Spacer()
                    VStack(spacing: 10) {
                        KlangradarAppIcon(size: 68)
                        Text("Dein Klangradar Account")
                            .font(.title2.bold())
                        Text("Ein Account synchronisiert Favoriten, Interessen und Erinnerungen.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.center)
                    }
                    Spacer()
                }
                .listRowBackground(Color.clear)
            }

            // Generated by Claude Code — "Sicheres Passwort" war eine
            // eigene, große Section mit vollformatigen Zeilen pro
            // Anforderung. Jetzt kompakt als Fließtext-Checkliste direkt im
            // Footer unter den Feldern (näher an der Referenzvorgabe).
            Section {
                    TextField("E-Mail-Adresse", text: $email)
                        .textContentType(.emailAddress)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                        .keyboardType(.emailAddress)
                    RevealablePasswordField(title: "Passwort", text: $password, isRevealed: $showsPassword, textContentType: .newPassword)
                    RevealablePasswordField(title: "Passwort wiederholen", text: $passwordConfirmation, isRevealed: $showsPassword, textContentType: .newPassword)
            } header: {
                Text("Zugangsdaten")
            } footer: {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Mit diesen Zugangsdaten kannst du dich später auf jedem Gerät anmelden.")
                    ForEach(requirements, id: \.title) { requirement in
                        Label(requirement.title, systemImage: requirement.isMet ? "checkmark.circle.fill" : "circle")
                            .foregroundStyle(requirement.isMet ? .green : .secondary)
                    }
                    if !passwordConfirmation.isEmpty, password != passwordConfirmation {
                        Label("Die Passwörter stimmen nicht überein.", systemImage: "exclamationmark.circle.fill")
                            .foregroundStyle(.red)
                    }
                }
                .padding(.top, 6)
            }

            Section {
                Toggle(isOn: $acceptedTerms) {
                    Text("Ich akzeptiere die AGB.")
                }
                .toggleStyle(.checkbox)
                Toggle(isOn: $acceptedPrivacy) {
                    Text("Ich habe die Datenschutzerklärung gelesen.")
                }
                .toggleStyle(.checkbox)
                Toggle(isOn: $marketingEmailOptIn) {
                    // Generated by Claude Code — Icon-breiter Platzhalter,
                    // damit der Text mit den Checkbox-Zeilen darüber
                    // fluchtet statt am linken Rand zu beginnen (wirkte
                    // uneinheitlich/"durcheinander").
                    HStack(alignment: .top, spacing: 12) {
                        Color.clear.frame(width: 20, height: 1)
                        VStack(alignment: .leading) {
                            Text("Neuigkeiten per E-Mail")
                            Text("Optional und jederzeit widerrufbar").font(.caption).foregroundStyle(.secondary)
                        }
                    }
                }
            } footer: {
                // Generated by Claude Code — vorher öffnete "Impressum (AGB)"
                // nur das Impressum ohne AGB-Inhalt, und "Datenschutz"
                // verlinkte auf die falsche Domain (klangradar.app statt
                // .com) und lief damit ins Leere. Jetzt drei eigene,
                // funktionierende In-App-Links.
                HStack(spacing: 16) {
                    Button("AGB") { showsAGB = true }
                    Button("Datenschutz") { showsDatenschutz = true }
                    Button("Impressum") { showsImpressum = true }
                }
            }

            if let errorMessage {
                Section { Label(errorMessage, systemImage: "exclamationmark.triangle.fill").foregroundStyle(.red) }
            }
        }
        .navigationTitle("Account erstellen")
        .onboardingChrome()
        .navigationBarTitleDisplayMode(.inline)
        // Generated by Claude Code — Header direkt am Form (siehe
        // OnboardingView.swift für den Hintergrund dieses Musters).
        // onboardingBackground() NACH dem Header, damit ein einziger
        // Verlauf hinter beiden liegt statt zweier separater Kanten.
        .safeAreaInset(edge: .top, spacing: 0) { header }
        .onboardingBackground()
        .safeAreaInset(edge: .bottom) {
            Button { Task { await signUp() } } label: {
                Text("Account erstellen").frame(maxWidth: .infinity)
            }
                .authPrimaryButtonStyle()
                .controlSize(.large)
                .disabled(!isValid || isWorking)
                .authBottomActionLayout()
        }
        .overlay { if isWorking { ProgressView().controlSize(.large) } }
        .interactiveDismissDisabled(isWorking)
        .sheet(isPresented: $showsImpressum) {
            NavigationStack {
                ImpressumView()
                    .toolbar {
                        ToolbarItem(placement: .cancellationAction) {
                            Button("Fertig") { showsImpressum = false }
                        }
                    }
            }
        }
        .sheet(isPresented: $showsAGB) {
            NavigationStack {
                AGBView()
                    .toolbar {
                        ToolbarItem(placement: .cancellationAction) {
                            Button("Fertig") { showsAGB = false }
                        }
                    }
            }
        }
        .sheet(isPresented: $showsDatenschutz) {
            NavigationStack {
                DatenschutzView()
                    .toolbar {
                        ToolbarItem(placement: .cancellationAction) {
                            Button("Fertig") { showsDatenschutz = false }
                        }
                    }
            }
        }
    }

    private func signUp() async {
        isWorking = true
        errorMessage = nil
        defer { isWorking = false }
        let cleanEmail = email.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        do {
            try await auth.signUp(email: cleanEmail, password: password)
            onSignedUp(cleanEmail, marketingEmailOptIn)
        } catch {
            errorMessage = error.localizedDescription
        }
    }
}
