// Generated by Claude Code
// Generischer, konfigurationsgesteuerter Parser für öffentliche JSON-Event-APIs
// (z. B. alteoper.de/de/api/events/). Nutzt dieselbe config-Form, die für
// "api"-Quellen bereits in sources.config hinterlegt war, aber bisher von
// keinem Parser gelesen wurde (parseBayernCloud erwartet @graph/data und
// meldete deshalb "Response contained no event items").
//
// config: parser: "json_api", itemsPath, idPath, titlePath, startPath,
// endPath?, venuePath?, descriptionPath?, ticketPath?, imagePath?,
// urlTemplate? ("/de/programm/{slug}" — {feld} wird aus dem Item ersetzt),
// baseUrl?, nextPath? (Feld mit URL der Folgeseite, z. B. "next"),
// skipPastPath? (boolesches Feld, z. B. "is_past" -> Item überspringen).

import type { ParseResult, RawEvent } from "../types.ts";

export interface JsonApiConfig {
  itemsPath?: string;
  idPath?: string;
  titlePath?: string;
  startPath?: string;
  endPath?: string;
  venuePath?: string;
  descriptionPath?: string;
  ticketPath?: string;
  imagePath?: string;
  urlTemplate?: string;
  baseUrl?: string;
  nextPath?: string;
  skipPastPath?: string;
}

function getPath(obj: unknown, path: string | undefined): unknown {
  if (!path) return undefined;
  let cur: unknown = obj;
  for (const key of path.split(".")) {
    if (cur === null || typeof cur !== "object") return undefined;
    cur = (cur as Record<string, unknown>)[key];
  }
  return cur;
}

function str(value: unknown): string | null {
  if (typeof value === "number") return String(value);
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed ? trimmed : null;
}

function absolute(url: string | null, baseUrl: string | undefined): string | null {
  if (!url) return null;
  try {
    return new URL(url, baseUrl).toString();
  } catch {
    return null;
  }
}

export function jsonApiNextUrl(body: string, config: JsonApiConfig): string | null {
  if (!config.nextPath) return null;
  try {
    return absolute(str(getPath(JSON.parse(body), config.nextPath)), config.baseUrl);
  } catch {
    return null;
  }
}

export function parseJsonApi(body: string, config: JsonApiConfig): ParseResult {
  const events: RawEvent[] = [];
  const errors: string[] = [];

  let root: unknown;
  try {
    root = JSON.parse(body);
  } catch (err) {
    return { events, errors: [`Antwort ist kein gültiges JSON: ${err instanceof Error ? err.message : String(err)}`] };
  }

  const items = config.itemsPath ? getPath(root, config.itemsPath) : root;
  if (!Array.isArray(items)) {
    return { events, errors: [`itemsPath "${config.itemsPath ?? ""}" liefert keine Liste`] };
  }

  items.forEach((item, i) => {
    const label = `item ${i + 1}`;
    if (config.skipPastPath && getPath(item, config.skipPastPath) === true) return;

    const title = str(getPath(item, config.titlePath));
    const start = str(getPath(item, config.startPath));
    if (!title) return void errors.push(`${label}: kein Titel (${config.titlePath}), übersprungen`);
    if (!start || Number.isNaN(new Date(start).getTime())) {
      return void errors.push(`${label} ("${title}"): ungültiges Startdatum, übersprungen`);
    }

    const url = config.urlTemplate
      ? absolute(
        config.urlTemplate.replace(/\{([^}]+)\}/g, (_, key) => str(getPath(item, key)) ?? ""),
        config.baseUrl,
      )
      : null;
    const end = str(getPath(item, config.endPath));

    events.push({
      externalId: str(getPath(item, config.idPath)),
      title,
      description: str(getPath(item, config.descriptionPath)),
      startDateTime: start,
      endDateTime: end && !Number.isNaN(new Date(end).getTime()) ? end : null,
      venueName: null,
      venueAddress: null,
      venueDetail: str(getPath(item, config.venuePath)),
      url,
      ticketUrl: absolute(str(getPath(item, config.ticketPath)), config.baseUrl),
      imageUrl: absolute(str(getPath(item, config.imagePath)), config.baseUrl),
      priceMin: null,
      priceMax: null,
      isFree: null,
    });
  });

  return { events, errors };
}
