import { Geist, Geist_Mono } from "next/font/google";

// Flat-White-Redesign (Generated by Claude Code): eine Schriftfamilie für
// Landingpage, Redaktions-Dashboard und Veranstalterportal. next/font hostet
// die Dateien selbst — kein Laufzeit-Request zu Google Fonts.
export const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
  display: "swap",
});

export const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  display: "swap",
});
