"use client";

import { useState, useTransition } from "react";
import { assignEventToSeries, createEventSeries } from "./actions";

export type Series = { id: string; title: string; organizerId: string; description: string | null };
export type Event = { id: string; title: string; date: string; organizerId: string; seriesId: string | null };

export function SeriesManager({ organizers, series, events }: { organizers: { id: string; name: string }[]; series: Series[]; events: Event[] }) {
  const [pending, startTransition] = useTransition(); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const run = (job: () => Promise<void>, success: string) => startTransition(async () => { setError(null); setMessage(null); try { await job(); setMessage(success); } catch (cause) { setError(cause instanceof Error ? cause.message : "Speichern fehlgeschlagen."); } });
  return <div className="space-y-10">{error && <p className="text-sm text-red-700">{error}</p>}{message && <p className="text-sm text-emerald-700">{message}</p>}<section className="rounded-xl border border-black/[0.06] bg-[#f5f5f7] p-5"><h2 className="text-base font-semibold text-[#1d1d1f]">Neue Serie</h2><form className="mt-4 grid gap-3 sm:grid-cols-2" action={(data) => run(() => createEventSeries(data), "Serie angelegt.")}><select required name="organizer_id" className="rounded-lg border border-black/10 bg-white px-3 py-2 text-sm"><option value="">Institution wählen</option>{organizers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input required name="title" maxLength={160} placeholder="z. B. Orgelkonzerte 2026/27" className="rounded-lg border border-black/10 bg-white px-3 py-2 text-sm" /><textarea name="description_de" rows={2} placeholder="Gemeinsame Beschreibung (optional)" className="sm:col-span-2 rounded-lg border border-black/10 bg-white px-3 py-2 text-sm" /><button disabled={pending} className="justify-self-start rounded-full bg-[#0071e3] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{pending ? "Speichert…" : "Serie anlegen"}</button></form></section><section><h2 className="mb-3 text-sm font-semibold text-[#86868b]">Termine zuordnen</h2>{events.length === 0 ? <p className="text-sm text-[#86868b]">Noch keine eigenen Events.</p> : <div className="overflow-hidden rounded-xl border border-black/[0.06] bg-white"><table className="w-full text-sm"><thead className="border-b border-black/[0.06] text-left"><tr><th className="px-4 py-3 text-xs text-[#86868b]">Event</th><th className="px-4 py-3 text-xs text-[#86868b]">Termin</th><th className="px-4 py-3 text-xs text-[#86868b]">Serie</th></tr></thead><tbody className="divide-y divide-neutral-200">{events.map((event) => <tr key={event.id}><td className="px-4 py-3 font-medium text-[#1d1d1f]">{event.title}</td><td className="px-4 py-3 text-[#48484a]">{event.date}</td><td className="px-4 py-3"><select disabled={pending} value={event.seriesId ?? ""} onChange={(value) => run(() => assignEventToSeries(event.id, value.target.value || null), "Zuordnung gespeichert.")} className="rounded border border-black/10 bg-white px-2 py-1 text-sm"><option value="">Keine Serie</option>{series.filter((item) => item.organizerId === event.organizerId).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></td></tr>)}</tbody></table></div>}</section></div>;
}
