import Foundation

struct NotificationPreferences: Sendable {
    var newMatchingEvents = true
    var priceChanges = true
    var almostSoldOut = true
    var reminderDayBefore = true
    var followedEnsembleNewEvent = true
}

enum InterestCategory: String, CaseIterable, Sendable {
    case genre, work, person, ensemble, venue
    var title: String { switch self { case .genre: "Genres"; case .work: "Werke"; case .person: "Personen"; case .ensemble: "Ensembles"; case .venue: "Orte" } }
    var systemImage: String { switch self { case .genre: "music.quarternote.3"; case .work: "music.note.list"; case .person: "person"; case .ensemble: "person.3"; case .venue: "building.columns" } }
}
struct InterestOption: Identifiable, Hashable, Sendable { let id: String; let label: String; var photoURL: URL? = nil }

struct UserEventList: Identifiable, Hashable, Sendable {
    let id: UUID
    let name: String
    let createdAt: Date?
    let events: [ConcertEvent]
}

struct KlangradarUserProfile: Sendable {
    var displayName: String
    var birthDate: Date?
    var avatarURL: URL?
    var firstName: String?
    var lastName: String?
    var phone: String?
    var address: String?
}

struct RegionOption: Identifiable, Hashable, Sendable {
    let id: UUID
    let name: String
    var latitude: Double? = nil
    var longitude: Double? = nil
}

// Generated by Claude Code
/// Eine Zeile aus der View `city_regions`
/// (20261031000001_city_model_regions_extension.sql) -- im Unterschied zu
/// `RegionOption`/`activeRegions()` bewusst UNGEFILTERT nach `is_active`,
/// damit der Onboarding-Stadtwähler alle fünf Städte fest anzeigen kann
/// (München live, Berlin/Hamburg/Frankfurt/Wien als "bald verfügbar").
struct CityRegionOption: Identifiable, Hashable, Sendable {
    let id: UUID
    let slug: String
    let nameDE: String
    let shortNameDE: String?
    let regionName: String?
    let isActive: Bool
    let editorialStatus: String
    let sortOrder: Int
    var latitude: Double? = nil
    var longitude: Double? = nil

    /// `true` für "live" (aktuell nur München) -- alle anderen
    /// `editorial_status`-Werte (u.a. `soft_launch`) gelten als noch nicht
    /// redaktionell scharf geschaltet und bekommen im UI ein "bald
    /// verfügbar"-Badge, bleiben aber auswählbar.
    var isLive: Bool { editorialStatus == "live" }
}

// Zwei unabhängig entstandene, nicht überlappende Assistenz-Features
// (unterschiedliche Edge Functions "personal-concierge" vs.
// "klangradar-coach") -- beide behalten, da sie unterschiedliche Zwecke
// verfolgen (Orts-/Ticket-Chat vs. Stimmungs-Check-in-Coaching).
struct PersonalConciergeResult: Sendable {
    let conversationID: UUID
    let message: String
    let events: [PersonalConciergeEvent]
    let places: [PersonalConciergePlace]
    let languageProvider: String
    let placesProvider: String
}

struct PersonalConciergeEvent: Identifiable, Hashable, Sendable {
    let id: UUID
    let slug: String
    let title: String
    let subtitle: String?
    let startDate: Date?
    let venueID: UUID?
    let venueName: String
    let priceMin: Double?
    let priceMax: Double?
    let currency: String
    let isFree: Bool
    let ticketURL: URL?
    let reasons: [String]

    var concertEvent: ConcertEvent {
        ConcertEvent(
            id: id, slug: slug, title: title, subtitle: subtitle,
            startDatetime: startDate.map { ISO8601DateFormatter().string(from: $0) } ?? ISO8601DateFormatter().string(from: .now),
            imageUrls: nil, status: "scheduled",
            venues: venueID.map { VenueSummary(id: $0, name: venueName) },
            isFree: isFree
        )
    }
}

struct PersonalConciergePlace: Identifiable, Hashable, Sendable {
    let id: String
    let name: String
    let address: String?
    let mapsURL: URL?
    let rating: Double?
}

struct KlangradarStats: Sendable {
    let savedEvents: Int
    let plannedEvents: Int
    let visitedEvents: Int
    let followedPersons: Int
    let followedEnsembles: Int
    let followedVenues: Int
    let followedWorks: Int
}

struct CoachInsight: Identifiable, Hashable, Sendable {
    let id: String
    let kind: String
    let title: String
    let body: String
    let priority: Int
    let actions: [JSONObject]
}

struct CoachDashboard: Sendable {
    let signalQuality: String
    let knownPreferences: Int
    let recentIntentSignals: Int
    let plannedEvents: Int
    let reflectedVisits: Int
    let savedEvents: Int
    let recentViews: Int
    let topGenres: [String]
    let latestCheckin: JSONObject?
    let insights: [CoachInsight]
    let trends: [JSONObject]
}

struct CoachEvent: Identifiable, Hashable, Sendable {
    let id: UUID
    let slug: String
    let title: String
    let subtitle: String?
    let startDate: Date?
    let venueID: UUID?
    let venueName: String
    let priceMin: Double?
    let isFree: Bool
    let ticketURL: URL?
    let imageURL: URL?
    let reasons: [String]

    var concertEvent: ConcertEvent {
        ConcertEvent(
            id: id, slug: slug, title: title, subtitle: subtitle,
            startDatetime: startDate.map { ISO8601DateFormatter().string(from: $0) } ?? ISO8601DateFormatter().string(from: .now),
            imageUrls: imageURL.map { [$0.absoluteString] }, status: "scheduled",
            venues: venueID.map { VenueSummary(id: $0, name: venueName) },
            isFree: isFree
        )
    }
}

struct CoachReply: Sendable {
    let conversationID: UUID?
    let answer: String
    let events: [CoachEvent]
    /// true, wenn keine exakte Übereinstimmung gefunden wurde und `events`
    /// stattdessen gelockerte Alternativen enthält (siehe klangradar-coach
    /// Edge Function) -- die Chat-UI kennzeichnet die Karten dann als
    /// "Alternativen" statt als Treffer.
    let eventsAreAlternatives: Bool
    let actions: [JSONObject]
    let memoryProposal: JSONObject?
    let goalProposal: JSONObject?
    let suggestedPrompts: [String]
    let provider: String
}

struct UserRepository: Sendable {
    let client: SupabaseRESTClient

    func askConcierge(message: String, conversationID: UUID?, token: String) async throws -> PersonalConciergeResult {
        var body: JSONObject = ["message": .string(message)]
        if let conversationID { body["conversation_id"] = .string(conversationID.uuidString) }
        let response: JSONObject = try await client.edgeFunction("personal-concierge", body: body, accessToken: token)
        guard let id = response.string("conversation_id").flatMap(UUID.init(uuidString:)) else {
            throw APIError.invalidResponse
        }
        let events = response.objects("events").compactMap { row -> PersonalConciergeEvent? in
            guard let eventID = row.string("id").flatMap(UUID.init(uuidString:)),
                  let slug = row.string("slug"), let title = row.string("title") else { return nil }
            let ticketRows = row.objects("tickets")
            let bestTicket = ticketRows.first { $0.bool("is_broken") != true }
            return PersonalConciergeEvent(
                id: eventID, slug: slug, title: title, subtitle: row.string("subtitle"),
                startDate: row.string("start_datetime").flatMap(FlexibleDateParser.date(from:)),
                venueID: row.string("venue_id").flatMap(UUID.init(uuidString:)),
                venueName: row.string("venue_name") ?? "Ort folgt",
                priceMin: row.number("price_min"), priceMax: row.number("price_max"),
                currency: row.string("price_currency") ?? "EUR", isFree: row.bool("is_free") ?? false,
                ticketURL: (bestTicket?.string("url") ?? row.string("ticket_url") ?? row.string("website_url")).flatMap(URL.init(string:)),
                reasons: row.strings("reasons")
            )
        }
        let places = response.objects("places").compactMap { row -> PersonalConciergePlace? in
            let displayName = row.object("displayName")?.string("text")
            guard let name = displayName else { return nil }
            return PersonalConciergePlace(
                id: row.string("id") ?? name, name: name,
                address: row.string("formattedAddress"),
                mapsURL: row.string("googleMapsUri").flatMap(URL.init(string:)),
                rating: row.number("rating")
            )
        }
        let providers = response.object("providers") ?? [:]
        return PersonalConciergeResult(
            conversationID: id, message: response.string("message") ?? "",
            events: events, places: places,
            languageProvider: providers.string("language") ?? "local-parser",
            placesProvider: providers.string("places") ?? "not-configured"
        )
    }

    func klangradarStats(token: String) async throws -> KlangradarStats {
        let row: JSONObject = try await client.rpc("my_klangradar_stats", accessToken: token)
        return KlangradarStats(
            savedEvents: Int(row.number("saved_events") ?? 0), plannedEvents: Int(row.number("planned_events") ?? 0),
            visitedEvents: Int(row.number("visited_events") ?? 0), followedPersons: Int(row.number("followed_persons") ?? 0),
            followedEnsembles: Int(row.number("followed_ensembles") ?? 0), followedVenues: Int(row.number("followed_venues") ?? 0),
            followedWorks: Int(row.number("followed_works") ?? 0)
        )
    }

    func coachDashboard(token: String) async throws -> CoachDashboard {
        let response: JSONObject = try await client.edgeFunction("klangradar-coach", body: ["action": .string("dashboard")], accessToken: token)
        let context = response.object("context") ?? [:]
        let lenses = context.object("coach_lenses") ?? [:]
        let fit = lenses.object("fit") ?? [:]
        let rhythm = lenses.object("rhythm") ?? [:]
        let discovery = lenses.object("discovery") ?? [:]
        let topGenres = discovery.objects("top_genres").compactMap { $0.string("name") }
        return CoachDashboard(
            signalQuality: context.string("signal_quality") ?? "low",
            knownPreferences: fit.integer("known_preferences") ?? 0,
            recentIntentSignals: fit.integer("recent_intent_signals") ?? 0,
            plannedEvents: rhythm.integer("planned") ?? 0,
            reflectedVisits: rhythm.integer("reflected_visits") ?? 0,
            savedEvents: rhythm.integer("saved") ?? 0,
            recentViews: discovery.integer("recent_views") ?? 0,
            topGenres: topGenres,
            latestCheckin: context.object("latest_checkin"),
            insights: response.objects("insights").compactMap { row in
                guard let title = row.string("title"), let body = row.string("body") else { return nil }
                return CoachInsight(id: row.string("id") ?? row.string("fingerprint") ?? UUID().uuidString, kind: row.string("kind") ?? "planning", title: title, body: body, priority: row.integer("priority") ?? 0, actions: row.objects("actions"))
            },
            trends: response.objects("trends")
        )
    }

    func coachCheckin(mood: String, energy: Int, minutes: Int?, budget: Double?, companion: String?, token: String) async throws {
        var body: JSONObject = ["action": .string("checkin"), "mood": .string(mood), "energy": .number(Double(energy))]
        body["available_minutes"] = minutes.map { .number(Double($0)) } ?? .null
        body["budget"] = budget.map(JSONValue.number) ?? .null
        body["companion"] = companion.map(JSONValue.string) ?? .null
        let _: JSONObject = try await client.edgeFunction("klangradar-coach", body: body, accessToken: token)
    }

    // cityName: die im Stadt-Chip aktuell gewählte Stadt (siehe CityStore) --
    // Nutzerfeedback "Datenanbindung ... nur auf ausgewählter Stadt
    // basierend": ohne diesen Kontext kannte die KI die App-Stadtauswahl
    // nicht und musste ohne Stadt-Eingrenzung über alle Städte suchen.
    func askCoach(message: String, conversationID: UUID?, cityName: String?, token: String) async throws -> CoachReply {
        var body: JSONObject = ["action": .string("chat"), "message": .string(message)]
        if let conversationID { body["conversation_id"] = .string(conversationID.uuidString) }
        if let cityName { body["city_name"] = .string(cityName) }
        let response: JSONObject = try await client.edgeFunction("klangradar-coach", body: body, accessToken: token)
        let events = response.objects("events").compactMap { row -> CoachEvent? in
            guard let id = row.string("id").flatMap(UUID.init(uuidString:)), let slug = row.string("slug"), let title = row.string("title") else { return nil }
            return CoachEvent(
                id: id, slug: slug, title: title, subtitle: row.string("subtitle"),
                startDate: row.string("start_datetime").flatMap(FlexibleDateParser.date(from:)),
                venueID: row.string("venue_id").flatMap(UUID.init(uuidString:)), venueName: row.string("venue_name") ?? "Ort folgt",
                priceMin: row.number("price_min"), isFree: row.bool("is_free") ?? false,
                ticketURL: (row.string("ticket_url") ?? row.string("website_url")).flatMap(URL.init(string:)),
                imageURL: row.string("image_url").flatMap(URL.init(string:)),
                reasons: row.strings("reasons")
            )
        }
        return CoachReply(
            conversationID: response.string("conversation_id").flatMap(UUID.init(uuidString:)),
            answer: response.string("answer") ?? "",
            events: events, eventsAreAlternatives: response.bool("events_are_alternatives") ?? false,
            actions: response.objects("actions"),
            memoryProposal: response.object("memory_proposal"), goalProposal: response.object("goal_proposal"),
            suggestedPrompts: response.strings("suggested_prompts"), provider: response.string("provider") ?? "local"
        )
    }

    func confirmCoachProposal(_ proposal: JSONObject, kind: String, token: String) async throws {
        let _: JSONObject = try await client.edgeFunction("klangradar-coach", body: ["action": .string(kind), "proposal": .object(proposal)], accessToken: token)
    }

    func profile(userID: UUID, token: String) async throws -> KlangradarUserProfile {
        let rows: [JSONObject] = try await client.get(
            table: "profiles",
            queryItems: [
                URLQueryItem(name: "select", value: "display_name,birth_date,avatar_url,first_name,last_name,phone,address"),
                URLQueryItem(name: "id", value: "eq.\(userID.uuidString)"),
                URLQueryItem(name: "limit", value: "1")
            ],
            accessToken: token
        )
        let row = rows.first ?? [:]
        return KlangradarUserProfile(
            displayName: row.string("display_name") ?? "",
            birthDate: row.string("birth_date").flatMap(FlexibleDateParser.date(from:)),
            avatarURL: row.string("avatar_url").flatMap(URL.init(string:)),
            firstName: row.string("first_name"),
            lastName: row.string("last_name"),
            phone: row.string("phone"),
            address: row.string("address")
        )
    }

    /// Onboarding-Schritt "Persönliche Daten" — separat von `updateProfile`
    /// (das bleibt für die bestehende Profil-Bearbeitung unverändert), da
    /// Vor-/Nachname dort getrennt erfasst werden, `display_name` aber für
    /// bestehende Anzeigen weiter als kombinierter Name gepflegt wird.
    func updatePersonalData(
        firstName: String,
        lastName: String,
        userID: UUID,
        token: String
    ) async throws {
        let cleanFirst = firstName.trimmingCharacters(in: .whitespacesAndNewlines)
        let cleanLast = lastName.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleanFirst.isEmpty else { return }
        let displayName = cleanLast.isEmpty ? cleanFirst : "\(cleanFirst) \(cleanLast)"
        try await client.update(
            table: "profiles",
            values: [
                "first_name": .string(cleanFirst),
                "last_name": .string(cleanLast),
                "display_name": .string(displayName)
            ],
            filters: [URLQueryItem(name: "id", value: "eq.\(userID.uuidString)")],
            accessToken: token
        )
    }

    func acceptTerms(version: String, marketingEmailOptIn: Bool, userID: UUID, token: String) async throws {
        try await client.update(
            table: "profiles",
            values: [
                "terms_accepted_at": .string(ISO8601DateFormatter().string(from: .now)),
                "terms_version": .string(version),
                "marketing_email_opt_in": .bool(marketingEmailOptIn)
            ],
            filters: [URLQueryItem(name: "id", value: "eq.\(userID.uuidString)")],
            accessToken: token
        )
    }

    /// `update_home_location` ist eine `returns void`-SQL-Funktion
    /// (20260724000001_update_home_location.sql) — PostgREST liefert dafür
    /// den JSON-Wert `null`, den `JSONValue` direkt dekodieren kann.
    func updateHomeLocation(latitude: Double, longitude: Double, token: String) async throws {
        let _: JSONValue = try await client.rpc(
            "update_home_location",
            parameters: ["p_lat": .number(latitude), "p_lng": .number(longitude)],
            accessToken: token
        )
    }

    /// Seit der Stadt-Erweiterung (Berlin/Hamburg/Frankfurt/Wien neben
    /// München, siehe docs/12-city-expansion-import.md) können hier mehrere
    /// aktive Städte zurückkommen -- Grundlage für den manuellen
    /// Standort-Fallback im Onboarding UND für CityStore/CitySwitcherView.
    /// latitude/longitude (20261031000001_city_model_regions_extension.sql)
    /// werden für die "Stadt anhand meines Standorts empfehlen"-Funktion
    /// mitgeladen.
    func activeRegions() async throws -> [RegionOption] {
        let rows: [JSONObject] = try await client.get(table: "regions", queryItems: [
            URLQueryItem(name: "select", value: "id,name,latitude,longitude"),
            URLQueryItem(name: "type", value: "eq.city"),
            URLQueryItem(name: "is_active", value: "eq.true"),
            URLQueryItem(name: "order", value: "name.asc")
        ])
        return rows.compactMap { row in
            guard let id = row.string("id").flatMap(UUID.init(uuidString:)), let name = row.string("name") else { return nil }
            return RegionOption(id: id, name: name, latitude: row.number("latitude"), longitude: row.number("longitude"))
        }
    }

    // Generated by Claude Code
    /// Alle fünf Städte aus der View `city_regions`, unabhängig von
    /// `is_active` -- Grundlage für den echten Stadt-Auswahlbildschirm im
    /// Onboarding (Punkt 4 der Ziel-Struktur). Verändert bewusst NICHT
    /// `activeRegions()`, das weiterhin nur live geschaltete Städte für
    /// CityStore/CitySwitcherView liefert.
    func allCityRegions() async throws -> [CityRegionOption] {
        let rows: [JSONObject] = try await client.get(table: "city_regions", queryItems: [
            URLQueryItem(name: "select", value: "id,slug,name_de,short_name_de,region_name,is_active,editorial_status,sort_order,latitude,longitude"),
            URLQueryItem(name: "order", value: "sort_order.asc")
        ])
        return rows.compactMap { row in
            guard let id = row.string("id").flatMap(UUID.init(uuidString:)),
                  let slug = row.string("slug"),
                  let nameDE = row.string("name_de"),
                  let editorialStatus = row.string("editorial_status") else { return nil }
            return CityRegionOption(
                id: id,
                slug: slug,
                nameDE: nameDE,
                shortNameDE: row.string("short_name_de"),
                regionName: row.string("region_name"),
                isActive: row.bool("is_active") ?? false,
                editorialStatus: editorialStatus,
                sortOrder: row.integer("sort_order") ?? 0,
                latitude: row.number("latitude"),
                longitude: row.number("longitude")
            )
        }
    }

    func setPreferredRegion(regionID: UUID, userID: UUID, token: String) async throws {
        try await client.update(
            table: "profiles",
            values: ["preferred_region_id": .string(regionID.uuidString)],
            filters: [URLQueryItem(name: "id", value: "eq.\(userID.uuidString)")],
            accessToken: token
        )
    }

    /// Für CityStore: die zuletzt gewählte/gespeicherte Stadt eines
    /// angemeldeten Nutzers, um die Sitzungsauswahl beim nächsten Start
    /// vorzubelegen (siehe setPreferredRegion).
    func preferredRegionID(userID: UUID, token: String) async throws -> UUID? {
        let rows: [JSONObject] = try await client.get(
            table: "profiles",
            queryItems: [
                URLQueryItem(name: "select", value: "preferred_region_id"),
                URLQueryItem(name: "id", value: "eq.\(userID.uuidString)"),
                URLQueryItem(name: "limit", value: "1")
            ],
            accessToken: token
        )
        return rows.first?.string("preferred_region_id").flatMap(UUID.init(uuidString:))
    }

    func isOnboardingCompleted(userID: UUID, token: String) async throws -> Bool {
        let rows: [JSONObject] = try await client.get(
            table: "profiles",
            queryItems: [
                URLQueryItem(name: "select", value: "onboarding_completed"),
                URLQueryItem(name: "id", value: "eq.\(userID.uuidString)"),
                URLQueryItem(name: "limit", value: "1")
            ],
            accessToken: token
        )
        return rows.first?.bool("onboarding_completed") ?? false
    }

    func markOnboardingCompleted(userID: UUID, token: String) async throws {
        try await client.update(
            table: "profiles",
            values: ["onboarding_completed": .bool(true)],
            filters: [URLQueryItem(name: "id", value: "eq.\(userID.uuidString)")],
            accessToken: token
        )
    }

    func updateProfile(
        displayName: String,
        birthDate: Date?,
        userID: UUID,
        token: String
    ) async throws {
        let cleanName = String(displayName.trimmingCharacters(in: .whitespacesAndNewlines).prefix(80))
        guard !cleanName.isEmpty else { return }
        let dateValue: JSONValue = birthDate.map {
            .string(KlangradarDateTime.string($0, format: "yyyy-MM-dd"))
        } ?? .null
        try await client.update(
            table: "profiles",
            values: ["display_name": .string(cleanName), "birth_date": dateValue],
            filters: [URLQueryItem(name: "id", value: "eq.\(userID.uuidString)")],
            accessToken: token
        )
    }

    func profileAvatarURL(userID: UUID, token: String) async throws -> URL? {
        let rows: [JSONObject] = try await client.get(
            table: "profiles",
            queryItems: [
                URLQueryItem(name: "select", value: "avatar_url"),
                URLQueryItem(name: "id", value: "eq.\(userID.uuidString)"),
                URLQueryItem(name: "limit", value: "1")
            ],
            accessToken: token
        )
        return rows.first?.string("avatar_url").flatMap(URL.init(string:))
    }

    func uploadProfileAvatar(
        _ data: Data,
        userID: UUID,
        token: String
    ) async throws -> URL {
        let path = "\(userID.uuidString.lowercased())/avatar.jpg"
        let publicURL = try await client.uploadPublicObject(
            bucket: "profile-avatars",
            path: path,
            data: data,
            contentType: "image/jpeg",
            accessToken: token
        )
        var components = URLComponents(url: publicURL, resolvingAgainstBaseURL: false)
        components?.queryItems = [URLQueryItem(name: "v", value: String(Int(Date().timeIntervalSince1970)))]
        let versionedURL = components?.url ?? publicURL
        try await client.update(
            table: "profiles",
            values: ["avatar_url": .string(versionedURL.absoluteString)],
            filters: [URLQueryItem(name: "id", value: "eq.\(userID.uuidString)")],
            accessToken: token
        )
        return versionedURL
    }

    func deleteProfileAvatar(userID: UUID, token: String) async throws {
        let path = "\(userID.uuidString.lowercased())/avatar.jpg"
        try await client.deleteStorageObject(
            bucket: "profile-avatars",
            path: path,
            accessToken: token
        )
        try await client.update(
            table: "profiles",
            values: ["avatar_url": .null],
            filters: [URLQueryItem(name: "id", value: "eq.\(userID.uuidString)")],
            accessToken: token
        )
    }

    func favoriteEvents(userID: UUID, token: String) async throws -> [ConcertEvent] {
        let rows: [JSONObject] = try await client.get(table: "favorites", queryItems: [
            URLQueryItem(
                name: "select",
                value: "events(id,slug,title,subtitle,start_datetime,image_urls,status,category,is_free,venues(id,name,photo_url),event_genres(genres(id,slug,label_de)),event_participants(persons(id,full_name,photo_url),ensembles(id,name,photo_url)))"
            ),
            URLQueryItem(name: "user_id", value: "eq.\(userID.uuidString)")
        ], accessToken: token)
        return rows.compactMap { $0.object("events") }.compactMap(ConcertEvent.init(json:))
    }

    func favoriteIDs(userID: UUID, token: String) async throws -> Set<UUID> {
        let rows: [JSONObject] = try await client.get(table: "favorites", queryItems: [
            URLQueryItem(name: "select", value: "event_id"),
            URLQueryItem(name: "user_id", value: "eq.\(userID.uuidString)")
        ], accessToken: token)
        return Set(rows.compactMap { $0.string("event_id").flatMap(UUID.init(uuidString:)) })
    }

    func setFavorite(eventID: UUID, isFavorite: Bool, userID: UUID, token: String) async throws {
        if isFavorite {
            _ = try await client.insert(table: "favorites", values: ["user_id": .string(userID.uuidString), "event_id": .string(eventID.uuidString)], accessToken: token)
        } else {
            try await client.delete(table: "favorites", filters: [URLQueryItem(name: "user_id", value: "eq.\(userID.uuidString)"), URLQueryItem(name: "event_id", value: "eq.\(eventID.uuidString)")], accessToken: token)
        }
    }

    func eventLists(userID: UUID, token: String) async throws -> [UserEventList] {
        let rows: [JSONObject] = try await client.get(table: "favorite_lists", queryItems: [
            URLQueryItem(
                name: "select",
                value: "id,name,created_at,favorite_list_items(added_at,events(id,slug,title,subtitle,start_datetime,image_urls,status,category,is_free,venues(id,name,photo_url),event_genres(genres(id,slug,label_de))))"
            ),
            URLQueryItem(name: "user_id", value: "eq.\(userID.uuidString)"),
            URLQueryItem(name: "order", value: "created_at.desc")
        ], accessToken: token)
        return rows.compactMap { row in
            guard let id = row.string("id").flatMap(UUID.init(uuidString:)),
                  let name = row.string("name") else { return nil }
            let events = row.objects("favorite_list_items")
                .compactMap { $0.object("events") }
                .compactMap(ConcertEvent.init(json:))
                .sorted { ($0.startDate ?? .distantFuture) < ($1.startDate ?? .distantFuture) }
            return UserEventList(
                id: id,
                name: name,
                createdAt: row.string("created_at").flatMap(FlexibleDateParser.date(from:)),
                events: events
            )
        }
    }

    func createEventList(name: String, userID: UUID, token: String) async throws -> UserEventList? {
        let cleanName = String(name.trimmingCharacters(in: .whitespacesAndNewlines).prefix(80))
        guard !cleanName.isEmpty else { return nil }
        let rows = try await client.insert(
            table: "favorite_lists",
            values: ["user_id": .string(userID.uuidString), "name": .string(cleanName)],
            accessToken: token,
            returning: true
        )
        guard let row = rows.first,
              let id = row.string("id").flatMap(UUID.init(uuidString:)) else { return nil }
        return UserEventList(id: id, name: row.string("name") ?? cleanName, createdAt: nil, events: [])
    }

    func renameEventList(id: UUID, name: String, token: String) async throws {
        let cleanName = String(name.trimmingCharacters(in: .whitespacesAndNewlines).prefix(80))
        guard !cleanName.isEmpty else { return }
        try await client.update(
            table: "favorite_lists",
            values: ["name": .string(cleanName)],
            filters: [URLQueryItem(name: "id", value: "eq.\(id.uuidString)")],
            accessToken: token
        )
    }

    func deleteEventList(id: UUID, token: String) async throws {
        try await client.delete(
            table: "favorite_lists",
            filters: [URLQueryItem(name: "id", value: "eq.\(id.uuidString)")],
            accessToken: token
        )
    }

    func replaceEvents(in listID: UUID, selected: Set<UUID>, previous: Set<UUID>, token: String) async throws {
        for eventID in selected.subtracting(previous) {
            _ = try await client.insert(
                table: "favorite_list_items",
                values: ["list_id": .string(listID.uuidString), "event_id": .string(eventID.uuidString)],
                accessToken: token
            )
        }
        for eventID in previous.subtracting(selected) {
            try await client.delete(
                table: "favorite_list_items",
                filters: [
                    URLQueryItem(name: "list_id", value: "eq.\(listID.uuidString)"),
                    URLQueryItem(name: "event_id", value: "eq.\(eventID.uuidString)")
                ],
                accessToken: token
            )
        }
    }

    func preferences(userID: UUID, token: String) async throws -> NotificationPreferences {
        let rows: [JSONObject] = try await client.get(table: "notification_preferences", queryItems: [
            URLQueryItem(name: "select", value: "*"),
            URLQueryItem(name: "user_id", value: "eq.\(userID.uuidString)"),
            URLQueryItem(name: "limit", value: "1")
        ], accessToken: token)
        guard let row = rows.first else { return NotificationPreferences() }
        return NotificationPreferences(
            newMatchingEvents: row.bool("new_matching_events") ?? true,
            priceChanges: row.bool("price_changes") ?? true,
            almostSoldOut: row.bool("almost_sold_out") ?? true,
            reminderDayBefore: row.bool("reminder_day_before") ?? true,
            followedEnsembleNewEvent: row.bool("followed_ensemble_new_event") ?? true
        )
    }

    func setPreference(userID: UUID, token: String, column: String, value: Bool) async throws {
        try await client.upsert(table: "notification_preferences", values: [
            "user_id": .string(userID.uuidString), column: .bool(value)
        ], accessToken: token, conflictColumns: "user_id")
    }

    /// Nutzeranfrage: Fehlermeldungen auch aus der nativen App möglich machen,
    /// analog zu Flutters ReportContentSheet (app/lib/core/widgets/
    /// report_content_sheet.dart). Schreibt in dieselbe content_reports-
    /// Tabelle; die platform-Spalte (Migration 20261011000006) unterscheidet
    /// in der Redaktion zwischen Flutter- und Native-Meldungen.
    func reportContent(
        entityType: String,
        entityID: String,
        reason: String,
        message: String?,
        userID: UUID?,
        token: String
    ) async throws {
        var values: JSONObject = [
            "entity_type": .string(entityType),
            "entity_id": .string(entityID),
            "reason": .string(reason),
            "platform": .string("native")
        ]
        values["reporter_id"] = userID.map { .string($0.uuidString) } ?? .null
        if let message, !message.isEmpty { values["message"] = .string(message) }
        _ = try await client.insert(table: "content_reports", values: values, accessToken: token)
    }

    func interestOptions(_ category: InterestCategory) async throws -> [InterestOption] {
        let specification: (String, String, String)
        switch category {
        case .genre: specification = ("genres", "id,label_de", "sort_order")
        case .work: specification = ("works", "id,title,composer:persons(full_name)", "title")
        case .person: specification = ("persons", "id,full_name,photo_url", "full_name")
        case .ensemble: specification = ("ensembles", "id,name,photo_url", "name")
        case .venue: specification = ("venues", "id,name,photo_url", "name")
        }
        var rows: [JSONObject] = []
        let pageSize = 500
        while true {
            let page: [JSONObject] = try await client.get(table: specification.0, queryItems: [
                URLQueryItem(name: "select", value: specification.1),
                URLQueryItem(name: "order", value: "\(specification.2).asc"),
                URLQueryItem(name: "limit", value: String(pageSize)),
                URLQueryItem(name: "offset", value: String(rows.count))
            ])
            rows.append(contentsOf: page)
            if page.count < pageSize { break }
        }
        return rows.compactMap { row in
            guard let id = row.string("id"),
                  let baseLabel = row.string("label_de") ?? row.string("title") ?? row.string("full_name") ?? row.string("name")
            else { return nil }
            let label: String
            if category == .work, let composer = row.object("composer")?.string("full_name") {
                label = "\(baseLabel) — \(composer)"
            } else {
                label = baseLabel
            }
            return InterestOption(id: id, label: label, photoURL: row.string("photo_url").flatMap(URL.init(string:)))
        }
            .sorted { $0.label.localizedStandardCompare($1.label) == .orderedAscending }
    }

    func selectedInterests(_ category: InterestCategory, userID: UUID, token: String) async throws -> Set<String> {
        let (table, column) = interestStorage(category)
        let rows: [JSONObject] = try await client.get(table: table, queryItems: [URLQueryItem(name: "select", value: column), URLQueryItem(name: "user_id", value: "eq.\(userID.uuidString)")], accessToken: token)
        return Set(rows.compactMap { $0.string(column) })
    }

    func setInterest(_ category: InterestCategory, id: String, selected: Bool, userID: UUID, token: String) async throws {
        let (table, column) = interestStorage(category)
        if selected { _ = try await client.insert(table: table, values: ["user_id": .string(userID.uuidString), column: .string(id)], accessToken: token) }
        else { try await client.delete(table: table, filters: [URLQueryItem(name: "user_id", value: "eq.\(userID.uuidString)"), URLQueryItem(name: column, value: "eq.\(id)")], accessToken: token) }
    }

    // recommended_events/discovery_events/popular_events haben alle drei
    // `p_city_id uuid default munich_city_id()` (siehe
    // 20261031000011_recommended_discovery_city_filter.sql und
    // 20261031000005_city_scoped_rpcs.sql) -- ein weggelassener Parameter
    // lässt den Default (München) greifen statt der tatsächlich in
    // CityStore gewählten Stadt. Das ließ Home-Rails wie "Für dich" und
    // "Beliebt" unabhängig vom Stadt-Filter immer Münchner Termine zeigen,
    // während die übrige Home-Abfrage (upcomingEvents(regionID:)) korrekt
    // filterte. cityID == nil ("Alle Städte") muss explizit `.null` senden,
    // sonst greift wieder der München-Default.
    func recommendedEvents(limit: Int = 16, cityID: UUID?, token: String? = nil) async throws -> [ConcertEvent] {
        try await homeEvents(function: "recommended_events", limit: limit, cityID: cityID, token: token)
    }

    func discoveryEvents(limit: Int = 16, cityID: UUID?, token: String) async throws -> [ConcertEvent] {
        try await homeEvents(function: "discovery_events", limit: limit, cityID: cityID, token: token)
    }

    func popularEvents(limit: Int = 16, cityID: UUID?, token: String? = nil) async throws -> [ConcertEvent] {
        try await homeEvents(function: "popular_events", limit: limit, cityID: cityID, token: token)
    }

    private func homeEvents(function: String, limit: Int, cityID: UUID?, token: String?) async throws -> [ConcertEvent] {
        let rows: [JSONObject] = try await client.rpc(
            function,
            parameters: [
                "p_result_limit": .number(Double(limit)),
                "p_city_id": cityID.map { .string($0.uuidString) } ?? .null
            ],
            accessToken: token
        )
        return rows.compactMap { original in
            var row = original
            if var venue = row.object("venues"),
               venue.string("id") == nil,
               let venueID = row.string("venue_id") {
                venue["id"] = .string(venueID)
                row["venues"] = .object(venue)
            }
            if row.string("status") == nil { row["status"] = .string("scheduled") }
            return ConcertEvent(json: row)
        }
    }

    private func interestStorage(_ category: InterestCategory) -> (String, String) {
        switch category { case .genre: ("profile_interest_genres", "genre_id"); case .work: ("user_favorite_works", "work_id"); case .person: ("user_favorite_persons", "person_id"); case .ensemble: ("user_favorite_ensembles", "ensemble_id"); case .venue: ("user_favorite_venues", "venue_id") }
    }
}

@MainActor
final class FavoriteStore: ObservableObject {
    @Published private(set) var ids: Set<UUID> = []
    private let auth: AuthStore
    private let repository: UserRepository?

    init(auth: AuthStore, repository: UserRepository?) { self.auth = auth; self.repository = repository }

    func load() async {
        guard let repository, let userID = auth.userID, let token = auth.accessToken else { return }
        ids = (try? await repository.favoriteIDs(userID: userID, token: token)) ?? []
    }

    func toggle(_ eventID: UUID) async {
        guard let repository, let userID = auth.userID, let token = auth.accessToken else { return }
        let newValue = !ids.contains(eventID)
        if newValue { ids.insert(eventID) } else { ids.remove(eventID) }
        do { try await repository.setFavorite(eventID: eventID, isFavorite: newValue, userID: userID, token: token) }
        catch { if newValue { ids.remove(eventID) } else { ids.insert(eventID) } }
    }
}

/// Nutzerwunsch: "bestimmten Ensembles/Personen/Venues folgen" direkt von
/// der jeweiligen Detailseite aus, statt nur über die separate Interessen-
/// Einstellungsseite — nutzt dieselben Tabellen (user_favorite_persons/
/// _ensembles/_venues), damit ein Follow auf der Detailseite und eine
/// Auswahl unter Profil → Interessen konsistent denselben Zustand
/// widerspiegeln. Genres bleiben bewusst außen vor (kein Follow-Button auf
/// einer Genre-Detailseite).
@MainActor
final class FollowStore: ObservableObject {
    @Published private(set) var personIDs: Set<UUID> = []
    @Published private(set) var ensembleIDs: Set<UUID> = []
    @Published private(set) var venueIDs: Set<UUID> = []
    private let auth: AuthStore
    private let repository: UserRepository?

    init(auth: AuthStore, repository: UserRepository?) { self.auth = auth; self.repository = repository }

    var isSignedIn: Bool { auth.userID != nil }

    func load() async {
        guard let repository, let userID = auth.userID, let token = auth.accessToken else { return }
        async let persons = try? repository.selectedInterests(.person, userID: userID, token: token)
        async let ensembles = try? repository.selectedInterests(.ensemble, userID: userID, token: token)
        async let venues = try? repository.selectedInterests(.venue, userID: userID, token: token)
        personIDs = Set(((await persons) ?? []).compactMap(UUID.init(uuidString:)))
        ensembleIDs = Set(((await ensembles) ?? []).compactMap(UUID.init(uuidString:)))
        venueIDs = Set(((await venues) ?? []).compactMap(UUID.init(uuidString:)))
    }

    func isFollowing(kind: EntityKind, id: UUID) -> Bool {
        switch kind {
        case .person: personIDs.contains(id)
        case .ensemble: ensembleIDs.contains(id)
        case .venue: venueIDs.contains(id)
        case .work: false
        }
    }

    func toggle(kind: EntityKind, id: UUID) async {
        guard let repository, let userID = auth.userID, let token = auth.accessToken else { return }
        let category: InterestCategory
        switch kind {
        case .person: category = .person
        case .ensemble: category = .ensemble
        case .venue: category = .venue
        case .work: return
        }
        let newValue = !isFollowing(kind: kind, id: id)
        setLocal(kind: kind, id: id, following: newValue)
        do {
            try await repository.setInterest(category, id: id.uuidString, selected: newValue, userID: userID, token: token)
        } catch {
            setLocal(kind: kind, id: id, following: !newValue)
        }
    }

    private func setLocal(kind: EntityKind, id: UUID, following: Bool) {
        switch kind {
        case .person: if following { personIDs.insert(id) } else { personIDs.remove(id) }
        case .ensemble: if following { ensembleIDs.insert(id) } else { ensembleIDs.remove(id) }
        case .venue: if following { venueIDs.insert(id) } else { venueIDs.remove(id) }
        case .work: break
        }
    }
}

/// App-weit als EnvironmentObject verfügbar (siehe RootTabView), damit
/// ReportContentLink auf Detailseiten (Event/Person/Ensemble/Venue) nicht
/// auth/UserRepository durch jede Zwischenansicht (SearchView, VenueMapView
/// etc.) durchreichen muss.
@MainActor
final class ReportStore: ObservableObject {
    let auth: AuthStore
    let repository: UserRepository?

    init(auth: AuthStore, repository: UserRepository?) {
        self.auth = auth
        self.repository = repository
    }
}
