import SwiftUI

struct RootTabView: View {
    @Environment(\.scenePhase) private var scenePhase
    let environment: AppEnvironment

    @State private var selection: AppTab = .home
    // Ohne dieses @ObservedObject würde RootTabView.body nie neu ausgewertet,
    // wenn sich der Auth-Zustand ändert — .onChange(of: auth.userID) unten
    // bräuchte dafür eine body-Neuauswertung als Auslöser, die environment
    // als reines `let` sonst nicht liefert.
    @ObservedObject private var auth: AuthStore
    @StateObject private var favorites: FavoriteStore
    @StateObject private var follows: FollowStore
    @StateObject private var reportStore: ReportStore
    @StateObject private var cityStore: CityStore
    @StateObject private var genreFilterRouter = GenreFilterRouter()
    @AppStorage("didCompleteOnboarding") private var didCompleteOnboarding = false
    @State private var showsOnboarding = false
    // Generated by Claude Code — App startet unabhängig vom System-Modus
    // immer hell; "appearance" bleibt aber jederzeit über die
    // Profil-Einstellung auf "system"/"dark" umstellbar.
    @AppStorage("appearance") private var appearance = "light"
    @AppStorage(BiometricAuth.enabledStorageKey) private var biometricProtectionEnabled = false
    @State private var isBiometricUnlocked = !BiometricAuth.isEnabled
    @State private var isAuthenticatingBiometrics = false
    @State private var showsCoach = false
    @ObservedObject private var attendanceMonitor = AttendanceLocationMonitor.shared

    init(environment: AppEnvironment) {
        self.environment = environment
        _selection = State(initialValue: ProcessInfo.processInfo.environment["KLANGRADAR_MARKETING_CAPTURE"] == "1" ? .profile : .home)
        _auth = ObservedObject(wrappedValue: environment.auth)
        _favorites = StateObject(wrappedValue: FavoriteStore(auth: environment.auth, repository: environment.restClient.map(UserRepository.init(client:))))
        _follows = StateObject(wrappedValue: FollowStore(auth: environment.auth, repository: environment.restClient.map(UserRepository.init(client:))))
        _reportStore = StateObject(wrappedValue: ReportStore(auth: environment.auth, repository: environment.restClient.map(UserRepository.init(client:))))
        _cityStore = StateObject(wrappedValue: CityStore(auth: environment.auth, repository: environment.restClient.map(UserRepository.init(client:))))
    }

    var body: some View {
        TabView(selection: $selection) {
            HomeView(
                repository: environment.events,
                contentRepository: environment.content,
                usesPreviewData: environment.isUsingPreviewData,
                auth: environment.auth,
                userRepository: environment.restClient.map(UserRepository.init(client:))
            )
            // Vorher .id(auth.userID) — zerstört und baut HomeViews komplette
            // NavigationStack neu auf, sobald sich die User-ID ändert (z. B.
            // Session-Wiederherstellung kurz nach dem Start). Genau dieser
            // Rebuild mitten im ersten Layout-Durchlauf verursacht einen
            // reproduzierbaren Absturz: "Layout requested for visible
            // navigation bar ... top item belongs to a different navigation
            // bar" (zwei UINavigationBar-Instanzen kurzzeitig gleichzeitig
            // aktiv). HomeViewModel reagiert bereits selbst per Combine auf
            // auth?.$state (siehe authCancellable in HomeViewModel.init) und
            // lädt bei Bedarf in-place neu — kein View-Rebuild nötig.
            .tag(AppTab.home)
            .tabItem {
                Label("Home", systemImage: "house")
            }



            SearchView(
                eventRepository: environment.events,
                contentRepository: environment.content
            )
                .tag(AppTab.search)
                .tabItem {
                    Label("Suche", systemImage: "magnifyingglass")
                }

            VenueMapView(repository: environment.content, eventRepository: environment.events, cityStore: cityStore)
                .tag(AppTab.map)
                .tabItem {
                    Label("Karte", systemImage: "map")
                }

            EventCalendarView(
                repository: environment.events,
                contentRepository: environment.content,
                auth: environment.auth,
                userRepository: environment.restClient.map(UserRepository.init(client:))
            )
                .tag(AppTab.calendar)
                .tabItem {
                    Label("Kalender", systemImage: "calendar")
                }

            ProfileView(
                usesPreviewData: environment.isUsingPreviewData,
                auth: environment.auth,
                userRepository: environment.restClient.map(UserRepository.init(client:)),
                editorialRepository: environment.restClient.map(EditorialRepository.init(client:)),
                eventRepository: environment.events,
                contentRepository: environment.content
            )
                .tag(AppTab.profile)
                .tabItem {
                    Label("Profil", systemImage: "person")
                }
        }
        .environmentObject(favorites)
        .environmentObject(follows)
        .environmentObject(reportStore)
        .environmentObject(genreFilterRouter)
        .environmentObject(cityStore)
        .overlay(alignment: .bottomTrailing) {
            if selection == .home, environment.restClient != nil, !shouldShowBiometricLock {
                Button {
                    showsCoach = true
                } label: {
                    Image("KlangradarLogo")
                        .resizable()
                        .scaledToFill()
                        .frame(width: 56, height: 56)
                        .clipShape(.rect(cornerRadius: 17, style: .continuous))
                        .overlay {
                            RoundedRectangle(cornerRadius: 17, style: .continuous)
                                .stroke(.white.opacity(0.76), lineWidth: 1)
                        }
                        .shadow(color: .black.opacity(0.16), radius: 11, y: 5)
                }
                .buttonStyle(RootCoachButtonStyle())
                .accessibilityLabel("Klangradar KI öffnen")
                .accessibilityHint("Öffnet die persönliche Klangradar KI in einer halbhohen Ansicht")
                .padding(.trailing, 18)
                .padding(.bottom, 88)
                .transition(.opacity.combined(with: .scale(scale: 0.96, anchor: .bottomTrailing)))
                .zIndex(20)
            }
        }
        .onChange(of: genreFilterRouter.pending) { _, pending in
            if pending != nil { selection = .search }
        }
        .task {
            await auth.bootstrap()
            await refreshOnboardingGate()
            await unlockWithBiometricsIfNeeded()
        }
        .onChange(of: auth.userID) { _, _ in
            Task {
                await refreshOnboardingGate()
                await favorites.load()
                await follows.load()
                await cityStore.load()
                await attendanceMonitor.refresh()
            }
        }
        .task { await favorites.load() }
        .task { await follows.load() }
        .task { await cityStore.load() }
        .task {
            // Nutzerwunsch: automatische, standortbasierte Erkennung "warst
            // du bei diesem gemerkten Konzert?" — läuft passiv im
            // Hintergrund (Geofencing), markiert nie selbstständig, fragt
            // immer per eigenem Popup nach (siehe AttendanceLocationMonitor,
            // .sheet unten). requestAlwaysAuthorizationIfNeeded() ist ein
            // No-Op, solange der Zugriff bereits "Immer" ist oder verweigert
            // wurde — kein wiederholtes Nachfragen.
            attendanceMonitor.configure(repository: environment.restClient.map(UserRepository.init(client:)), auth: auth)
            attendanceMonitor.requestAlwaysAuthorizationIfNeeded()
            await attendanceMonitor.refresh()
        }
        .sheet(item: $attendanceMonitor.pendingConfirmation) { pending in
            AttendanceConfirmationPrompt(eventTitle: pending.title) { accepted in
                Task { await attendanceMonitor.confirmPendingAttendance(accepted: accepted) }
            }
            .presentationDetents([.height(260)])
        }
        .fullScreenCover(isPresented: $showsOnboarding) {
            OnboardingView(
                auth: auth,
                repository: environment.restClient.map(UserRepository.init(client:))
            ) {
                didCompleteOnboarding = true
                showsOnboarding = false
            }
            // Generated by Claude Code — FollowCategoryStepView (Onboarding-
            // Schritt "Folgen") liest FollowStore per @EnvironmentObject;
            // ohne explizites Reattach hier stürzt die App beim Erreichen
            // dieses Schritts mit "No ObservableObject of type FollowStore
            // found" ab, weil fullScreenCover-Inhalte das .environmentObject
            // der präsentierenden View nicht zuverlässig erben.
            .environmentObject(follows)
        }
        .sheet(isPresented: $auth.isCompletingPasswordRecovery) {
            PasswordResetCompletionView(auth: auth)
        }
        .sheet(isPresented: $showsCoach) {
            if let repository = environment.restClient.map(UserRepository.init(client:)) {
                NavigationStack {
                    KlangradarCoachView(
                        auth: auth,
                        repository: repository,
                        eventRepository: environment.events,
                        contentRepository: environment.content,
                        startsInChat: true,
                        showsDismissButton: true
                    )
                }
                // KlangradarCoachView liest @EnvironmentObject CityStore (für
                // die Stadt-Vorgabe an die KI) — .sheet()-Inhalte erben die
                // Environment-Objects der präsentierenden View NICHT
                // zuverlässig (gleiches Muster wie FollowStore beim
                // fullScreenCover oben). Ohne dieses Reattach stürzt die
                // App beim Öffnen der Klangradar KI zuverlässig mit
                // "No ObservableObject of type CityStore found" ab.
                .environmentObject(favorites)
                .environmentObject(cityStore)
                .presentationCornerRadius(28)
                // Nutzerfeedback (mehrfach): auf iPad blieb links/rechts ein
                // Rand, Hintergrund sichtbar — sowohl bei .presentationSizing
                // (.page) mit Detents (Detents erzwingen dort die
                // freischwebende "Form"-Karte, Sizing wird ignoriert) als
                // auch beim früheren Verzicht auf Detents (dann keine
                // ziehbare Halbhöhe mehr). Die eigentlich richtige Lösung:
                // .page.fitted(horizontal: false, vertical: true) — "page"
                // füllt die Breite kantenbündig, "fitted(vertical: true)"
                // lässt NUR die Höhe dem gewählten Detent folgen. Funktioniert
                // size-class-unabhängig, kein Branching mehr nötig.
                .modifier(CoachSheetPresentation())
            }
        }
        .alert("Link konnte nicht geöffnet werden", isPresented: callbackErrorBinding) {
            Button("OK", role: .cancel) { auth.callbackErrorMessage = nil }
        } message: {
            Text(auth.callbackErrorMessage ?? "Bitte fordere einen neuen Link an.")
        }
        .onOpenURL { url in
            if url.scheme == AuthService.callbackScheme, url.host == "auth-callback" {
                showsOnboarding = false
                Task { await auth.handleAuthCallback(url) }
                return
            }
            let path = url.path.lowercased()
            if path.contains("search") { selection = .search }
            else if path.contains("map") || path.contains("venue") { selection = .map }
            else if path.contains("calendar") { selection = .calendar }
            else if path.contains("profile") || path.contains("admin") { selection = .profile }
            else { selection = .home }
        }
        .preferredColorScheme(preferredColorScheme)
        .overlay {
            if shouldShowBiometricLock {
                BiometricLockView(isAuthenticating: isAuthenticatingBiometrics) {
                    Task { await unlockWithBiometricsIfNeeded() }
                }
                .transition(.opacity)
                .zIndex(100)
            }
        }
        .onChange(of: scenePhase) { _, phase in
            if phase == .background, biometricProtectionEnabled, case .authenticated = auth.state {
                isBiometricUnlocked = false
            } else if phase == .active {
                Task {
                    await unlockWithBiometricsIfNeeded()
                    await attendanceMonitor.refresh()
                }
            }
        }
        .onChange(of: biometricProtectionEnabled) { _, enabled in
            isBiometricUnlocked = !enabled
            if enabled { Task { await unlockWithBiometricsIfNeeded() } }
        }
    }

    private var callbackErrorBinding: Binding<Bool> {
        Binding(
            get: { auth.callbackErrorMessage != nil },
            set: { if !$0 { auth.callbackErrorMessage = nil } }
        )
    }

    private var shouldShowBiometricLock: Bool {
        guard case .authenticated = auth.state else { return false }
        return biometricProtectionEnabled && !isBiometricUnlocked
    }

    @MainActor
    private func unlockWithBiometricsIfNeeded() async {
        guard shouldShowBiometricLock, !isAuthenticatingBiometrics else { return }
        isAuthenticatingBiometrics = true
        defer { isAuthenticatingBiometrics = false }
        if (try? await BiometricAuth.authenticate(reason: "Klangradar entsperren")) == true {
            withAnimation(.easeOut(duration: 0.2)) { isBiometricUnlocked = true }
        }
    }

    private var preferredColorScheme: ColorScheme? {
        switch appearance { case "light": .light; case "dark": .dark; default: nil }
    }

    /// Zeigt das Onboarding, solange es lokal noch nie durchlaufen wurde
    /// (Gast-Skip zählt hier auch — "Ohne Account fortfahren" beendet den
    /// Flow), UND zusätzlich immer dann, wenn ein echter (nicht-anonymer)
    /// Account existiert, dessen `profiles.onboarding_completed` serverseitig
    /// noch nicht gesetzt ist — deckt Neuinstall/anderes Gerät mit
    /// bestehendem Account ab, ohne den lokalen Gast-Skip zu verlieren.
    private func refreshOnboardingGate() async {
        guard !auth.isCompletingPasswordRecovery else {
            showsOnboarding = false
            return
        }
        guard
            case .authenticated = auth.state,
            let userID = auth.userID,
            let token = auth.accessToken,
            let repository = environment.restClient.map(UserRepository.init(client:))
        else {
            showsOnboarding = !didCompleteOnboarding
            return
        }
        let completed = (try? await repository.isOnboardingCompleted(userID: userID, token: token)) ?? true
        // Ein bestehender Nutzer, der sich bewusst aus dem Profil anmeldet,
        // darf nicht zurück in den Registrierungsflow gezwungen werden. Das
        // serverseitige Flag hilft nur auf einer frischen Installation; ein
        // lokal bereits abgeschlossenes (auch als Gast übersprungenes)
        // Onboarding hat Vorrang.
        showsOnboarding = !didCompleteOnboarding && !completed
    }
}

// Erzwingt kantenbündiges Sheet-Sizing (kein "Form"-Rand auf iPad) ab iOS 18,
// unverändertes Verhalten darunter — .presentationSizing(_:) existiert erst
// ab iOS 18, ein reiner `if #available`-Ausdruck als ViewModifier-Body lässt
// sich nicht direkt inline in eine Modifier-Kette schreiben, deshalb als
// eigener Typ.
private struct CoachSheetPresentation: ViewModifier {
    func body(content: Content) -> some View {
        if #available(iOS 18.0, *) {
            content
                .presentationSizing(.page.fitted(horizontal: false, vertical: true))
                .presentationDetents([.medium, .large])
                .presentationDragIndicator(.visible)
                .presentationBackgroundInteraction(.enabled(upThrough: .medium))
        } else {
            content
                .presentationDetents([.medium, .large])
                .presentationDragIndicator(.visible)
                .presentationBackgroundInteraction(.enabled(upThrough: .medium))
        }
    }
}

private struct RootCoachButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .scaleEffect(configuration.isPressed ? 0.96 : 1)
            .opacity(configuration.isPressed ? 0.9 : 1)
            .animation(.easeOut(duration: 0.14), value: configuration.isPressed)
    }
}

private struct BiometricLockView: View {
    let isAuthenticating: Bool
    let retry: () -> Void

    var body: some View {
        ZStack {
            Color(uiColor: .systemBackground).ignoresSafeArea()
            VStack(spacing: 18) {
                Image(systemName: BiometricAuth.availableBiometryKind == .touchID ? "touchid" : "faceid")
                    .font(.system(size: 48, weight: .regular))
                    .foregroundStyle(KlangradarTheme.accent)
                Text("Klangradar ist geschützt")
                    .font(.title2.bold())
                Text("Authentifiziere dich, um fortzufahren.")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
                Button("Entsperren", systemImage: "lock.open") { retry() }
                    .buttonStyle(.borderedProminent)
                    .controlSize(.large)
                    .disabled(isAuthenticating)
            }
            .padding(32)
        }
    }
}

private enum AppTab: Hashable {
    case home
    case search
    case map
    case calendar
    case profile
}
