"use client";

import * as React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import {
  LayoutDashboard,
  CalendarDays,
  Users,
  Megaphone,
  BadgeCheck,
  Plus,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

export type NavItem = { href: string; label: string };
export type NavGroup = { label: string; icon: LucideIcon; items: NavItem[] };

// Flat-White-Redesign (Generated by Claude Code, Okt. 2026): acht Gruppen,
// davon vier mit nur einem Eintrag, zu vier Arbeitsbereichen gebündelt —
// "Übersicht", "Programm", "Reichweite" (Promotion + Auswertung),
// "Organisation" (Team, Agentur, Finanzen, Bibliothek). Alle Seiten und Pfade
// bleiben erhalten; "Termin anlegen" sitzt als Hauptaktion ganz oben,
// "Neue Entität beanspruchen" als Nebenaktion unten (siehe Layout).
export const NAV_GROUPS: NavGroup[] = [
  {
    label: "Übersicht",
    icon: LayoutDashboard,
    items: [
      { href: "/veranstalter", label: "Dashboard" },
      { href: "/veranstalter/postfach", label: "Postfach" },
    ],
  },
  {
    label: "Programm",
    icon: CalendarDays,
    items: [
      { href: "/veranstalter/events", label: "Meine Events" },
      { href: "/veranstalter/events/discover", label: "Entdecken" },
      { href: "/veranstalter/serien", label: "Serien" },
    ],
  },
  {
    label: "Reichweite",
    icon: Megaphone,
    items: [
      { href: "/veranstalter/promote", label: "Push & Promote" },
      { href: "/veranstalter/marketing", label: "Marketing-Tools" },
      { href: "/veranstalter/analytics", label: "Analytics" },
    ],
  },
  {
    label: "Organisation",
    icon: Users,
    items: [
      { href: "/veranstalter/team", label: "Mitglieder & Rollen" },
      { href: "/veranstalter/agentur", label: "Agentur" },
      { href: "/veranstalter/finanzen", label: "Finanzen" },
      { href: "/veranstalter/bibliothek", label: "Bibliothek" },
    ],
  },
];

// Genauester Treffer statt jedes Präfixes — sonst waren auf
// /veranstalter/events/discover "Meine Events" UND "Entdecken" aktiv.
function activeHrefFor(pathname: string): string | null {
  let best: string | null = null;
  for (const item of NAV_GROUPS.flatMap((group) => group.items)) {
    const matches = item.href === "/veranstalter"
      ? pathname === "/veranstalter"
      : pathname === item.href || pathname.startsWith(`${item.href}/`);
    if (matches && (!best || item.href.length > best.length)) best = item.href;
  }
  return best;
}

export function SidebarNavigation({ onNavigate }: { onNavigate?: () => void }) {
  const pathname = usePathname();
  const activeHref = activeHrefFor(pathname);

  return (
    <nav aria-label="Veranstalterportal" className="flex flex-1 flex-col gap-5 overflow-y-auto px-3 pb-4">
      <Link
        href="/veranstalter/events/new"
        onClick={onNavigate}
        className="mx-0.5 flex h-10 items-center justify-center gap-2 rounded-lg bg-[#2D2A6E] text-[13.5px] font-medium text-white hover:bg-[#1F1D52]"
      >
        <Plus className="size-4" aria-hidden="true" />
        Termin anlegen
      </Link>
      {NAV_GROUPS.map((group) => (
        <div key={group.label} className="flex flex-col gap-px">
          <div className="flex items-center gap-2 px-2.5 pb-1.5 text-[12px] font-medium text-[#6B6B6B]">
            <group.icon className="size-3.5" aria-hidden="true" />
            {group.label}
          </div>
          {group.items.map((item) => {
            const active = item.href === activeHref;
            return (
              <Link
                key={item.href}
                href={item.href}
                onClick={onNavigate}
                aria-current={active ? "page" : undefined}
                className={cn("dashboard-nav-item text-[13.5px]", active && "dashboard-nav-item-active")}
              >
                {item.label}
              </Link>
            );
          })}
        </div>
      ))}
      <div className="mt-auto border-t border-[#EAEAEA] pt-3">
        <Link
          href="/veranstalter/claim"
          onClick={onNavigate}
          aria-current={activeHref === null && pathname.startsWith("/veranstalter/claim") ? "page" : undefined}
          className={cn("dashboard-nav-item text-[13.5px]", pathname.startsWith("/veranstalter/claim") && "dashboard-nav-item-active")}
        >
          <span className="flex items-center gap-2">
            <BadgeCheck className="size-4" aria-hidden="true" />
            Profil beanspruchen
          </span>
        </Link>
      </div>
    </nav>
  );
}
