import SwiftUI

/// Generated by Claude Code — vorher gab es beim Onboarding-Schritt "AGB
/// akzeptieren" keine Möglichkeit, die AGB tatsächlich zu lesen (der Button
/// hieß "Impressum (AGB)", öffnete aber nur ImpressumView ohne AGB-Inhalt).
/// Rechtlich fragwürdig: eine Checkbox-Zustimmung zu einem nicht einsehbaren
/// Text ist keine wirksame Einwilligung. Text synchron mit
/// docs/legal/agb.md halten (siehe dortiger ENTWURF-Hinweis).
struct AGBView: View {
    var body: some View {
        List {
            Section {
                Text("Entwurf, noch nicht anwaltlich geprüft. Vollständiger Text: docs/legal/agb.md")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            Section("1. Geltungsbereich") {
                Text("Diese AGB gelten für die Nutzung der App „Klangradar“, angeboten von Jakob Liess, Gabelsbergerstraße 6, 80333 München.")
            }

            Section("2. Leistungsbeschreibung") {
                Text("Die App aggregiert Informationen zu Veranstaltungen der klassischen Musik, Chor-, Vokal-, Kirchen- und Orchestermusik und stellt Such-, Karten- und Merkfunktionen bereit. Veranstaltungsdaten stammen teilweise aus strukturierten Schnittstellen und teilweise aus automatisiertem Abruf öffentlich zugänglicher Veranstalter-Websites.")
            }

            Section("3. Kein Vertragspartner für Ticketkäufe") {
                Text("Wir verkaufen selbst keine Tickets. Ein etwaiger Kaufvertrag kommt ausschließlich zwischen Nutzer:in und dem jeweiligen Veranstalter/Ticketanbieter zustande.")
            }

            Section("4. Registrierung") {
                Text("Für bestimmte Funktionen ist eine Registrierung per E-Mail erforderlich. Angaben müssen wahrheitsgemäß sein.")
            }

            Section("5. Haftungsausschluss für Veranstaltungsdaten") {
                Text("Termine, Preise, Verfügbarkeiten und Ortsangaben können veraltet, unvollständig oder fehlerhaft sein. Maßgeblich sind stets die Angaben des jeweiligen Veranstalters.")
            }

            Section("6. Kündigung / Kontolöschung") {
                Text("Konten können jederzeit in den App-Einstellungen gelöscht werden.")
            }

            Section("7. Schlussbestimmungen") {
                Text("Es gilt deutsches Recht.")
            }
        }
        .navigationTitle("AGB")
        .navigationBarTitleDisplayMode(.inline)
    }
}

#Preview {
    NavigationStack { AGBView() }
}
