import SwiftUI

/// Generated by Claude Code — ersetzt den vorherigen externen Link auf
/// "https://klangradar.app/datenschutz" (falsche Domain, die App läuft
/// unter klangradar.com — der Link führte damit ins Leere). Zeigt den Text
/// jetzt wie ImpressumView direkt in der App an. Text synchron mit
/// docs/legal/datenschutzerklaerung.md halten (siehe dortiger
/// ENTWURF-Hinweis).
struct DatenschutzView: View {
    var body: some View {
        List {
            Section {
                Text("Entwurf, noch nicht anwaltlich geprüft. Vollständiger Text: docs/legal/datenschutzerklaerung.md")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            Section("1. Verantwortlicher") {
                Text("Jakob Liess, Gabelsbergerstraße 6, 80333 München, jakob@klangradar.com (siehe Impressum).")
            }

            Section("2. Welche Daten wir verarbeiten") {
                VStack(alignment: .leading, spacing: 8) {
                    Text("• E-Mail-Adresse, Passwort-Hash: Konto/Login")
                    Text("• Standortdaten (bei Erlaubnis): Kartenansicht, Standort-Check-in bei Konzertbesuchen")
                    Text("• Push-Token: Benachrichtigungen zu Konzerten")
                    Text("• Suchhistorie (eingeloggt): persönliche Empfehlungen")
                    Text("• Interessen/Präferenzen: personalisierte Empfehlungen")
                }
            }

            Section("3. Empfänger / Auftragsverarbeiter") {
                Text("Supabase (Datenbank-, Auth- und Storage-Hosting). Bei aktivierter Anmeldung mit Apple/Google: der jeweilige Anbieter.")
            }

            Section("4. Standortdaten") {
                Text("Der Standort wird nicht dauerhaft gespeichert. Beim Besuchs-Check-in wird die Distanz zur Spielstätte nur im Moment der Anfrage berechnet, gespeichert wird lediglich das Ergebnis (besucht: ja/verifiziert per Standort), keine Koordinate.")
            }

            Section("5. Betroffenenrechte") {
                Text("Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch sowie Recht auf Beschwerde bei einer Aufsichtsbehörde. Anfragen an jakob@klangradar.com.")
            }

            Section("6. Widerruf von Einwilligungen") {
                Text("Standortfreigabe und Push-Benachrichtigungen können jederzeit in den Geräte- bzw. App-Einstellungen widerrufen werden.")
            }
        }
        .navigationTitle("Datenschutz")
        .navigationBarTitleDisplayMode(.inline)
    }
}

#Preview {
    NavigationStack { DatenschutzView() }
}
