import SwiftUI

/// Aus ProfileView.swift extrahiert, damit dieselbe Ansicht sowohl von
/// Profil → Interessen (per NavigationLink, mit eigenem Navigationstitel)
/// als auch als eingebetteter Onboarding-Schritt (ohne umgebenden
/// NavigationStack — `.navigationTitle` bleibt dort einfach wirkungslos)
/// verwendet werden kann, ohne die Interessen-Logik zu duplizieren.
struct InterestsView: View {
    @ObservedObject var auth: AuthStore
    let repository: UserRepository?
    /// Onboarding-Schritt "Interessen" zeigt bewusst nur Genres — Werke
    /// entfallen dort komplett, Personen/Ensembles/Venues bekommen eigene
    /// Folgen-Schritte (siehe FollowCategoryStepView). Ohne Vorgabe (Profil
    /// → Interessen) bleibt der volle Kategorie-Umschalter wie bisher.
    var fixedCategory: InterestCategory? = nil
    @State private var category: InterestCategory = .genre
    @State private var options: [InterestOption] = []
    @State private var selected: Set<String> = []
    @State private var searchText = ""

    private var filteredOptions: [InterestOption] {
        searchText.isEmpty ? options : options.filter { $0.label.localizedStandardContains(searchText) }
    }

    private var showsThumbnails: Bool {
        category == .person || category == .ensemble || category == .venue
    }

    private var entityKind: EntityKind {
        switch category {
        case .person: .person
        case .ensemble: .ensemble
        case .venue: .venue
        case .genre, .work: .work
        }
    }

    var body: some View {
        if fixedCategory != nil {
            onboardingChipBody
        } else {
            settingsListBody
        }
    }

    /// Generated by Claude Code — Genres im Onboarding waren volle
    /// List-Zeilen (Radio-Kreis + Trennlinie), Nutzerfeedback: "zu groß"
    /// und "zu sehr im Stil einer Liste". Jetzt ein fließendes Chip-Grid
    /// (ausgewählt = gefüllt) statt einer Liste — Profil → Interessen
    /// bleibt unverändert die vollständige, kategorisierte Liste.
    private var onboardingChipBody: some View {
        ScrollView {
            VStack(spacing: 16) {
                OnboardingSearchField(prompt: "\(category.title) durchsuchen", text: $searchText)
                FlowLayout(spacing: 10) {
                    ForEach(filteredOptions) { option in
                        let isSelected = selected.contains(option.id)
                        Button { toggle(option.id) } label: {
                            Text(option.label)
                                .font(.subheadline.weight(.medium))
                                .padding(.horizontal, 16)
                                .padding(.vertical, 10)
                                .background(isSelected ? KlangradarTheme.accent : Color(.secondarySystemBackground), in: .capsule)
                                .foregroundStyle(isSelected ? .white : .primary)
                        }
                        .buttonStyle(.plain)
                    }
                }
            }
            .padding(.horizontal, 20)
            .padding(.top, 12)
            .padding(.bottom, 12)
        }
        .scrollDismissesKeyboard(.interactively)
        .onAppear { if let fixedCategory { category = fixedCategory } }
        .task(id: category) { searchText = ""; await load() }
    }

    private var settingsListBody: some View {
        List {
            Section {
                ScrollView(.horizontal) {
                    HStack(spacing: 10) {
                        ForEach(InterestCategory.allCases, id: \.self) { item in
                            Button { category = item } label: {
                                Label(item.title, systemImage: item.systemImage)
                                    .padding(.horizontal, 12).padding(.vertical, 8)
                                    .background(category == item ? KlangradarTheme.accent : Color.secondary.opacity(0.12), in: .capsule)
                                    .foregroundStyle(category == item ? .white : .primary)
                            }.buttonStyle(.plain)
                        }
                    }
                }.scrollIndicators(.hidden)
            }
            Section("\(category.title) · \(selected.count) ausgewählt") {
                ForEach(filteredOptions) { option in
                    Button { toggle(option.id) } label: {
                        HStack(spacing: 12) {
                            if showsThumbnails { InterestOptionThumbnail(option: option, kind: entityKind) }
                            Text(option.label).foregroundStyle(.primary)
                            Spacer()
                            Image(systemName: selected.contains(option.id) ? "checkmark.circle.fill" : "circle")
                                .font(.system(size: 28, weight: .regular))
                                .frame(width: 44, height: 44)
                                .foregroundStyle(selected.contains(option.id) ? KlangradarTheme.accent : .secondary)
                        }
                    }
                }
            }
        }
        .navigationTitle("Interessen")
        .searchable(text: $searchText, prompt: "\(category.title) durchsuchen")
        .task(id: category) { searchText = ""; await load() }
    }

    private func load() async {
        guard let repository else { return }
        options = (try? await repository.interestOptions(category)) ?? []
        guard let id = auth.userID, let token = auth.accessToken else { return }
        selected = (try? await repository.selectedInterests(category, userID: id, token: token)) ?? []
    }

    private func toggle(_ id: String) {
        guard let repository, let userID = auth.userID, let token = auth.accessToken else { return }
        let newValue = !selected.contains(id)
        if newValue { selected.insert(id) } else { selected.remove(id) }
        Task { try? await repository.setInterest(category, id: id, selected: newValue, userID: userID, token: token) }
    }
}
