// Inhalte für die App-Simulationen auf klangradar.com (Generated by Claude
// Code, Okt. 2026). Alle Termine, Orte und Mitwirkenden sind echte Einträge
// aus der Klangradar-Datenbank (Stand 10.10.2026); Bilder sind dieselben,
// die auch die App zu diesen Einträgen zeigt.
export const APP_ACCENT = "#146194";

const RATTLE_PHOTO =
  "https://zqgzcspeqllrihfwmayn.supabase.co/storage/v1/object/public/entity-photos/person/c9c444b3-f867-4fc5-bce1-d0a0d6dd097e/4e02c101-4324-4f86-8823-bdef75b024f9.jpg";
const HADELICH_PHOTO =
  "https://zqgzcspeqllrihfwmayn.supabase.co/storage/v1/object/public/ingested-images/person/2ff2cfa4-3e65-47c2-b921-8c1815df47a1.webp";

export type FeedEvent = { title: string; when: string; venue: string; image: string };

export const FEED_EVENTS: FeedEvent[] = [
  {
    title: "Ariadne auf Naxos",
    when: "Mo., 12. Okt. 19:00",
    venue: "Nationaltheater",
    image: "https://www.staatsoper.de/media/_processed_/9/0/csm_Ariadne_HEader_f62de06d45.jpg",
  },
  {
    title: "Sir Simon Rattle & Isabelle Faust",
    when: "Do., 15. Okt. 20:00",
    venue: "Herkulessaal",
    image: "https://www.brso.de/wp-content/uploads/sites/2/16-9-faust-isabelle-c-felix-broede.jpg",
  },
  {
    title: "Lucrezia Borgia",
    when: "So., 18. Okt. 18:00",
    venue: "Nationaltheater",
    image: "https://www.staatsoper.de/media/_processed_/6/a/csm_Header_Lucrezia_Borgia_21zu9_8ee6c8def3.png",
  },
  {
    title: "Simone Young & Augustin Hadelich",
    when: "Do., 22. Okt. 20:00",
    venue: "Herkulessaal",
    image: "https://www.brso.de/wp-content/uploads/sites/2/16-9-young-simone-c-sandrah-steh.jpg",
  },
  {
    title: "Un ballo in maschera",
    when: "Sa., 31. Okt. 19:00",
    venue: "Nationaltheater",
    image: "https://www.staatsoper.de/media/_processed_/b/5/csm_Ballo_21zu9_2146aa4264.jpg",
  },
  {
    title: "La Bohème",
    when: "Fr., 13. Nov. 19:00",
    venue: "Nationaltheater",
    image: "https://www.staatsoper.de/media/_processed_/2/4/csm_La_boheme_72840010df.png",
  },
];

export const HERO_EVENT = {
  title: "Die Kameliendame",
  label: "HEUTE · 19:30",
  venue: "Nationaltheater München",
  image:
    "https://www.staatsoper.de/media/_processed_/9/6/csm_Kameliendame_Feyferlik_Summerscales_Homepage-3840x2160px_f504977eca.jpg",
};

export const DETAIL_EVENT = {
  title: "Sir Simon Rattle & Isabelle Faust",
  date: "Donnerstag, 15. Oktober 2026, 20:00",
  venue: "Herkulessaal der Residenz",
  ensemble: "Symphonieorchester des Bayerischen Rundfunks",
  image: "https://www.brso.de/wp-content/uploads/sites/2/16-9-faust-isabelle-c-felix-broede.jpg",
  people: [
    { name: "Sir Simon Rattle", role: "Dirigent", photo: RATTLE_PHOTO },
    { name: "Isabelle Faust", role: "Violine", photo: "https://www.brso.de/wp-content/uploads/sites/2/16-9-faust-isabelle-c-felix-broede.jpg" },
  ],
};

export const ARTIST = {
  name: "Sir Simon Rattle",
  role: "Dirigent",
  photo: RATTLE_PHOTO,
  upcoming: [
    { day: "15", month: "Okt", title: "Sir Simon Rattle & Isabelle Faust", meta: "Do. 20:00 · Herkulessaal" },
    { day: "07", month: "Nov", title: "Symphonieorchester des BR: Sir Simon Rattle", meta: "Sa. 19:00 · Isarphilharmonie" },
    { day: "28", month: "Feb", title: "Pelléas et Mélisande", meta: "So. 18:00 · Isarphilharmonie" },
    { day: "06", month: "Mai", title: "Mahler 10", meta: "Do. 20:00 · Herkulessaal" },
  ],
};

export const ALSO_PHOTOS = { hadelich: HADELICH_PHOTO };
