/* eslint-disable @next/next/no-img-element */
import type { ReactNode } from "react";

// iPhone-Rahmen für Screenshots und Simulationen der nativen App (Generated by
// Claude Code). Bildschirm-Inhalte werden in echter iPhone-Breite (402 pt)
// gestaltet und dann skaliert, damit Schriftgrößen und Abstände der App 1:1
// stimmen.
const SCREEN_W = 402;
const SCREEN_H = 874;
const BEZEL = 10;

export function PhoneFrame({
  width = 300,
  children,
  className = "",
  label,
}: {
  width?: number;
  children: ReactNode;
  className?: string;
  label: string;
}) {
  const inner = width - BEZEL * 2;
  const scale = inner / SCREEN_W;
  const innerHeight = SCREEN_H * scale;
  return (
    <figure
      aria-label={label}
      className={`relative shrink-0 bg-[#0c0c0d] ${className}`}
      style={{ width, height: innerHeight + BEZEL * 2, padding: BEZEL, borderRadius: width * 0.17 }}
    >
      <div className="relative overflow-hidden bg-white" style={{ width: inner, height: innerHeight, borderRadius: width * 0.145 }}>
        <div style={{ width: SCREEN_W, height: SCREEN_H, transform: `scale(${scale})`, transformOrigin: "top left" }}>{children}</div>
      </div>
    </figure>
  );
}

/** Echter App-Screenshot (enthält Statusleiste und Dynamic Island bereits). */
export function Screenshot({ src, alt, eager = false }: { src: string; alt: string; eager?: boolean }) {
  return (
    <img
      src={src}
      alt={alt}
      width={SCREEN_W}
      height={SCREEN_H}
      className="block h-full w-full object-cover"
      loading={eager ? "eager" : "lazy"}
    />
  );
}

/** Statusleiste + Dynamic Island für nachgebaute Bildschirme. */
export function StatusBar({ light = false }: { light?: boolean }) {
  const color = light ? "#ffffff" : "#000000";
  return (
    <div className="absolute inset-x-0 top-0 z-20 flex h-[54px] items-center justify-between px-[34px] pt-[6px]" aria-hidden="true">
      <span style={{ color, font: "600 17px -apple-system, 'SF Pro Text', system-ui, sans-serif" }}>9:41</span>
      <span className="absolute left-1/2 top-[11px] h-[37px] w-[124px] -translate-x-1/2 rounded-full bg-black" />
      <span className="flex items-center gap-[6px]">
        <svg width="18" height="12" viewBox="0 0 18 12" fill={color}>
          <rect x="0" y="8" width="3" height="4" rx="1" />
          <rect x="5" y="5.5" width="3" height="6.5" rx="1" />
          <rect x="10" y="3" width="3" height="9" rx="1" />
          <rect x="15" y="0" width="3" height="12" rx="1" />
        </svg>
        <svg width="16" height="12" viewBox="0 0 16 12" fill={color}>
          <path d="M8 2.2c2.3 0 4.4.9 6 2.4l1.3-1.4A10.5 10.5 0 0 0 8 .2 10.5 10.5 0 0 0 .7 3.2L2 4.6a8.5 8.5 0 0 1 6-2.4Zm0 3.8c1.3 0 2.5.5 3.4 1.3l1.4-1.4A6.7 6.7 0 0 0 8 4a6.7 6.7 0 0 0-4.8 1.9l1.4 1.4C5.5 6.5 6.7 6 8 6Zm0 3.6c-.6 0-1.1.2-1.5.6L8 11.8l1.5-1.6c-.4-.4-.9-.6-1.5-.6Z" />
        </svg>
        <svg width="27" height="13" viewBox="0 0 27 13" fill="none">
          <rect x="0.5" y="0.5" width="23" height="12" rx="3.8" stroke={color} strokeOpacity="0.4" />
          <rect x="2" y="2" width="20" height="9" rx="2.5" fill={color} />
          <path d="M25 4.5v4c.8-.3 1.3-1.1 1.3-2s-.5-1.7-1.3-2Z" fill={color} fillOpacity="0.45" />
        </svg>
      </span>
    </div>
  );
}

/** Schwebende Tab-Leiste der App (Liquid Glass), aktiver Tab hervorgehoben. */
export function TabBar({ active }: { active: "home" | "suche" | "karte" | "kalender" | "profil" }) {
  const tabs = [
    { id: "home", label: "Home", path: "M4 11.5 12 4l8 7.5V20a1 1 0 0 1-1 1h-4.5v-6h-5v6H5a1 1 0 0 1-1-1v-8.5Z" },
    { id: "suche", label: "Suche", path: "M10.5 4a6.5 6.5 0 1 0 4 11.6l4.2 4.2 1.4-1.4-4.2-4.2A6.5 6.5 0 0 0 10.5 4Zm0 2a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9Z" },
    { id: "karte", label: "Karte", path: "M3 6.5 8.5 4l7 2.5L21 4v13.5L15.5 20l-7-2.5L3 20V6.5Z" },
    { id: "kalender", label: "Kalender", path: "M5 5h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Zm0 5v9h14v-9H5Zm2-7h2v4H7V3Zm8 0h2v4h-2V3Z" },
    { id: "profil", label: "Profil", path: "M12 4a4 4 0 1 1 0 8 4 4 0 0 1 0-8Zm0 10c4.4 0 8 2.2 8 5v1H4v-1c0-2.8 3.6-5 8-5Z" },
  ] as const;
  return (
    <div className="absolute inset-x-[20px] bottom-[22px] z-20 flex h-[62px] items-center justify-between rounded-full border border-white/70 bg-white/80 px-[6px] shadow-[0_8px_30px_rgba(0,0,0,0.08)] backdrop-blur-xl" aria-hidden="true">
      {tabs.map((tab) => {
        const isActive = tab.id === active;
        return (
          <span
            key={tab.id}
            className={`flex h-[52px] w-[68px] flex-col items-center justify-center gap-[2px] rounded-full ${isActive ? "bg-black/[0.06]" : ""}`}
          >
            <svg width="24" height="24" viewBox="0 0 24 24" fill={isActive ? "#146194" : "#111111"}>
              <path d={tab.path} fillRule="evenodd" />
            </svg>
            <span style={{ font: "500 11px -apple-system, 'SF Pro Text', system-ui, sans-serif", color: isActive ? "#146194" : "#111111" }}>
              {tab.label}
            </span>
          </span>
        );
      })}
    </div>
  );
}
