/* eslint-disable @next/next/no-img-element */
import type { ReactNode } from "react";

// iPhone-Rahmen für echte Screenshots und Bildschirmaufnahmen der nativen App
// (Generated by Claude Code). Inhalte werden in iPhone-Breite (402 pt)
// gelegt und skaliert. Über die echte Statusleiste der Aufnahmen (Uhrzeit,
// Akkustand, Aufnahmepunkt) kommt eine saubere 9:41-Leiste mit Dynamic Island.
const SCREEN_W = 402;
const SCREEN_H = 874;
const BEZEL = 10;

export function PhoneFrame({
  width = 300,
  children,
  className = "",
  label,
}: {
  width?: number;
  children: ReactNode;
  className?: string;
  label: string;
}) {
  const inner = width - BEZEL * 2;
  const scale = inner / SCREEN_W;
  const innerHeight = SCREEN_H * scale;
  return (
    <figure
      aria-label={label}
      className={`relative shrink-0 bg-[#0c0c0d] ${className}`}
      style={{ width, height: innerHeight + BEZEL * 2, padding: BEZEL, borderRadius: width * 0.17 }}
    >
      <div className="relative overflow-hidden bg-white" style={{ width: inner, height: innerHeight, borderRadius: width * 0.145 }}>
        <div className="relative" style={{ width: SCREEN_W, height: SCREEN_H, transform: `scale(${scale})`, transformOrigin: "top left" }}>
          {children}
          <CleanStatusBar />
        </div>
      </div>
    </figure>
  );
}

/** Echter App-Screenshot. */
export function Screenshot({ src, alt, eager = false }: { src: string; alt: string; eager?: boolean }) {
  return (
    <img
      src={src}
      alt={alt}
      width={SCREEN_W}
      height={SCREEN_H}
      className="block h-full w-full object-cover object-top"
      loading={eager ? "eager" : "lazy"}
      decoding="async"
    />
  );
}

/** Echte Bildschirmaufnahme, stumm in Schleife. */
export function ScreenVideo({ src, poster, label }: { src: string; poster: string; label: string }) {
  return (
    <video
      className="block h-full w-full object-cover object-top"
      src={src}
      poster={poster}
      autoPlay
      muted
      loop
      playsInline
      preload="metadata"
      aria-label={label}
    />
  );
}

/** Weichzeichner-Band über der echten Statusleiste + saubere 9:41-Anzeige. */
function CleanStatusBar() {
  return (
    <div className="pointer-events-none absolute inset-x-0 top-0 z-20 h-[54px]" aria-hidden="true">
      <div
        className="absolute inset-0 bg-white/60 backdrop-blur-[20px]"
        style={{
          maskImage: "linear-gradient(to bottom, black 70%, transparent)",
          WebkitMaskImage: "linear-gradient(to bottom, black 70%, transparent)",
        }}
      />
      <div className="relative flex h-full items-center justify-between px-[34px] pt-[6px]">
        <span style={{ font: "600 17px -apple-system, 'SF Pro Text', system-ui, sans-serif", color: "#000" }}>9:41</span>
        <span className="absolute left-1/2 top-[11px] h-[37px] w-[124px] -translate-x-1/2 rounded-full bg-black" />
        <span className="flex items-center gap-[6px]">
          <svg width="18" height="12" viewBox="0 0 18 12" fill="#000">
            <rect x="0" y="8" width="3" height="4" rx="1" />
            <rect x="5" y="5.5" width="3" height="6.5" rx="1" />
            <rect x="10" y="3" width="3" height="9" rx="1" />
            <rect x="15" y="0" width="3" height="12" rx="1" />
          </svg>
          <svg width="16" height="12" viewBox="0 0 16 12" fill="#000">
            <path d="M8 2.2c2.3 0 4.4.9 6 2.4l1.3-1.4A10.5 10.5 0 0 0 8 .2 10.5 10.5 0 0 0 .7 3.2L2 4.6a8.5 8.5 0 0 1 6-2.4Zm0 3.8c1.3 0 2.5.5 3.4 1.3l1.4-1.4A6.7 6.7 0 0 0 8 4a6.7 6.7 0 0 0-4.8 1.9l1.4 1.4C5.5 6.5 6.7 6 8 6Zm0 3.6c-.6 0-1.1.2-1.5.6L8 11.8l1.5-1.6c-.4-.4-.9-.6-1.5-.6Z" />
          </svg>
          <svg width="27" height="13" viewBox="0 0 27 13" fill="none">
            <rect x="0.5" y="0.5" width="23" height="12" rx="3.8" stroke="#000" strokeOpacity="0.4" />
            <rect x="2" y="2" width="20" height="9" rx="2.5" fill="#000" />
            <path d="M25 4.5v4c.8-.3 1.3-1.1 1.3-2s-.5-1.7-1.3-2Z" fill="#000" fillOpacity="0.45" />
          </svg>
        </span>
      </div>
    </div>
  );
}
