/* eslint-disable @next/next/no-img-element */
import { StatusBar, TabBar } from "./phone";
import { APP_ACCENT, ARTIST, DETAIL_EVENT, FEED_EVENTS, HERO_EVENT } from "./data";

// Nachbauten der nativen iOS-Bildschirme (Generated by Claude Code). Maße,
// Schriftgrößen, Farben und Kartenformen folgen den echten SwiftUI-Views
// (HomeView, EventDetailView, PersonDetail) bzw. den Simulator-Screenshots;
// Inhalte sind echte Datenbank-Einträge (siehe data.ts).
const SF = "-apple-system, 'SF Pro Display', 'SF Pro Text', system-ui, sans-serif";
const APP_BG = "linear-gradient(180deg, #EEF5FB 0%, #F7FAFD 55%, #F4F8FC 100%)";

function CityPill({ city }: { city: string }) {
  return (
    <span
      className="flex h-[40px] items-center gap-[8px] rounded-full border border-black/[0.08] bg-white/70 px-[16px]"
      style={{ color: APP_ACCENT, font: `500 17px ${SF}` }}
    >
      <svg width="16" height="16" viewBox="0 0 16 16" fill={APP_ACCENT} aria-hidden="true">
        <path d="M15 1 1 7.2l6.1 1.7L8.8 15 15 1Z" />
      </svg>
      {city}
      <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke={APP_ACCENT} strokeWidth="1.8" aria-hidden="true">
        <path d="M2.5 4.5 6 8l3.5-3.5" />
      </svg>
    </span>
  );
}

/** Home-Feed "Für dich": Karten laufen endlos nach links durch. */
export function SimHomeFeed() {
  const loop = [...FEED_EVENTS, ...FEED_EVENTS];
  const hero = HERO_EVENT;
  return (
    <div className="relative h-full w-full overflow-hidden" style={{ background: APP_BG, fontFamily: SF }}>
      <StatusBar />
      <div className="flex items-center justify-between px-[16px] pt-[64px]">
        <span style={{ font: `600 17px ${SF}` }}>Klangradar</span>
        <CityPill city="München" />
      </div>

      <div className="relative mx-[20px] mt-[20px] h-[224px] overflow-hidden rounded-[30px]">
        <img src={hero.image} alt="" className="h-full w-full object-cover" />
        <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/15 to-transparent" />
        <div className="absolute inset-x-[20px] bottom-[18px] text-white">
          <div style={{ font: `600 13px ${SF}`, letterSpacing: "0.12em" }}>{hero.label}</div>
          <div className="mt-[4px]" style={{ font: `700 26px ${SF}`, letterSpacing: "-0.01em" }}>
            {hero.title}
          </div>
          <div className="mt-[4px] opacity-90" style={{ font: `400 16px ${SF}` }}>
            {hero.venue}
          </div>
        </div>
      </div>

      <div className="px-[20px] pt-[30px]" style={{ font: `700 26px ${SF}`, letterSpacing: "-0.01em" }}>
        Für dich
      </div>
      <div className="mt-[14px] overflow-hidden pl-[20px]">
        <div className="flex w-max gap-[16px]" style={{ animation: "fw-marquee 42s linear infinite" }}>
          {loop.map((event, index) => (
            <div key={`${event.title}-${index}`} className="w-[196px] shrink-0">
              <div className="relative h-[110px] overflow-hidden rounded-[20px]">
                <img src={event.image} alt="" className="h-full w-full object-cover" />
                <span className="absolute right-[10px] top-[10px]">
                  <svg width="22" height="20" viewBox="0 0 22 20" fill="none" stroke="white" strokeWidth="2">
                    <path d="M11 18.5S2 13 2 6.8A4.8 4.8 0 0 1 11 4.5a4.8 4.8 0 0 1 9 2.3C20 13 11 18.5 11 18.5Z" />
                  </svg>
                </span>
              </div>
              <div className="mt-[8px] line-clamp-2" style={{ font: `600 16px ${SF}`, lineHeight: 1.2 }}>
                {event.title}
              </div>
              <div className="mt-[3px] truncate text-[#8A8A8E]" style={{ font: `400 14px ${SF}` }}>
                {event.when} · {event.venue}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="px-[20px] pt-[26px]" style={{ font: `700 26px ${SF}`, letterSpacing: "-0.01em" }}>
        In den nächsten 7 Tagen
      </div>
      <div className="mt-[14px] flex gap-[16px] pl-[20px]">
        {FEED_EVENTS.slice(0, 2).map((event) => (
          <div key={event.title} className="h-[110px] w-[196px] shrink-0 overflow-hidden rounded-[20px]">
            <img src={event.image} alt="" className="h-full w-full object-cover" />
          </div>
        ))}
      </div>
      <TabBar active="home" />
    </div>
  );
}

/** Konzertdetail mit Mitwirkenden und Ticket-Leiste. */
export function SimEventDetail() {
  return (
    <div className="relative h-full w-full overflow-hidden" style={{ background: APP_BG, fontFamily: SF }}>
      <StatusBar light />
      <div className="relative h-[380px]">
        <img src={DETAIL_EVENT.image} alt="" className="h-full w-full object-cover" />
        <div className="absolute inset-0 bg-gradient-to-b from-black/35 via-transparent to-transparent" />
        <div className="absolute inset-x-[16px] top-[64px] flex justify-between">
          {["M15 5 8 12l7 7", ""].map((d, i) =>
            i === 0 ? (
              <span key="back" className="flex size-[44px] items-center justify-center rounded-full bg-white/25 backdrop-blur-md">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
                  <path d={d} />
                </svg>
              </span>
            ) : (
              <span key="actions" className="flex gap-[10px]">
                {["M12 20.5S3 15 3 8.8A4.8 4.8 0 0 1 12 6.5a4.8 4.8 0 0 1 9 2.3C21 15 12 20.5 12 20.5Z", "M12 3v12M7 8l5-5 5 5M5 14v5h14v-5"].map((p) => (
                  <span key={p} className="flex size-[44px] items-center justify-center rounded-full bg-white/25 backdrop-blur-md">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d={p} />
                    </svg>
                  </span>
                ))}
              </span>
            ),
          )}
        </div>
      </div>
      <div className="px-[20px] pt-[22px]">
        <div style={{ font: `700 30px ${SF}`, lineHeight: 1.12, letterSpacing: "-0.015em" }}>{DETAIL_EVENT.title}</div>
        <div className="mt-[14px] flex items-center gap-[10px]" style={{ font: `600 17px ${SF}` }}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#111" strokeWidth="1.8">
            <rect x="3" y="5" width="18" height="16" rx="2.5" />
            <path d="M3 10h18M8 3v4M16 3v4" />
          </svg>
          {DETAIL_EVENT.date}
        </div>
        <div className="mt-[8px] flex items-center gap-[10px] text-[#3C3C43]" style={{ font: `400 17px ${SF}` }}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#3C3C43" strokeWidth="1.8">
            <path d="M12 21s-7-6.2-7-11.5a7 7 0 0 1 14 0C19 14.8 12 21 12 21Z" />
            <circle cx="12" cy="9.5" r="2.5" />
          </svg>
          {DETAIL_EVENT.venue}
        </div>
        <div className="mt-[22px]" style={{ font: `700 22px ${SF}` }}>
          Mitwirkende
        </div>
        <div className="mt-[12px] flex flex-col gap-[10px]">
          {DETAIL_EVENT.people.map((person) => (
            <div key={person.name} className="flex items-center gap-[14px] rounded-[20px] bg-white/80 p-[10px] shadow-[0_1px_0_rgba(0,0,0,0.04)]">
              <img src={person.photo} alt="" className="size-[52px] rounded-full object-cover" />
              <div className="flex flex-col">
                <span style={{ font: `600 17px ${SF}` }}>{person.name}</span>
                <span className="text-[#8A8A8E]" style={{ font: `400 15px ${SF}` }}>
                  {person.role}
                </span>
              </div>
            </div>
          ))}
          <div className="flex items-center gap-[14px] rounded-[20px] bg-white/80 p-[10px]">
            <span className="flex size-[52px] items-center justify-center rounded-full" style={{ background: "#E3EEF7", color: APP_ACCENT, font: `700 15px ${SF}` }}>
              BR
            </span>
            <div className="flex min-w-0 flex-col">
              <span className="truncate" style={{ font: `600 17px ${SF}` }}>
                {DETAIL_EVENT.ensemble}
              </span>
              <span className="text-[#8A8A8E]" style={{ font: `400 15px ${SF}` }}>
                Orchester
              </span>
            </div>
          </div>
        </div>
      </div>
      <div className="absolute inset-x-0 bottom-0 z-20 flex items-center gap-[12px] border-t border-black/[0.06] bg-white/85 px-[20px] pb-[34px] pt-[14px] backdrop-blur-xl">
        <div className="flex min-w-0 flex-1 flex-col">
          <span className="text-[#8A8A8E]" style={{ font: `400 13px ${SF}` }}>
            Herkulessaal
          </span>
          <span className="whitespace-nowrap" style={{ font: `600 16px ${SF}` }}>Do., 15. Okt. · 20:00</span>
        </div>
        <span className="flex h-[50px] shrink-0 items-center whitespace-nowrap rounded-full px-[18px] text-white" style={{ background: APP_ACCENT, font: `600 16px ${SF}` }}>
          Zur Veranstaltungsseite
        </span>
      </div>
    </div>
  );
}

/** Künstlerseite mit "Folgen" und kommenden Terminen. */
export function SimArtist() {
  return (
    <div className="relative h-full w-full overflow-hidden" style={{ background: APP_BG, fontFamily: SF }}>
      <StatusBar light />
      <div className="relative h-[420px]">
        <img src={ARTIST.photo} alt="" className="h-full w-full object-cover object-top" />
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-black/30" />
        <div className="absolute inset-x-[20px] bottom-[22px] text-white">
          <div style={{ font: `600 15px ${SF}`, letterSpacing: "0.06em" }}>DIRIGENT</div>
          <div className="mt-[2px]" style={{ font: `700 36px ${SF}`, letterSpacing: "-0.02em" }}>
            {ARTIST.name}
          </div>
        </div>
      </div>
      <div className="flex gap-[10px] px-[20px] pt-[18px]">
        <span className="flex h-[48px] flex-1 items-center justify-center gap-[8px] rounded-full text-white" style={{ background: APP_ACCENT, font: `600 17px ${SF}` }}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="white">
            <path d="M12 21.5 10.6 20C5.4 15.4 2 12.3 2 8.5A5.5 5.5 0 0 1 7.5 3c1.7 0 3.4.8 4.5 2.1A6 6 0 0 1 16.5 3 5.5 5.5 0 0 1 22 8.5c0 3.8-3.4 6.9-8.6 11.5L12 21.5Z" />
          </svg>
          Folgst du
        </span>
        <span className="flex h-[48px] w-[48px] items-center justify-center rounded-full bg-white/80">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke={APP_ACCENT} strokeWidth="2" strokeLinecap="round">
            <path d="M12 3v12M7 8l5-5 5 5M5 14v5h14v-5" />
          </svg>
        </span>
      </div>
      <div className="px-[20px] pt-[24px]" style={{ font: `700 22px ${SF}` }}>
        Nächste Konzerte
      </div>
      <div className="mx-[20px] mt-[12px] overflow-hidden rounded-[22px] bg-white/85">
        {ARTIST.upcoming.map((item, index) => (
          <div key={item.title} className={`flex items-center gap-[14px] px-[14px] py-[12px] ${index > 0 ? "border-t border-black/[0.06]" : ""}`}>
            <span className="flex w-[46px] flex-col items-center">
              <span style={{ color: APP_ACCENT, font: `600 12px ${SF}` }}>{item.month.toUpperCase()}</span>
              <span style={{ font: `700 22px ${SF}` }}>{item.day}</span>
            </span>
            <span className="flex min-w-0 flex-col">
              <span className="truncate" style={{ font: `600 16px ${SF}` }}>
                {item.title}
              </span>
              <span className="truncate text-[#8A8A8E]" style={{ font: `400 14px ${SF}` }}>
                {item.meta}
              </span>
            </span>
          </div>
        ))}
      </div>
      <TabBar active="suche" />
    </div>
  );
}
