import type { Metadata } from "next";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { CountUp } from "@/components/motion/count-up";
import { Reveal } from "@/components/motion/reveal";
import { RotatingWord } from "@/components/motion/rotating-word";

export const metadata: Metadata = {
  title: "Klassische Konzerte entdecken",
  description: "Klassische Konzerte entdecken — in München, Berlin, Hamburg, Wien und Frankfurt.",
  alternates: { canonical: "/" },
  openGraph: {
    title: "Klangradar — Klassische Konzerte entdecken",
    description: "Konzerte, Ensembles und Spielstätten an einem Ort.",
    url: "/",
  },
};

// Flat-White-Landingpage (Generated by Claude Code, Okt. 2026). Zahlen kommen
// live aus der Datenbank; schlägt eine Abfrage fehl, fällt die Kennzahl weg,
// statt eine erfundene Zahl zu zeigen.
const CITIES = ["München", "Berlin", "Hamburg", "Wien", "Frankfurt"];

const STAT_COLUMNS: Record<number, string> = { 1: "sm:grid-cols-1", 2: "sm:grid-cols-2", 3: "sm:grid-cols-3", 4: "sm:grid-cols-4" };

const VENUES = [
  "Nationaltheater",
  "Isarphilharmonie",
  "Herkulessaal",
  "Gärtnerplatztheater",
  "Philharmonie Berlin",
  "Konzerthaus Berlin",
  "Komische Oper Berlin",
  "Elbphilharmonie",
  "Musikverein Wien",
  "Wiener Konzerthaus",
  "Theater an der Wien",
  "Volksoper Wien",
  "Alte Oper Frankfurt",
  "Oper Frankfurt",
];

const ORGANIZER_FEATURES = [
  {
    title: "Programm pflegen",
    text: "Termine, Besetzungen und Werke an einer Stelle anlegen — oder automatisch aus der eigenen Website übernehmen lassen.",
  },
  {
    title: "Reichweite aufbauen",
    text: "Termine hervorheben und gezielt Menschen zeigen, die Ensembles, Werken oder Spielstätten folgen.",
  },
  {
    title: "Wirkung sehen",
    text: "Aufrufe, Merklisten und Ticket-Klicks pro Termin — als Grundlage für die nächste Saison.",
  },
  {
    title: "Im Team arbeiten",
    text: "Mitglieder mit Rollen einladen, Agenturen verbinden und Profile von Ensembles oder Spielstätten verwalten.",
  },
];

async function loadStats() {
  try {
    const supabase = await createClient();
    const now = new Date().toISOString();
    const [events, venues, ensembles] = await Promise.all([
      supabase
        .from("events")
        .select("id", { count: "exact", head: true })
        .gte("start_datetime", now)
        .in("status", ["scheduled", "sold_out"]),
      supabase.from("venues").select("id", { count: "exact", head: true }),
      supabase.from("ensembles").select("id", { count: "exact", head: true }),
    ]);
    return [
      { label: "kommende Konzerte", value: events.error ? null : events.count },
      { label: "Spielstätten", value: venues.error ? null : venues.count },
      { label: "Ensembles", value: ensembles.error ? null : ensembles.count },
      { label: "Städte", value: CITIES.length },
    ].filter((stat): stat is { label: string; value: number } => typeof stat.value === "number" && stat.value > 0);
  } catch {
    return [];
  }
}

export default async function PublicHomePage() {
  const stats = await loadStats();

  return (
    <div className="overflow-hidden">
      <section className="mx-auto flex max-w-5xl flex-col items-start gap-8 px-6 pb-20 pt-20 sm:pt-28">
        <span className="fw-rise inline-flex items-center gap-2 rounded-full border border-[#EAEAEA] px-3 py-1 text-[13px] text-[#4A4A4A]">
          <span className="fw-pulse-dot size-1.5 rounded-full bg-[#2D2A6E]" aria-hidden="true" />
          Für Konzertgänger und Veranstalter
        </span>
        <h1
          className="fw-rise max-w-4xl text-[clamp(2.75rem,7vw,5.5rem)] font-semibold leading-[0.98] tracking-[-0.045em] text-[#111111]"
          style={{ animationDelay: "80ms" }}
        >
          Klassische Konzerte in <RotatingWord words={CITIES} className="text-[#2D2A6E]" />
        </h1>
        <p
          className="fw-rise max-w-xl text-[clamp(1.05rem,1.6vw,1.25rem)] leading-relaxed text-[#4A4A4A]"
          style={{ animationDelay: "160ms" }}
        >
          Alle Konzerte, Ensembles und Spielstätten an einem Ort — redaktionell geprüft und jeden Tag aktuell.
        </p>
        <div className="fw-rise flex flex-wrap gap-3" style={{ animationDelay: "240ms" }}>
          <Link
            href="/veranstalter"
            className="group inline-flex h-12 items-center gap-2 rounded-lg bg-[#2D2A6E] px-6 text-[15px] font-medium text-white hover:bg-[#1F1D52]"
          >
            Als Veranstalter starten
            <span aria-hidden="true" className="transition-transform duration-200 group-hover:translate-x-1">
              →
            </span>
          </Link>
          <a
            href="#veranstalter"
            className="inline-flex h-12 items-center rounded-lg border border-[#DADADA] px-6 text-[15px] font-medium text-[#111111] hover:border-[#111111]"
          >
            Mehr erfahren
          </a>
        </div>
      </section>

      {stats.length > 0 && (
        <section aria-label="Klangradar in Zahlen" className="border-y border-[#EAEAEA]">
          <dl className={`mx-auto grid max-w-5xl grid-cols-2 ${STAT_COLUMNS[stats.length] ?? "sm:grid-cols-4"}`}>
            {stats.map((stat, index) => (
              <div
                key={stat.label}
                className={[
                  "flex flex-col gap-1 px-6 py-8",
                  index % 2 === 1 ? "border-l border-[#EAEAEA]" : "",
                  index > 0 && index % 2 === 0 ? "sm:border-l sm:border-[#EAEAEA]" : "",
                  index > 1 ? "border-t border-[#EAEAEA] sm:border-t-0" : "",
                ].join(" ")}
              >
                <dt className="order-2 text-[14px] text-[#6B6B6B]">{stat.label}</dt>
                <dd className="order-1 font-[family-name:var(--font-geist-mono)] text-[clamp(1.75rem,3vw,2.5rem)] font-medium tracking-[-0.03em] text-[#111111]">
                  <CountUp value={stat.value} />
                </dd>
              </div>
            ))}
          </dl>
        </section>
      )}

      <section aria-label="Spielstätten" className="group relative py-10">
        <div className="pointer-events-none absolute inset-y-0 left-0 z-10 w-24 bg-gradient-to-r from-white to-transparent" aria-hidden="true" />
        <div className="pointer-events-none absolute inset-y-0 right-0 z-10 w-24 bg-gradient-to-l from-white to-transparent" aria-hidden="true" />
        <ul className="sr-only">
          {VENUES.map((venue) => (
            <li key={venue}>{venue}</li>
          ))}
        </ul>
        <div
          aria-hidden="true"
          className="flex w-max gap-12 whitespace-nowrap text-[clamp(1.25rem,2.4vw,1.75rem)] font-medium tracking-[-0.02em] text-[#BDBDBD] group-hover:[animation-play-state:paused]"
          style={{ animation: "fw-marquee 48s linear infinite" }}
        >
          {[...VENUES, ...VENUES].map((venue, index) => (
            <span key={`${venue}-${index}`} className="transition-colors duration-200 hover:text-[#111111]">
              {venue}
            </span>
          ))}
        </div>
      </section>

      <section id="veranstalter" className="mx-auto max-w-5xl scroll-mt-24 px-6 py-20 sm:py-28">
        <Reveal>
          <p className="text-[14px] font-medium text-[#2D2A6E]">Für Veranstalter</p>
          <h2 className="mt-3 max-w-2xl text-[clamp(2rem,4vw,3rem)] font-semibold leading-[1.05] tracking-[-0.035em] text-[#111111]">
            Ihr Programm dort, wo Publikum sucht.
          </h2>
        </Reveal>
        <div className="mt-14 grid border-t border-[#EAEAEA] sm:grid-cols-2">
          {ORGANIZER_FEATURES.map((feature, index) => (
            <Reveal
              key={feature.title}
              delayMs={index * 90}
              className={`border-b border-[#EAEAEA] py-8 ${index % 2 === 0 ? "sm:border-r sm:pr-8" : "sm:pl-8"}`}
            >
              <div className="flex items-baseline gap-4">
                <span className="font-[family-name:var(--font-geist-mono)] text-[13px] text-[#8A8A8A]">0{index + 1}</span>
                <div className="flex flex-col gap-2">
                  <h3 className="text-[18px] font-semibold tracking-[-0.015em] text-[#111111]">{feature.title}</h3>
                  <p className="text-[15px] leading-relaxed text-[#4A4A4A]">{feature.text}</p>
                </div>
              </div>
            </Reveal>
          ))}
        </div>
      </section>

      <section className="border-t border-[#EAEAEA]">
        <Reveal className="mx-auto flex max-w-5xl flex-col items-start gap-6 px-6 py-20 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="max-w-xl text-[clamp(1.6rem,3vw,2.25rem)] font-semibold leading-[1.1] tracking-[-0.03em] text-[#111111]">
            Bereit für die nächste Saison?
          </h2>
          <Link
            href="/veranstalter"
            className="group inline-flex h-12 items-center gap-2 rounded-lg bg-[#2D2A6E] px-6 text-[15px] font-medium text-white hover:bg-[#1F1D52]"
          >
            Zum Veranstalterportal
            <span aria-hidden="true" className="transition-transform duration-200 group-hover:translate-x-1">
              →
            </span>
          </Link>
        </Reveal>
      </section>
    </div>
  );
}
