import type { Metadata } from "next";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { CountUp } from "@/components/motion/count-up";
import { Reveal } from "@/components/motion/reveal";
import { RotatingWord } from "@/components/motion/rotating-word";
import { PhoneFrame, Screenshot } from "@/components/app-site/phone";
import { SimArtist, SimEventDetail, SimHomeFeed } from "@/components/app-site/sim-screens";

export const metadata: Metadata = {
  title: "Klangradar für iPhone — Klassische Konzerte entdecken",
  description:
    "Oper, Sinfoniekonzerte und Kammermusik in München, Berlin, Hamburg, Wien und Frankfurt — personalisiert, mit Künstlern, Spielstätten und Kalender. Die Klangradar-App für iPhone.",
  alternates: { canonical: "/" },
  openGraph: {
    title: "Klangradar für iPhone",
    description: "Das Konzertleben deiner Stadt in einer App.",
    url: "/",
  },
};

// App-Website (Generated by Claude Code, Okt. 2026): bewirbt die native
// iOS-App. Echte Simulator-Screenshots (public/app/) und Nachbauten der
// App-Bildschirme mit echten Einträgen (components/app-site/). Kennzahlen
// kommen live aus der Datenbank und fallen bei einem Fehler weg.
const CITIES = ["München", "Berlin", "Hamburg", "Wien", "Frankfurt"];

const CITY_ROWS = [
  { name: "München", venues: "Nationaltheater · Isarphilharmonie · Herkulessaal · Gärtnerplatztheater" },
  { name: "Berlin", venues: "Philharmonie · Konzerthaus · Komische Oper · Deutsche Oper" },
  { name: "Hamburg", venues: "Elbphilharmonie · Laeiszhalle · Staatsoper" },
  { name: "Wien", venues: "Musikverein · Konzerthaus · Staatsoper · Theater an der Wien" },
  { name: "Frankfurt", venues: "Alte Oper · Oper Frankfurt" },
];

const STAT_COLUMNS: Record<number, string> = { 1: "sm:grid-cols-1", 2: "sm:grid-cols-2", 3: "sm:grid-cols-3", 4: "sm:grid-cols-4" };

const IPHONE_FEATURES = [
  { title: "Sprachsuche", text: "„Mahler in der Isarphilharmonie“ — einfach sagen statt tippen." },
  { title: "Direkt in den Kalender", text: "Ein Tipp, und das Konzert steht mit Ort und Uhrzeit in deinem iPhone-Kalender." },
  { title: "Merkliste, auch offline", text: "Gemerkte Konzerte bleiben verfügbar, auch ohne Netz im Foyer." },
  { title: "Mit Face ID geschützt", text: "Dein Profil und deine Listen öffnen sich nur für dich." },
  { title: "Klangradar-KI", text: "Frag nach dem passenden Abend — die KI kennt Programm, Besetzung und deine Vorlieben." },
  { title: "Fünf Städte", text: "München, Berlin, Hamburg, Wien und Frankfurt. Stadt wechseln mit einem Tipp." },
];

async function loadStats() {
  try {
    const supabase = await createClient();
    const now = new Date().toISOString();
    const [events, persons, ensembles] = await Promise.all([
      supabase
        .from("events")
        .select("id", { count: "exact", head: true })
        .gte("start_datetime", now)
        .in("status", ["scheduled", "sold_out"]),
      supabase.from("persons").select("id", { count: "exact", head: true }),
      supabase.from("ensembles").select("id", { count: "exact", head: true }),
    ]);
    return [
      { label: "kommende Konzerte", value: events.error ? null : events.count },
      { label: "Künstlerinnen und Künstler", value: persons.error ? null : persons.count },
      { label: "Ensembles", value: ensembles.error ? null : ensembles.count },
      { label: "Städte", value: CITIES.length },
    ].filter((stat): stat is { label: string; value: number } => typeof stat.value === "number" && stat.value > 0);
  } catch {
    return [];
  }
}

function AppStoreBadge() {
  return (
    <span
      className="inline-flex h-14 items-center gap-3 rounded-xl bg-[#111111] px-5 text-white"
      aria-label="Demnächst im App Store"
    >
      <svg width="22" height="26" viewBox="0 0 17 20" fill="currentColor" aria-hidden="true">
        <path d="M14.2 10.6c0-2.6 2.1-3.8 2.2-3.9-1.2-1.8-3.1-2-3.7-2-1.6-.2-3.1.9-3.9.9-.8 0-2-.9-3.4-.9C3.6 4.8 2 5.8 1.1 7.4c-1.9 3.2-.5 8 1.3 10.6.9 1.3 1.9 2.7 3.3 2.6 1.3-.1 1.8-.8 3.4-.8s2 .8 3.4.8c1.4 0 2.3-1.3 3.2-2.6 1-1.5 1.4-2.9 1.4-3-.1 0-2.7-1-2.9-4.4ZM11.7 3c.7-.9 1.2-2.1 1.1-3.3-1 0-2.3.7-3 1.6-.7.8-1.2 2-1.1 3.2 1.2.1 2.3-.6 3-1.5Z" />
      </svg>
      <span className="flex flex-col leading-none">
        <span className="text-[11px] text-white/75">Demnächst im</span>
        <span className="mt-1 text-[19px] font-semibold tracking-[-0.01em]">App Store</span>
      </span>
    </span>
  );
}

function FeatureRow({
  eyebrow,
  title,
  text,
  points,
  phone,
  reverse = false,
}: {
  eyebrow: string;
  title: string;
  text: string;
  points: string[];
  phone: React.ReactNode;
  reverse?: boolean;
}) {
  return (
    <section className="border-t border-[#EAEAEA]">
      <div
        className={`mx-auto flex max-w-6xl flex-col items-center gap-14 px-6 py-24 md:gap-20 lg:py-32 ${reverse ? "md:flex-row-reverse" : "md:flex-row"}`}
      >
        <Reveal className="flex-1">
          <p className="text-[14px] font-medium text-[#2D2A6E]">{eyebrow}</p>
          <h2 className="mt-3 max-w-md text-[clamp(2rem,4vw,3rem)] font-semibold leading-[1.04] tracking-[-0.035em] text-[#111111]">
            {title}
          </h2>
          <p className="mt-5 max-w-md text-[17px] leading-relaxed text-[#4A4A4A]">{text}</p>
          <ul className="mt-8 flex max-w-md flex-col border-t border-[#EAEAEA]">
            {points.map((point) => (
              <li key={point} className="flex items-start gap-3 border-b border-[#EAEAEA] py-3.5 text-[15px] text-[#111111]">
                <svg className="mt-1 shrink-0" width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="#2D2A6E" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <path d="M2.5 7.5 5.5 10.5 11.5 3.5" />
                </svg>
                {point}
              </li>
            ))}
          </ul>
        </Reveal>
        <Reveal delayMs={120} className="flex flex-1 justify-center">
          <div className="fw-float">{phone}</div>
        </Reveal>
      </div>
    </section>
  );
}

export default async function PublicHomePage() {
  const stats = await loadStats();

  return (
    <div className="overflow-hidden">
      {/* Hero */}
      <section className="mx-auto flex max-w-6xl flex-col items-center gap-16 px-6 pb-24 pt-16 md:flex-row md:gap-10 md:pt-24">
        <div className="flex flex-1 flex-col items-start gap-7">
          <span className="fw-rise inline-flex items-center gap-2 rounded-full border border-[#EAEAEA] px-3 py-1 text-[13px] text-[#4A4A4A]">
            <span className="fw-pulse-dot size-1.5 rounded-full bg-[#2D2A6E]" aria-hidden="true" />
            Die Klassik-App für iPhone
          </span>
          <h1
            className="fw-rise text-[clamp(2.5rem,5vw,4.25rem)] font-semibold leading-[1.02] tracking-[-0.045em] text-[#111111]"
            style={{ animationDelay: "80ms" }}
          >
            Das Konzertleben von
            <br />
            <RotatingWord words={CITIES} className="text-[#2D2A6E]" />
            <br />
            in einer App.
          </h1>
          <p className="fw-rise max-w-md text-[clamp(1.05rem,1.5vw,1.2rem)] leading-relaxed text-[#4A4A4A]" style={{ animationDelay: "160ms" }}>
            Oper, Sinfoniekonzerte und Kammermusik — kuratiert nach deinem Geschmack, mit Besetzung, Programm und
            Spielstätte. Jeden Tag aktuell.
          </p>
          <div className="fw-rise flex flex-wrap items-center gap-4" style={{ animationDelay: "240ms" }}>
            <AppStoreBadge />
            <a href="#funktionen" className="fw-link text-[15px] font-medium text-[#111111]">
              Funktionen ansehen
            </a>
          </div>
        </div>
        <div className="relative flex flex-1 justify-center">
          <div className="fw-rise absolute left-1/2 top-14 hidden -translate-x-[95%] -rotate-[8deg] opacity-90 sm:block" style={{ animationDelay: "320ms" }}>
            <PhoneFrame width={250} label="Screenshot: Suche in der Klangradar-App">
              <Screenshot src="/app-preview/search2.jpg" alt="Suche: Personen, Ensembles, Orte und Werke entdecken" eager />
            </PhoneFrame>
          </div>
          <div className="fw-rise relative z-10 sm:translate-x-[18%]" style={{ animationDelay: "200ms" }}>
            <div className="fw-float">
              <PhoneFrame width={300} label="Klangradar-App: Startseite mit Empfehlungen in München">
                <SimHomeFeed />
              </PhoneFrame>
            </div>
          </div>
        </div>
      </section>

      {stats.length > 0 && (
        <section aria-label="Klangradar in Zahlen" className="border-y border-[#EAEAEA]">
          <dl className={`mx-auto grid max-w-6xl grid-cols-2 ${STAT_COLUMNS[stats.length] ?? "sm:grid-cols-4"}`}>
            {stats.map((stat, index) => (
              <div
                key={stat.label}
                className={[
                  "flex flex-col gap-1 px-6 py-8",
                  index % 2 === 1 ? "border-l border-[#EAEAEA]" : "",
                  index > 0 && index % 2 === 0 ? "sm:border-l sm:border-[#EAEAEA]" : "",
                  index > 1 ? "border-t border-[#EAEAEA] sm:border-t-0" : "",
                ].join(" ")}
              >
                <dt className="order-2 text-[14px] text-[#6B6B6B]">{stat.label}</dt>
                <dd className="order-1 font-[family-name:var(--font-geist-mono)] text-[clamp(1.75rem,3vw,2.5rem)] font-medium tracking-[-0.03em] text-[#111111]">
                  <CountUp value={stat.value} />
                </dd>
              </div>
            ))}
          </dl>
        </section>
      )}

      <div id="funktionen" className="scroll-mt-20">
        <FeatureRow
          eyebrow="Kalender"
          title="Heute Abend? Ein Blick genügt."
          text="Jeder Punkt ist ein Konzert. Tippe auf einen Tag und sieh sofort, was wo gespielt wird — mit Uhrzeit und Spielstätte."
          points={[
            "Empfehlungen nach Komponisten, Künstlern und Spielstätten",
            "Heute, diese Woche, demnächst — immer im Blick",
            "Merken mit einem Tipp",
          ]}
          phone={
            <PhoneFrame width={290} label="Kalender der App mit Konzerten im Oktober">
              <Screenshot src="/app-preview/calendar-ffm.jpg" alt="Kalender: Oktober 2026, am 10. Oktober Ensemble Modern in der Alten Oper Frankfurt" />
            </PhoneFrame>
          }
        />
        <FeatureRow
          reverse
          eyebrow="Jedes Konzert im Detail"
          title="Wer spielt. Wo. Und wann."
          text="Besetzung, Spielstätte und Termin auf einen Blick — und mit einem Tipp im Kalender oder auf der Seite des Veranstalters."
          points={["Dirigentinnen, Solisten und Ensembles verlinkt", "Ort mit Anfahrt und Karte", "Direkt in den iPhone-Kalender"]}
          phone={
            <PhoneFrame width={290} label="Konzertdetail: Sir Simon Rattle und Isabelle Faust im Herkulessaal">
              <SimEventDetail />
            </PhoneFrame>
          }
        />
        <FeatureRow
          eyebrow="Folgen"
          title="Verpasse nie wieder deine Lieblinge."
          text="Folge Dirigenten, Solistinnen, Orchestern und Häusern. Kündigen sie einen neuen Termin an, erfährst du es zuerst."
          points={["Mitteilungen bei neuen Konzerten", "Alle kommenden Termine einer Person", "Biografie und Bilder"]}
          phone={
            <PhoneFrame width={290} label="Künstlerseite: Sir Simon Rattle mit kommenden Konzerten">
              <SimArtist />
            </PhoneFrame>
          }
        />
      </div>

      {/* Echte Screenshots im Überblick */}
      <section className="border-t border-[#EAEAEA] bg-[#FAFAFA]">
        <div className="mx-auto max-w-6xl px-6 py-24 lg:py-32">
          <Reveal>
            <p className="text-[14px] font-medium text-[#2D2A6E]">Entdecken</p>
            <h2 className="mt-3 max-w-2xl text-[clamp(2rem,4vw,3rem)] font-semibold leading-[1.04] tracking-[-0.035em] text-[#111111]">
              Suchen, stöbern, auf der Karte finden.
            </h2>
          </Reveal>
          <div className="-mx-6 mt-14 flex snap-x snap-mandatory gap-8 overflow-x-auto px-6 pb-4 md:mx-0 md:grid md:grid-cols-3 md:overflow-visible md:px-0">
            {[
              { src: "/app-preview/search2.jpg", alt: "Suche nach Personen, Ensembles, Orten und Werken", caption: "Alles entdecken", text: "Personen, Ensembles, Orte und Werke." },
              { src: "/app-preview/map.jpg", alt: "Karte mit allen Spielstätten in Frankfurt", caption: "Karte", text: "Jede Spielstätte deiner Stadt auf einen Blick." },
              { src: "/app-preview/cities-muc.jpg", alt: "Stadtauswahl: München, Berlin, Hamburg, Wien, Frankfurt am Main", caption: "Fünf Städte", text: "Stadt wechseln mit einem Tipp." },
            ].map((shot, index) => (
              <Reveal key={shot.src} delayMs={index * 110} className="flex shrink-0 snap-center flex-col items-center gap-5">
                <PhoneFrame width={260} label={shot.alt}>
                  <Screenshot src={shot.src} alt={shot.alt} />
                </PhoneFrame>
                <div className="text-center">
                  <p className="text-[16px] font-semibold text-[#111111]">{shot.caption}</p>
                  <p className="mt-1 text-[14px] text-[#6B6B6B]">{shot.text}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* Städte */}
      <section id="staedte" className="scroll-mt-20 border-t border-[#EAEAEA]">
        <div className="mx-auto max-w-6xl px-6 py-24 lg:py-32">
          <Reveal>
            <p className="text-[14px] font-medium text-[#2D2A6E]">Fünf Städte</p>
            <h2 className="mt-3 max-w-2xl text-[clamp(2rem,4vw,3rem)] font-semibold leading-[1.04] tracking-[-0.035em] text-[#111111]">
              Zu Hause in den großen Musikstädten.
            </h2>
          </Reveal>
          <ul className="mt-12 border-t border-[#EAEAEA]">
            {CITY_ROWS.map((city, index) => (
              <Reveal key={city.name} delayMs={index * 70}>
                <li className="group grid grid-cols-[3rem_minmax(0,1fr)] items-baseline gap-4 border-b border-[#EAEAEA] py-5 sm:grid-cols-[3rem_minmax(0,16rem)_minmax(0,1fr)]">
                  <span className="font-[family-name:var(--font-geist-mono)] text-[13px] text-[#8A8A8A]">0{index + 1}</span>
                  <span className="text-[clamp(1.6rem,3vw,2.5rem)] font-semibold tracking-[-0.035em] text-[#111111] transition-[color,transform] duration-300 group-hover:translate-x-2 group-hover:text-[#2D2A6E]">
                    {city.name}
                  </span>
                  <span className="col-start-2 text-[15px] text-[#6B6B6B] sm:col-start-auto">{city.venues}</span>
                </li>
              </Reveal>
            ))}
          </ul>
        </div>
      </section>

      {/* iPhone-Funktionen */}
      <section className="border-t border-[#EAEAEA]">
        <div className="mx-auto max-w-6xl px-6 py-24 lg:py-32">
          <Reveal>
            <p className="text-[14px] font-medium text-[#2D2A6E]">Gemacht für iPhone</p>
            <h2 className="mt-3 max-w-2xl text-[clamp(2rem,4vw,3rem)] font-semibold leading-[1.04] tracking-[-0.035em] text-[#111111]">
              Nativ gebaut. Schnell, ruhig, auf den Punkt.
            </h2>
          </Reveal>
          <div className="mt-14 grid gap-px overflow-hidden border-y border-[#EAEAEA] bg-[#EAEAEA] sm:grid-cols-2 lg:grid-cols-3">
            {IPHONE_FEATURES.map((feature, index) => (
              <Reveal
                key={feature.title}
                delayMs={(index % 3) * 90}
                className="bg-white px-1 py-8 sm:px-6"
              >
                <h3 className="text-[18px] font-semibold tracking-[-0.015em] text-[#111111]">{feature.title}</h3>
                <p className="mt-2 text-[15px] leading-relaxed text-[#4A4A4A]">{feature.text}</p>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* Für Veranstalter */}
      <section className="border-t border-[#EAEAEA] bg-[#FAFAFA]">
        <Reveal className="mx-auto flex max-w-6xl flex-col items-start gap-6 px-6 py-16 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-[14px] font-medium text-[#2D2A6E]">Für Veranstalter</p>
            <p className="mt-2 max-w-xl text-[clamp(1.25rem,2.2vw,1.6rem)] font-semibold leading-snug tracking-[-0.025em] text-[#111111]">
              Ihr Programm in der App: Termine pflegen, Reichweite aufbauen, Wirkung sehen.
            </p>
          </div>
          <Link
            href="/veranstalter"
            className="group inline-flex h-12 shrink-0 items-center gap-2 rounded-lg border border-[#DADADA] bg-white px-6 text-[15px] font-medium text-[#111111] hover:border-[#111111]"
          >
            Zum Veranstalterportal
            <span aria-hidden="true" className="transition-transform duration-200 group-hover:translate-x-1">
              →
            </span>
          </Link>
        </Reveal>
      </section>

      {/* Abschluss */}
      <section className="border-t border-[#EAEAEA]">
        <Reveal className="mx-auto flex max-w-6xl flex-col items-center gap-8 px-6 py-28 text-center">
          <h2 className="max-w-3xl text-[clamp(2.25rem,5vw,4rem)] font-semibold leading-[1.02] tracking-[-0.04em] text-[#111111]">
            Dein nächster Konzertabend wartet schon.
          </h2>
          <AppStoreBadge />
        </Reveal>
      </section>
    </div>
  );
}
