-- Generated by Claude Code — öffentliche Quellenangabe pro Event (Punkt 3
-- aus docs/10-legal-status.md: Transparenz-Maßnahme für die rechtlich noch
-- ungeprüften Scrape-Quellen, ersetzt keine anwaltliche Prüfung, reduziert
-- aber das Risiko und ist ohnehin guter Stil bei Datenübernahmen).
--
-- Die `sources`-Tabelle selbst bleibt admin/editor-only (enthält in `config`
-- CSS-Selektoren und in `legal_basis` interne rechtliche Einschätzungen, die
-- nicht öffentlich sein sollen). Diese Funktion gibt bewusst nur Name und
-- URL der Quelle zurück, sonst nichts.
create or replace function public.event_source_attribution(p_event_id uuid)
returns table(source_name text, source_url text)
language sql
security definer
stable
set search_path = public
as $$
  select s.name, s.url
  from events e
  join sources s on s.id = e.source_id
  where e.id = p_event_id;
$$;

grant execute on function public.event_source_attribution(uuid) to anon, authenticated;
