-- 21 weitere Münchner Spielstätten (auf Nutzerwunsch, Liste von 22 geprüft
-- — "Bayerischer Hof – Festsaal zur Stadt" ließ sich unter diesem Namen
-- nirgends verifizieren, laut Hotel-eigener Raumliste gibt es nur
-- "Festsaal", "Festsaal Rang I", "Atrium" und "Spiegelsaal"; daher
-- weggelassen statt geraten). Adressen/Koordinaten recherchiert und über
-- Nominatim/OpenStreetMap geokodiert, is_verified bewusst false wie beim
-- ursprünglichen Excel-Import — redaktionelle Freigabe steht aus.
--
-- Hinweis für die Redaktion: DREI verschiedene, räumlich getrennte Orte
-- tragen "Carl Orff" im Namen — das bereits vorhandene "Carl-Orff-Saal" im
-- alten Gasteig-Gebäude (Rosenheimer Straße 5), das hier neu angelegte
-- "Carl-Orff-Auditorium" an der HMTM-Dependance (Luisenstraße 37a), und ein
-- dritter, interner Saal desselben Namens im "Fat Cat"-Kulturzentrum (das
-- ebenfalls im alten Gasteig-Gebäude sitzt) — beim Zuordnen von Events
-- nicht verwechseln.
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, capacity, is_verified) values
  ('hubertussaal', 'Hubertussaal', 'Historischer Konzertsaal im Nordtrakt von Schloss Nymphenburg, größter der drei Säle im Orangerietrakt mit Platz für rund 400 Gäste.', 'Schloss Nymphenburg 1', '80638', 'München', ST_MakePoint(11.5032967, 48.1582569)::geography, 'https://www.schlosskonzerte-nymphenburg.de/', 400, false),
  ('max-joseph-saal', 'Max-Joseph-Saal', 'Klassizistischer Festsaal in der Münchner Residenz mit Stuckdekor und Kristalllüstern, einer der akustisch besten Kammermusiksäle der Stadt.', 'Residenzstraße 1', '80333', 'München', ST_MakePoint(11.5778676, 48.1421714)::geography, 'https://www.schloesser.bayern.de/deutsch/raeume/objekte/mu_r_mj.htm', 330, false),
  ('alte-kongresshalle', 'Alte Kongresshalle', 'Denkmalgeschützte, retrofuturistische Veranstaltungshalle von 1952/53 auf der Theresienhöhe, seit 2007 als Eventlocation genutzt.', 'Theresienhöhe 14', '80339', 'München', ST_MakePoint(11.5458135, 48.1327267)::geography, 'https://www.altekongresshalle.de/', 850, false),
  ('hochschule-fuer-musik-und-theater-muenchen', 'Hochschule für Musik und Theater München', 'Staatliche Musikhochschule im ehemaligen NS-„Führerbau" am Königsplatz, zentrale Ausbildungsstätte für Musik und Theater in München.', 'Arcisstraße 12', '80333', 'München', ST_MakePoint(11.5674452, 48.1460982)::geography, 'https://www.hmtm.de/', null, false),
  ('carl-orff-auditorium', 'Carl-Orff-Auditorium', 'Kleiner Konzertsaal der Hochschule für Musik und Theater in der Dependance Luisenstraße, ehemalige Reaktorhalle. Nicht zu verwechseln mit dem gleichnamigen Saal im alten Gasteig-Gebäude.', 'Luisenstraße 37a', '80333', 'München', ST_MakePoint(11.5647517, 48.1482436)::geography, 'https://www.hmtm.de/', 116, false),
  ('rubinstein-saal', 'Rubinstein-Saal', 'Konzertsaal des Tonkünstlerverbands München mit Steinway-Flügel, genutzt für Schüler- und Kammerkonzerte.', 'Landsberger Straße 336', '80687', 'München', ST_MakePoint(11.4956052, 48.1441221)::geography, 'https://www.tonkuenstler-muenchen.de/', null, false),
  ('buergerhaus-garching', 'Bürgerhaus Garching', 'Modernes Veranstaltungszentrum am Bürgerplatz Garching mit teilbarem Hauptsaal für bis zu 800 Personen.', 'Bürgerplatz 9', '85748', 'Garching bei München', ST_MakePoint(11.6504393, 48.2504133)::geography, null, 800, false),
  ('buergerhaus-unterfoehring', 'Bürgerhaus Unterföhring', 'Kultur- und Bürgerzentrum in Unterföhring, Veranstaltungsort für Konzerte und Gemeindeevents.', 'Münchner Straße 65', '85774', 'Unterföhring', ST_MakePoint(11.6394095, 48.1914361)::geography, 'https://www.buergerhaus-unterfoehring.de/', null, false),
  ('kulturzentrum-trudering', 'Kulturzentrum Trudering', 'Kommunales Kulturzentrum im Münchner Stadtteil Trudering mit Sälen für Konzerte und Veranstaltungen.', 'Wasserburger Landstraße 32', '81825', 'München', ST_MakePoint(11.6705393, 48.1193281)::geography, 'https://www.kulturzentrum-trudering.de/', null, false),
  ('fat-cat', 'Fat Cat', 'Kulturzentrum in Zwischennutzung im alten Gasteig-Gebäude in Haidhausen, mit mehreren Sälen (u.a. einem eigenen, gleichnamigen "Carl-Orff-Saal") für Konzerte, Comedy und Theater.', 'Rosenheimer Straße 5', '81667', 'München', ST_MakePoint(11.5906675, 48.131765)::geography, 'https://www.fatcat-muc.de/', 600, false),
  ('ampere', 'Ampere', 'Konzert- und Clubvenue im Muffatwerk-Komplex an der Isar, eröffnet 2010, Programmschwerpunkt Konzerte und DJ-Events.', 'Zellstraße 4', '81667', 'München', ST_MakePoint(11.5894533, 48.1330499)::geography, 'https://www.muffatwerk.de/', null, false),
  ('einstein-kultur', 'Einstein Kultur', 'Stadtteilkulturzentrum in Haidhausen seit 2012, in ehemaligen Bierkellern untergebracht, Programm für Musik und Diskurs.', 'Einsteinstraße 42', '81675', 'München', ST_MakePoint(11.6008844, 48.1354033)::geography, 'https://www.einsteinkultur.de/', null, false),
  ('bayerischer-hof-festsaal', 'Bayerischer Hof – Festsaal', 'Historischer Festsaal im Grandhotel Bayerischer Hof mit Art-déco-Treppenhaus und öffenbarem Glasdach, seit über 125 Jahren Veranstaltungsort.', 'Promenadeplatz 2-6', '80333', 'München', ST_MakePoint(11.5726992, 48.1405561)::geography, 'https://www.bayerischerhof.de/', 870, false),
  ('schloss-nymphenburg', 'Schloss Nymphenburg', 'Barockes und Rokoko-Schloss im Münchner Westen, von 1715 bis 1918 Sommerresidenz der Wittelsbacher.', 'Schloss Nymphenburg 1', '80638', 'München', ST_MakePoint(11.5032967, 48.1582569)::geography, 'https://www.schloesser.bayern.de/', null, false),
  ('schloss-blutenburg', 'Schloss Blutenburg', 'Spätgotische Schlossanlage mit Kapelle von 1488–97, Wittelsbacher Wasserschloss an der Würm, heute Ort für Kammerkonzerte im Sommer.', 'Seldweg 15', '81247', 'München', ST_MakePoint(11.4571439, 48.1633994)::geography, 'https://www.schlosskonzerte-blutenburg.de/', null, false),
  ('schloss-schleissheim', 'Schloss Schleissheim', 'Barocke Schlossanlage in Oberschleißheim mit prunkvollem Festsaal im Neuen Schloss, Ort sommerlicher Residenz-Solisten-Konzerte.', 'Max-Emanuel-Platz 1', '85764', 'Oberschleißheim', ST_MakePoint(11.5610072, 48.2488391)::geography, 'https://www.schloesser-schleissheim.de/', null, false),
  ('auferstehungskirche', 'Auferstehungskirche', 'Eine der größten evangelischen Kirchen Münchens, 1931 von German Bestelmeyer erbaut, mit rund 800 Plätzen; Ort der Konzertreihe „Westend Vibes".', 'Gollierstraße 55', '80339', 'München', ST_MakePoint(11.5381109, 48.1355039)::geography, 'https://www.auferstehungskirche.de/', 800, false),
  ('asamkirche', 'Asamkirche', 'Barocke Bürgerkirche der Gebrüder Asam (1733–1746), eines der bedeutendsten Werke des süddeutschen Spätbarock.', 'Sendlinger Straße 32', '80331', 'München', ST_MakePoint(11.5695229, 48.1352103)::geography, null, null, false),
  ('kunsthalle-muenchen', 'Kunsthalle München', 'Ausstellungshaus für internationale Kunst in den Fünf Höfen, Gebäude von Herzog & de Meuron.', 'Theatinerstraße 8', '80333', 'München', ST_MakePoint(11.5758786, 48.1399663)::geography, 'https://www.kunsthalle-muc.de/', null, false),
  ('pinakothek-der-moderne', 'Pinakothek der Moderne', 'Museum für Kunst, Design, Grafik und Architektur im Kunstareal, eines der größten Sammlungshäuser Europas.', 'Barer Straße 40', '80333', 'München', ST_MakePoint(11.5722272, 48.1471604)::geography, 'https://www.pinakothek.de/', null, false),
  ('muenchner-stadtmuseum', 'Münchner Stadtmuseum', 'Stadtgeschichtliches Museum im ehemaligen Zeughaus am St.-Jakobs-Platz; wegen Sanierung mit Interimsausstellung.', 'St.-Jakobs-Platz 1', '80331', 'München', ST_MakePoint(11.5730339, 48.1351078)::geography, 'https://www.muenchner-stadtmuseum.de/', null, false),
  ('deutsches-museum-ehrensaal', 'Deutsches Museum – Ehrensaal', 'Zentraler Gedenksaal im Deutschen Museum für bedeutende Wissenschaftler und Techniker, eröffnet 1925, gelegentlich Ort von Kammerkonzerten; Museumsflügel derzeit sanierungsbedingt eingeschränkt.', 'Museumsinsel 1', '80538', 'München', ST_MakePoint(11.5829090, 48.1300409)::geography, 'https://www.deutsches-museum.de/', null, false),
  ('haus-der-kunst', 'Haus der Kunst', 'Zentrum für zeitgenössische Kunst am Südrand des Englischen Gartens, 1937 erbaut.', 'Prinzregentenstraße 1', '80538', 'München', ST_MakePoint(11.5852836, 48.1444409)::geography, 'https://hausderkunst.de/', null, false),
  ('muenchner-kammerspiele', 'Münchner Kammerspiele', 'Traditionsreiches Sprechtheater im Jugendstil-Schauspielhaus von Littmann/Riemerschmid (1901), gelegentlich Ort für Konzerte und Crossover-Formate.', 'Maximilianstraße 26', '80539', 'München', ST_MakePoint(11.5824700, 48.1384040)::geography, 'https://www.muenchner-kammerspiele.de/', 727, false),
  ('muenchner-volkstheater', 'Münchner Volkstheater', '2021 eröffneter Theater-Neubau im Schlachthofviertel mit Hauptbühne für rund 600 Zuschauer sowie flexiblen Nebenspielstätten.', 'Tumblingerstraße 29', '80337', 'München', ST_MakePoint(11.5558987, 48.1236634)::geography, 'https://www.muenchner-volkstheater.de/', 600, false),
  ('lenbachhaus', 'Lenbachhaus', 'Kunstmuseum in der ehemaligen Künstlervilla Franz von Lenbachs, bekannt für die Sammlung des "Blauer Reiter" sowie Kammerkonzerte im historischen Ambiente.', 'Luisenstraße 33', '80333', 'München', ST_MakePoint(11.5635027, 48.1469399)::geography, 'https://www.lenbachhaus.de/', null, false)
on conflict (slug) do nothing;
