-- Generated by Claude Code
-- Ticketlinks: ticket_url war für ~100 % der Events leer, obwohl ein Teil
-- der Quellen als website_url direkt auf einen Ticketshop zeigt
-- (muenchenticket.de, reservix.de, eventim.de, tickets.staatstheater.bayern, …).
-- Diese URLs sind echte Kaufseiten und sollen ticket_url sein, damit die
-- Clients "Tickets kaufen" statt nur "Zur Veranstaltungsseite" anbieten.
-- Gilt per Trigger auch für alle künftigen Importe.

create or replace function public.is_ticket_shop_url(url text)
returns boolean
language sql
immutable
as $$
  select url ~* '^https?://([a-z0-9-]+\.)*(muenchenticket\.(de|net)|reservix\.de|eventim\.de|ticketmaster\.[a-z.]+|oeticket\.com|wien-ticket\.at|br-ticket\.de|ticketino\.com|ticketcorner\.ch|adticket\.de|eventbrite\.[a-z.]+|tixforgigs\.com|ticket-regional\.de)(/|$)'
      or url ~* '^https?://tickets\.[a-z0-9.-]+/'
      or url ~* '^https?://[a-z0-9.-]+/pth\.webshop/';
$$;

create or replace function public.events_set_ticket_url_from_shop()
returns trigger
language plpgsql
as $$
begin
  if new.ticket_url is null and new.website_url is not null
     and public.is_ticket_shop_url(new.website_url) then
    new.ticket_url := new.website_url;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_events_ticket_url_from_shop on public.events;
create trigger trg_events_ticket_url_from_shop
  before insert or update of website_url on public.events
  for each row execute function public.events_set_ticket_url_from_shop();

update public.events
set ticket_url = website_url
where ticket_url is null
  and website_url is not null
  and public.is_ticket_shop_url(website_url);
