-- Generated by Claude Code
-- Alte Oper Frankfurt (api): der Parser "json_api" existierte nur in der
-- config, aber nicht im Code -> jeder Lauf endete mit "no event items", der
-- Body-Hash wurde trotzdem gespeichert und alle Folgeläufe liefen als
-- skipped_unchanged. Frankfurt hatte dadurch keine kommenden Events.
-- Jetzt: json_api-Parser (siehe ingest-source/parsers/json_api.ts) mit
-- Paginierung (423 Termine, 10 pro Seite), Kauflink (ticket_link) und Bild.
update public.sources
set config = (coalesce(config, '{}'::jsonb) - 'httpCache') || jsonb_build_object(
      'nextPath', 'next',
      'maxPages', 50,
      'skipPastPath', 'is_past',
      'ticketPath', 'ticket_link',
      'imagePath', 'image.url'
    )
where name = 'Alte Oper Frankfurt'
  and type = 'api'
  and config->>'parser' = 'json_api';
