"use client";

import { Analytics } from "@vercel/analytics/next";
import { useSyncExternalStore } from "react";

const key = "klangradar-analytics-consent";
const changeEvent = "klangradar-consent-change";

function subscribe(onChange: () => void) {
  window.addEventListener("storage", onChange);
  window.addEventListener(changeEvent, onChange);
  return () => {
    window.removeEventListener("storage", onChange);
    window.removeEventListener(changeEvent, onChange);
  };
}

function readConsent() {
  try {
    return localStorage.getItem(key) ?? "none";
  } catch {
    return "none";
  }
}

function saveConsent(value: "yes" | "no") {
  try {
    localStorage.setItem(key, value);
  } catch {
    // Ohne Speicher gilt die Wahl nur bis zum Neuladen.
  }
  window.dispatchEvent(new Event(changeEvent));
}

// Generated by Claude Code: Der Server kennt localStorage nicht und rendert
// deshalb nichts ("ssr"); erst im Browser erscheinen Banner bzw. Analytics.
// Vorher las der useState-Initializer localStorage direkt und erzeugte auf
// jeder Seite einen Hydration-Fehler (Server: Banner, Browser: nichts).
export function ConsentAnalytics() {
  const consent = useSyncExternalStore(subscribe, readConsent, () => "ssr");
  if (consent === "ssr" || consent === "no") return null;
  if (consent === "yes") return <Analytics />;
  return (
    <div className="fw-rise fixed inset-x-4 bottom-4 z-50 mx-auto max-w-lg rounded-xl border border-[#EAEAEA] bg-white p-4">
      <p className="text-sm font-semibold text-[#111111]">Datenschutz</p>
      <p className="mt-1 text-xs leading-relaxed text-[#4A4A4A]">
        Mit deiner Zustimmung messen wir anonym, welche Seiten genutzt werden. Details stehen in der Datenschutzerklärung.
      </p>
      <div className="mt-3 flex gap-2">
        <button
          type="button"
          onClick={() => saveConsent("no")}
          className="rounded-lg border border-[#DADADA] px-3 py-2 text-xs font-medium text-[#111111] hover:border-[#111111]"
        >
          Ablehnen
        </button>
        <button
          type="button"
          onClick={() => saveConsent("yes")}
          className="rounded-lg bg-[#2D2A6E] px-3 py-2 text-xs font-medium text-white hover:bg-[#1F1D52]"
        >
          Akzeptieren
        </button>
      </div>
    </div>
  );
}
