"use client";

import { usePathname } from "next/navigation";
import { NAV_GROUPS, bestMatchingHref } from "@/components/sidebar";

// Zeigt in der Kopfzeile, wo man gerade ist ("Programm / Veranstaltungen"),
// statt eines statischen Untertitels. Generated by Claude Code.
export function DashboardBreadcrumb() {
  const pathname = usePathname();
  const hrefs = NAV_GROUPS.flatMap((group) => group.items.map((item) => item.href));
  const active = pathname ? bestMatchingHref(pathname, hrefs) : null;
  const group = NAV_GROUPS.find((g) => g.items.some((item) => item.href === active));
  const item = group?.items.find((i) => i.href === active);

  return (
    <nav aria-label="Pfad" className="flex min-w-0 items-center gap-2 text-[13px]">
      <span className="text-[#6B6B6B]">{group?.label ?? "Redaktion"}</span>
      {item && (
        <>
          <span aria-hidden="true" className="text-[#BDBDBD]">/</span>
          <span key={item.href} className="fw-fade truncate font-medium text-[#111111]">
            {item.label}
          </span>
        </>
      )}
    </nav>
  );
}
