"use client";

import Link from "next/link";
import Image from "next/image";
import { usePathname } from "next/navigation";
import { useMemo, useState, useSyncExternalStore } from "react";

// Flat-White-Redesign (Generated by Claude Code, Okt. 2026; Nutzer erlaubte
// ausdrücklich, Navigation und Struktur zu optimieren): die vier großen
// Gruppen (bis zu 15 Einträge) sind nach Arbeitsablauf neu geschnitten —
// "Heute" (was jetzt ansteht), "Programm" (Termine), "Wissen" (Stammdaten),
// "Datenqualität", "Vertrauen" (Claims/Verifizierung), "Import & System".
// Alle bisherigen Einträge und Pfade bleiben erhalten. Dazu: Schnellsuche
// über alle Einträge und auf-/zuklappbare Gruppen (Zustand pro Browser).
export const NAV_GROUPS = [
  {
    label: "Heute",
    items: [
      { href: "/wichtig", label: "Offene Aufgaben" },
      { href: "/todos", label: "To-Dos" },
      { href: "/review-queue", label: "Review-Queue" },
      { href: "/cancellations", label: "Absage-Review" },
      { href: "/content-reports", label: "Meldungen & Fehler" },
    ],
  },
  {
    label: "Programm",
    items: [
      { href: "/events", label: "Veranstaltungen" },
      { href: "/event-groups", label: "Event-Gruppen" },
      { href: "/festivals", label: "Festivals" },
      { href: "/event-promotions", label: "Event-Promotions" },
      { href: "/editorial-collections", label: "Redaktionelle Sammlungen" },
      { href: "/media", label: "Bilderfreigabe" },
    ],
  },
  {
    label: "Wissen",
    items: [
      { href: "/persons", label: "Personen" },
      { href: "/ensembles", label: "Ensembles" },
      { href: "/works", label: "Werke" },
      { href: "/venues", label: "Venues" },
      { href: "/organizers", label: "Veranstalter" },
      { href: "/ensemble-families", label: "Ensemblefamilien" },
      { href: "/knowledge-graph", label: "Knowledge Graph" },
    ],
  },
  {
    label: "Datenqualität",
    items: [
      { href: "/qualitaetspruefung", label: "Qualitätsprüfung" },
      { href: "/data-quality", label: "Recherche & Anreicherung" },
      { href: "/duplicates", label: "Duplikate" },
      { href: "/entity-candidates", label: "Entity-Kandidaten" },
      { href: "/aliases", label: "Schreibweisen & Aliasse" },
      { href: "/work-image-reuse", label: "Werk-Bild-Verknüpfungen" },
    ],
  },
  {
    label: "Vertrauen",
    items: [
      { href: "/entity-claims", label: "Veranstalter-Claims" },
      { href: "/entity-edit-suggestions", label: "Profiländerungsvorschläge" },
      { href: "/entity-trust", label: "Verifizierung" },
    ],
  },
  {
    label: "Import & System",
    items: [
      { href: "/sources", label: "Datenquellen & Import" },
      { href: "/source-health", label: "Quellen-Gesundheit" },
      { href: "/attributes", label: "Attribute & Inspiration" },
      { href: "/tags", label: "Tags" },
      { href: "/regions", label: "Regionen" },
      { href: "/users", label: "Benutzer" },
    ],
  },
];

const COLLAPSED_STORAGE_KEY = "klangradar.sidebar.collapsed";
const COLLAPSED_EVENT = "klangradar-sidebar-collapsed";

function subscribeCollapsed(onChange: () => void) {
  window.addEventListener("storage", onChange);
  window.addEventListener(COLLAPSED_EVENT, onChange);
  return () => {
    window.removeEventListener("storage", onChange);
    window.removeEventListener(COLLAPSED_EVENT, onChange);
  };
}

function readCollapsed() {
  try {
    return window.localStorage.getItem(COLLAPSED_STORAGE_KEY) ?? "[]";
  } catch {
    return "[]";
  }
}

// Ermittelt den am genauesten passenden Nav-Eintrag statt jeden Präfix-Treffer
// separat aktiv zu markieren — sonst blieb z.B. "Duplikate-Review" (/duplicates)
// dauerhaft blau hervorgehoben, auch auf /duplicates/persons oder
// /duplicates/works, weil deren Pfad ebenfalls mit "/duplicates" beginnt und
// jeder Eintrag unabhängig voneinander geprüft wurde (Nutzerfeedback: "der
// blaue hintergrund hängt immer bei duplikate review fest, auch wenn man zu
// einer anderen kategorie wechselt").
export function bestMatchingHref(pathname: string, hrefs: string[]): string | null {
  let best: string | null = null;
  for (const href of hrefs) {
    if (pathname === href || pathname.startsWith(`${href}/`)) {
      if (!best || href.length > best.length) best = href;
    }
  }
  return best;
}

export function Sidebar({ userEmail }: { userEmail?: string }) {
  const pathname = usePathname();
  const [query, setQuery] = useState("");
  // Zustand pro Browser über useSyncExternalStore (Server rendert alles offen,
  // danach übernimmt der Browser den gespeicherten Stand ohne Hydration-Fehler).
  const collapsedRaw = useSyncExternalStore(subscribeCollapsed, readCollapsed, () => "[]");
  const collapsed = useMemo(() => {
    try {
      return new Set(JSON.parse(collapsedRaw) as string[]);
    } catch {
      return new Set<string>();
    }
  }, [collapsedRaw]);

  const toggleGroup = (label: string) => {
    const next = new Set(collapsed);
    if (next.has(label)) next.delete(label);
    else next.add(label);
    try {
      window.localStorage.setItem(COLLAPSED_STORAGE_KEY, JSON.stringify([...next]));
      window.dispatchEvent(new Event(COLLAPSED_EVENT));
    } catch {
      // Ohne localStorage (privates Fenster) bleibt alles aufgeklappt.
    }
  };

  const activeHref = pathname
    ? bestMatchingHref(
        pathname,
        NAV_GROUPS.flatMap((group) => group.items.map((item) => item.href)),
      )
    : null;

  const normalizedQuery = query.trim().toLowerCase();
  const groups = NAV_GROUPS.map((group) => ({
    ...group,
    items: normalizedQuery
      ? group.items.filter((item) => item.label.toLowerCase().includes(normalizedQuery))
      : group.items,
  })).filter((group) => group.items.length > 0);

  return (
    <aside className="dashboard-sidebar">
      <div className="dashboard-brand">
        <span className="dashboard-brand-mark" aria-hidden="true">
          <Image src="/app-logo.svg" alt="" width={40} height={40} priority />
        </span>
        <span className="min-w-0">
          <span className="block truncate text-[14px] font-semibold tracking-tight text-[#111111]">Klangradar</span>
          <span className="block truncate text-[12px] text-[#6B6B6B]">Redaktion</span>
        </span>
      </div>
      <label className="block px-0.5">
        <span className="sr-only">Navigation durchsuchen</span>
        <input
          type="search"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Springe zu …"
          className="dashboard-nav-search"
        />
      </label>
      <nav className="dashboard-sidebar-nav" aria-label="Redaktion">
        {groups.map((group) => {
          // Beim Suchen und für die Gruppe der aktuellen Seite immer offen.
          const containsActive = group.items.some((item) => item.href === activeHref);
          const open = Boolean(normalizedQuery) || containsActive || !collapsed.has(group.label);
          const listId = `nav-group-${group.label.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`;
          return (
            <div key={group.label} className="dashboard-nav-group">
              <button
                type="button"
                className="dashboard-nav-group-toggle"
                aria-expanded={open}
                aria-controls={listId}
                onClick={() => toggleGroup(group.label)}
              >
                {group.label}
                <svg aria-hidden="true" width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M3 4.5l3 3 3-3" />
                </svg>
              </button>
              <div id={listId} className="dashboard-nav-collapse" data-open={open}>
                <div className="flex flex-col gap-px">
                  {group.items.map((item) => {
                    const active = item.href === activeHref;
                    return (
                      <Link
                        key={item.href}
                        href={item.href}
                        tabIndex={open ? undefined : -1}
                        aria-current={active ? "page" : undefined}
                        className={`dashboard-nav-item ${active ? "dashboard-nav-item-active" : ""}`}
                      >
                        {item.label}
                      </Link>
                    );
                  })}
                </div>
              </div>
            </div>
          );
        })}
        {groups.length === 0 && <p className="px-3 py-2 text-[13px] text-[#6B6B6B]">Kein Bereich gefunden.</p>}
      </nav>
      <div className="border-t border-[#EAEAEA] pt-3">
        <Link href="/veranstalter" className="dashboard-nav-item">
          Zum Veranstalterportal
          <span aria-hidden="true">→</span>
        </Link>
      </div>
      {userEmail && (
        <div className="dashboard-account" title={userEmail}>
          <span className="dashboard-account-avatar" aria-hidden="true">{userEmail.slice(0, 1).toUpperCase()}</span>
          <span className="min-w-0">
            <span className="block text-[11px] text-[#6B6B6B]">Angemeldet</span>
            <span className="block truncate text-[12px] text-[#111111]">{userEmail}</span>
          </span>
        </div>
      )}
    </aside>
  );
}
