// Generated by Claude Code
import UIKit

/// Zentrale Haptik-Palette mit drei Intensitäten (Nutzervorgabe
/// 2026-09-03), statt an jeder Stelle einzeln `UIImpactFeedbackGenerator`
/// zu instanziieren. Bewusst als reine statische Trigger, kein State —
/// jeder Aufruf erzeugt und feuert seinen eigenen Generator, was für
/// gelegentliche UI-Events (kein High-Frequency-Tracking wie Scroll)
/// ausreicht und keinen dauerhaft vorbereiteten Generator erfordert.
enum Haptics {
    /// Für Interaktionen, die selbst noch keine endgültige Entscheidung
    /// sind: Auswahl-Chips, Filter-Toggles, Stadt antippen (nicht
    /// bestätigen), Kalendertag wechseln.
    static func light() {
        UIImpactFeedbackGenerator(style: .light).impactOccurred()
    }

    /// Für abgeschlossene, aber alltägliche Bestätigungen: Folgen, Event
    /// speichern, Erinnerung setzen, Liste/Eintrag hinzufügen, Stadt
    /// bestätigen, Mindestauswahl erreicht.
    static func confirm() {
        UINotificationFeedbackGenerator().notificationOccurred(.success)
    }

    /// Für seltene, bedeutsame Momente: Registrierung abgeschlossen,
    /// Termin erfolgreich im Kalender, Check-in, Abzeichen/Meilensteine.
    static func strong() {
        UIImpactFeedbackGenerator(style: .heavy).impactOccurred()
    }

    /// Sanfter Impuls fürs Entfolgen/Ausblenden — bewusst schwächer als
    /// `confirm()`, da es keine positive Bestätigung, sondern eine
    /// zurückgenommene Aktion ist.
    static func soft() {
        UIImpactFeedbackGenerator(style: .soft).impactOccurred()
    }

    /// Zurückhaltender Warn-Impuls für Absagen/Programmänderungen —
    /// ausdrücklich nur beim aktiven Öffnen einer solchen Meldung, nicht
    /// beim bloßen Laden der Daten.
    static func warning() {
        UINotificationFeedbackGenerator().notificationOccurred(.warning)
    }
}
