import type { Metadata } from "next";

export const metadata: Metadata = { title: "Nutzungsbedingungen", description: "Nutzungsbedingungen für Klangradar.", alternates: { canonical: "/nutzungsbedingungen" } };

export default function TermsPage() {
  return <div className="mx-auto max-w-2xl px-6 py-16"><h1 className="type-heading text-3xl text-[#1d1d1f]">Nutzungsbedingungen</h1><p className="mt-2 mb-10 text-sm text-[#86868b]">Stand: September 2026 · Bitte vor Veröffentlichung rechtlich prüfen.</p><Section title="1. Geltungsbereich">Diese Bedingungen regeln die Nutzung der Klangradar-App und Weboberfläche. Für kostenpflichtige Angebote im Veranstalterportal gelten zusätzlich die jeweils vor Abschluss angezeigten Angebots- und Zahlungsbedingungen.</Section><Section title="2. Klangradar als Informationsdienst">Klangradar bündelt Informationen zu Konzerten, Künstler:innen und Spielstätten. Termine, Programme, Preise, Verfügbarkeiten und externe Ticketlinks können sich ändern; verbindlich sind die Angaben des jeweiligen Veranstalters oder Ticketanbieters.</Section><Section title="3. Konto und Nutzung">Nutzer:innen sind für die Richtigkeit ihrer Angaben und die Geheimhaltung ihrer Zugangsdaten verantwortlich. Die Plattform darf nicht missbräuchlich, rechtswidrig oder zur Beeinträchtigung anderer genutzt werden.</Section><Section title="4. Inhalte und Rechte">Eigene Inhalte dürfen nur hochgeladen werden, wenn die nötigen Rechte vorliegen. Klangradar darf sie zur Bereitstellung und Darstellung des Dienstes verarbeiten. Rechte Dritter bleiben unberührt.</Section><Section title="5. Haftung">Klangradar haftet nach den gesetzlichen Vorschriften bei Vorsatz, grober Fahrlässigkeit sowie bei Schäden an Leben, Körper oder Gesundheit. Im Übrigen ist die Haftung im gesetzlich zulässigen Umfang beschränkt.</Section><Section title="6. Änderungen und Kontakt">Wir können den Dienst und diese Bedingungen weiterentwickeln, soweit dies Nutzer:innen zumutbar ist. Fragen erreichst du unter jakob@klangradar.com.</Section></div>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-10"><h2 className="type-heading mb-2 text-lg text-[#1d1d1f]">{title}</h2><p className="text-sm leading-relaxed text-[#3a3a3c]">{children}</p></section>; }
