// Generated by Claude Code
import XCTest
@testable import KlangradarNative

/// Deckt `UserRepository.allCityRegions()` ab -- muss alle Städte aus
/// `city_regions` liefern (auch `is_active == false`), sortiert nach
/// `sort_order`, mit korrekt gemapptem `editorial_status`/`isLive`. Kein
/// Netzwerkzugriff nötig, ein HTTPClient-Test-Double reicht.
private final class StubHTTPClient: HTTPClient, @unchecked Sendable {
    private(set) var requests: [URLRequest] = []
    let responseBody: Data

    init(responseBody: Data) {
        self.responseBody = responseBody
    }

    func data(for request: URLRequest) async throws -> (Data, HTTPURLResponse) {
        requests.append(request)
        let response = HTTPURLResponse(url: request.url!, statusCode: 200, httpVersion: nil, headerFields: nil)!
        return (responseBody, response)
    }
}

final class CityRegionOptionTests: XCTestCase {
    private func makeRepository(_ client: StubHTTPClient) -> UserRepository {
        let configuration = APIConfiguration(supabaseURL: URL(string: "https://example.supabase.co")!, supabaseAnonKey: "anon")
        return UserRepository(client: SupabaseRESTClient(configuration: configuration, httpClient: client))
    }

    func testAllCityRegionsReturnsInactiveSoftLaunchCitiesTooAndQueriesUnfiltered() async throws {
        let munichID = UUID()
        let berlinID = UUID()
        let json = """
        [
          {"id": "\(munichID.uuidString)", "slug": "munich", "name_de": "München", "short_name_de": "München", "region_name": "Bayern", "is_active": true, "editorial_status": "live", "sort_order": 0, "latitude": 48.13, "longitude": 11.58},
          {"id": "\(berlinID.uuidString)", "slug": "berlin", "name_de": "Berlin", "short_name_de": "Berlin", "region_name": "Berlin", "is_active": false, "editorial_status": "soft_launch", "sort_order": 1, "latitude": 52.52, "longitude": 13.4}
        ]
        """
        let client = StubHTTPClient(responseBody: Data(json.utf8))
        let repository = makeRepository(client)

        let cities = try await repository.allCityRegions()

        XCTAssertEqual(cities.count, 2, "soft_launch/is_active=false Städte dürfen nicht herausgefiltert werden")
        XCTAssertEqual(cities.map(\.slug), ["munich", "berlin"], "Reihenfolge muss sort_order folgen")
        XCTAssertTrue(cities[0].isLive)
        XCTAssertFalse(cities[1].isLive)
        XCTAssertFalse(cities[1].isActive)

        let request = try XCTUnwrap(client.requests.first)
        XCTAssertTrue(request.url?.path.contains("/city_regions") == true)
        let query = request.url?.query ?? ""
        XCTAssertFalse(query.contains("is_active=eq.true"), "allCityRegions() darf, anders als activeRegions(), nicht nach is_active filtern")
    }
}
